### ISSUE TITLE
Chart library

### ISSUE THREAD

**Issue by FrancoisM** [Microsoft/ApplicationInsights-Home#101]
Do you use a third party open source library for your graphs?
I'd like to reuse your dependency graph to display trace data within my mobile app.

**Comment by SergeyKanzhelev** [comment]
@madeleinefletcher @AlexBulankou  can you help with this question.

@FrancoisM - you can report traces from mobile app to Application Map and see the map in Azure Portal instead of building your own visualization.

**Comment by FrancoisM** [comment]
To be sure we talk about the same thing: here I call mobile app the actual smartphone app not the Azure Mobile App Backend.
What is Application Map?

**Comment by FrancoisM** [comment]
Ok I see what Application Map is.
It's not what I'm looking for.
I want to produce charts like the dependency bar timeline graph.

**Comment by SergeyKanzhelev** [comment]
Try [Zipkin](http://zipkin.io/)

**Comment by FrancoisM** [comment]
Tks!
