### ISSUE TITLE
Average values for metrics on custom event when sampling is used

### ISSUE THREAD

**Issue by Kyle2123** [Microsoft/ApplicationInsights-Home#103]
I have a custom event that includes a custom metric that records the time that the event took to process.  I have sampling configured on my application to 10%.  When I add a chart in Metrics Explorer that filters on this event and then displays the average of my custom metric for processing time, the values reported are 1/10th of what I would expect them to be.

According to the [documentation](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-metrics-explorer), average is calculated by dividing the sum by the number of datapoints received over the interval.  I believe this is why my numbers are 1/10th of what they should be, because the itemCount on each row is 10.

How can I calculate averages for custom metrics on an event in Metrics Explorer when sampling was in use?  I would like the average just across the values reported.  In other words, sum(value)/actual count, instead of sum(value)/itemCount.

**Comment by SergeyKanzhelev** [comment]
will this work for you? `sum(value)/count()`?

**Comment by SergeyKanzhelev** [comment]
Sorry for delayed reply.
