### ISSUE TITLE
HTTPS calls marked incorrectly as SQL dependency

### ISSUE THREAD

**Issue by shkrishms** [Microsoft/ApplicationInsights-Home#104]
I noticed this on my server side. I am manually marking http post/get requests by

this.appInsightsClient.TrackDependency(depedencyName, depedencyAction, startDateTime, elapsed, success);
and correlating them to request by implementing ITelemetryInitializer .

On the analytics logs, I see https calls marked as SQL type. Not sure if this is from my tracking or from appinsights tracking. I hope they are not duplicated.

This is the target url: https://yodaalertservice.cloudapp.net/v1/

**Comment by SergeyKanzhelev** [comment]
Dup for this issue: https://github.com/Microsoft/ApplicationInsights-dotnet/issues/405

I believe the fix will be deployed early next week.

Sorry for the inconvinience
