### ISSUE TITLE
Security of Web tests

### ISSUE THREAD

**Issue by shkrishms** [Microsoft/ApplicationInsights-Home#107]
Hi,
I want to add multi step web tests to application insights.  I see that web tests have context parameters to add username and password.
I would like to know how this information is secured in the web tests when uploaded as a part of application insights?

**Comment by SergeyKanzhelev** [comment]
@SoubhagyaDash can you please reply here

**Comment by shkrishms** [comment]
Hi,
This information will be useful for me to proceed further. 

-Sharanya

**Comment by SoubhagyaDash** [comment]
@shkrishms Web tests are encrypted in transit and in our backend config store.

**Comment by shkrishms** [comment]
Thanks.
