### ISSUE TITLE
Is no more Application Insight local SDK a thing ?

### ISSUE THREAD

**Issue by mlorbetske** [Microsoft/ApplicationInsights-Home#114]
_From @Bartmax on March 16, 2017 13:29_

So no more `local SDK only`, is this now an azure-only service ?

If it's not, then the UI on 2017 is really crafted by evil azure $ eaters. (just kidding, no offense intended)

Also the docs points to the old UI, showing an option not available on 2017.
![pasted image at 2017_03_16 10_22 am](https://cloud.githubusercontent.com/assets/3386797/23998162/fb45dee2-0a32-11e7-85c1-cea08fe44d9b.png)

As an Azure customer that uses app insights already, can you please clarify the situation and if there's a change on how this services is/was used/consumed, can you point to the announcement about it? 

Thanks.

_Copied from original issue: aspnet/Tooling#1019_

**Comment by SergeyKanzhelev** [comment]
@mlorbetske what makes you think there is no more local mode? We do support it.

CC: @acearun @gardnerjr

**Comment by mlorbetske** [comment]
The issue was posted on aspnet/tooling by @bartmax, I believe he's looking for documentation on how to be in that mode as the tools have changed.

**Comment by gardnerjr** [comment]
that link doesn't show in 2017 **because the sdk is already installed by ASP.NET tooling** in VS2017, the only choice you have in the window after that is to *configure it*.

that link only shows when the project has *no AI of any kind in it* (a totally clean project).

**Comment by gardnerjr** [comment]
To see the link in 2017, create a new asp.net or asp.net core project, and remove the references to AI  (in core, open the csproj and remove the `PackageReference` for Application Insights.  Right click the project, and the Application Insights submenu will be gone.  right click the project and do either add->connected service and pick application insights, or right click add->application insights to see the same configure window as above, with the link at the bottom:
![local only in 2017](https://cloud.githubusercontent.com/assets/10158007/24874532/d9327774-1dd9-11e7-9d7c-73abaf78898c.png)
