### ISSUE TITLE
location_Country for DependencyTelemetry

### ISSUE THREAD

**Issue by saxenark** [Microsoft/ApplicationInsights-Home#116]
Hi,

I am not seeing values for client city, client state, or province and client country or region, in DependencyTelemetry that we are explicitly creating for a 3rd party API call. We are using 2.1.0 version of Microsoft.ApplicationInsights library.

What could be the reason for this?

Thanks,
Anubhav.

**Comment by SergeyKanzhelev** [comment]
This is how we collect [client IP](http://apmtips.com/blog/2016/07/05/client-ip-address) and then convert it to the geo location. There may be two options - you set `.Context.Location.Ip` context property to the IP address that we cannot resolve (you may set it explicitly or implicitly via Client IP header [telemetry initializer](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-configuration-with-applicationinsights-config#telemetry-initializers-aspnet))

Or you do not set it and it is taken as your servers' IP address. And it is also cannot be resolved.

In either way - validate the value of location_ip header first.

**Comment by saxenark** [comment]
Oh Ok. Let me try this.

**Comment by saxenark** [comment]
One more question, I want to know if there is a coding / design standard documentation available for implementing telemetry in web applications. I see lots of different understandings in each team and hence everybody lands up in doing telemetry in their own. Is there some sort of standardization/recommendation/best practices available?

**Comment by SergeyKanzhelev** [comment]
> documentation available for implementing telemetry 

What do you mean by implementing telemetry? There are documents on different aspects of it, but I need to have more context to be able to answer this question.

**Comment by saxenark** [comment]
Hi, Here is a hint of what I mean by standardization. I like to think of the documentation as the specs for a language like C++ or C#, but there are several documents/books/articles etc on best practices, guidelines, dos&dont's etc. I am looking at something similar from telemetry standardization for all apps in our portfolio.

![image](https://cloud.githubusercontent.com/assets/2850526/25078369/cc25e612-234f-11e7-95e5-521bc4ed4efd.png)

**Comment by SergeyKanzhelev** [comment]
This is exactly the document I plan to work on later this week. Basically we will explain every Application Insights type and context property with the scenarios how it should be used.

**Comment by SergeyKanzhelev** [comment]
Original question resolved via #233. For the second issue - feel free to contribute to https://docs.microsoft.com/azure/application-insights/application-insights-data-model using "Edit" button in right upper corner

![image](https://user-images.githubusercontent.com/9950081/41636641-8b46b6ce-7404-11e8-9f0f-b42753bda2e0.png)
