### ISSUE TITLE
Set validateIntegratedModeConfiguration to true

### ISSUE THREAD

**Issue by Mauzer93** [Microsoft/ApplicationInsights-Home#117]
We would like to enable 'validateIntegratedModeConfiguration' in our application (running in integration mode).
However, when we remove the classic asp modules, and enable 'validateIntegratedModeConfiguration', we noticed that removing the classic modules causes unexpected behavior in following scenario:

Browse to http://localhost/
- ISAPI handler gets selected as handler for the request
  - ApplicationInsights HttpModule gets executed
  - Custom HttpModule OnBeginRequest executes and logs the correlation id. (HttpContext.Current?.GetRequestTelemetry()?.Id)
  - Handler does not return a response (no matching middleware to create a http response message)
- StaticFile handler gets selected as handler for the request (next in handlers list)
  - Application Insights HttpModule gets executed
  - Custom HttpModule OnBeginRequest executes and logs the correlation id. (HttpContext.Current?.GetRequestTelemetry()?.Id)
  - DirectoryBrowsing module executes and generates a HTTP 403 response because directory browsing is disabled
  - Application Insights OnEndRequest gets executed and flushes to Azure Application Insights
  - Browser receives HTTP 403 response

In the example above, there will only be 1 request entry in Azure Application Insights (= good) with the last correlation id, the one generated by executing the static file handler.
But our logs will show 2 entries, one for the ISAPI handler scenario and one for the Static File handler scenario with mismatching correlation ids.

This behavior only occurs when we remove the classic asp.net Application Insights http module.

When we no response was generated by the OwinMiddleware, IIS falls back to the static file handler without executing the onEndRequest of the HttpModules called previously, instead, it recalls the OnBeginRequest, which generates a new operation id. After the static file handler found nothing, a 404 is send to the client and the OnEndRequest method of all modules are called. This causes the flush to AI. This is a problem for us, because the operation id used in the logs, are not the same as the one in Application Insights. So we can not correlate those logs with entries in AI.

Is there any way to enable keep validateIntegratedModeConfiguration while removing the classic asp.net Application Insights modules, without having the behavior described above?

Kind Regards,

Manaus Lavens

**Comment by SergeyKanzhelev** [comment]
I believe this issue might go away with the latest version of Application Insights SDK. Please try it out and re-open an issue if it still exists
