### ISSUE TITLE
trace and exception recorded fine but request count is always zero

### ISSUE THREAD

**Issue by krishnasingh1818** [Microsoft/ApplicationInsights-Home#119]
hi,

am using appinsight through nlog target and i am noting that in application insight i see only trace and exception category recorded and rest all (eg request) counts are showing zero and there is nothing displayed in search result with filter of just Request type.

while debugging on local am able to see that local appinsight visualizer records hits under request category too.  Any idea what could be the problem. ?

thank you 
![appinsight](https://cloud.githubusercontent.com/assets/10679463/25463366/587ccb2c-2abb-11e7-8276-86df10c8ec6d.png)

**Comment by SergeyKanzhelev** [comment]
nlog target wouldn't collect any request telemetry items. The described behavior may happen if you are running ASP.NET Core 2.0+ application. For these applications Visual Studio will enable requests collection when running locally in Visual Studio. Please follow appropriate [instructions](https://github.com/Microsoft/ApplicationInsights-aspnetcore#getting-started) to enable requests tracking
