### ISSUE TITLE
ai.device.screenResolution doesn't show in AppInsights Analytics/Metrics Explorer

### ISSUE THREAD

**Issue by tlmii** [Microsoft/ApplicationInsights-Home#124]
I previously followed the instructions [here](https://github.com/Microsoft/ApplicationInsights-Announcements/issues/5) to enable collection of screen resolution in AppInsights.

I can confirm via Fiddler that it is being sent to AppInsights along with the other PageView data.

But I do not see any way to retrieve/analyze these values. It does not show up as an option for Filtering in Metrics Explorer, nor does it show up as a property to address in AppInsights Analytics. 

What am I missing? It looks from #56 that maybe this was the wrong way to go about it:

> Property ContextTagKeys.DeviceScreenResolution is deprecated: "Use custom properties to report the screen resolution."

Is there documentation on the correct way to do this from the JS api? Should that other issue in the announcements be clarified to say it is no longer valid?

**Comment by SergeyKanzhelev** [comment]
Thanks for detailed report. Unfortunately screenResolution is on it's way to deprecation. We have an issue  https://github.com/Microsoft/ApplicationInsights-JS/issues/455 to remove it from code. @KamilSzostak can comment on milestone

**Comment by dankellett** [comment]
Why? This was very useful information.

**Comment by SergeyKanzhelev** [comment]
It was deprecated as a standard dimension: https://github.com/Microsoft/ApplicationInsights-Announcements/issues/5 

You can place screen resolution into custom properties of an event:

``` js
appInsights.queue.push(function () {
    appInsights.context.addTelemetryInitializer(function (envelope) {
        var telemetryItem = envelope.data.baseData;
        if (typeof screen !== "undefined") {
            telemetryItem.properties = telemetryItem.properties || {};
            telemetryItem.properties["ai.device.screenResolution"] = screen.width + "X" + screen.height;
            telemetryItem.properties["ai.device.locale"] = navigator.language || navigator.browserLanguage || "unknown";
        }
    });
});
```

We are considering to add screen resolution as pageview-only custom dimension. What is your use of this property? Are you running analysis like "above the fold" loading time? Or simply want distribution of screen types? Also do you care more of resolution or window size?

**Comment by dankellett** [comment]
When running a web application, screen size distribution is a useful statistic to determine where to spend more time on responsive design elements. We would also use it to see if design is impacting performance.

**Comment by SergeyKanzhelev** [comment]
so you mostly need both dimension in a form of `WWW x HHH`? Not a separate fields for separate dimensions. And you will prefer viewport size than screen resolution? Is it correct understanding of your use case?

**Comment by dankellett** [comment]
Yes, that format would be best for our needs. Both viewport size and screen resolution would be nice, the extra context would help build a bigger story about how users are using our application.

**Comment by SergeyKanzhelev** [comment]
and can you please confirm that collecting those using telemetry initializer works for you.

**Comment by dankellett** [comment]
Sure, please give day or two to confirm.

**Comment by dankellett** [comment]
Confirmed. The data that comes through as a custom data element on the page view is the data point that would be useful to see as a distribution visualization or table.

**Comment by SergeyKanzhelev** [comment]
thank you for confirmation
