### ISSUE TITLE
Data Loss in application insights

### ISSUE THREAD

**Issue by shkrishms** [Microsoft/ApplicationInsights-Home#126]
Hi,
I have been sending a lot of web api requests to an API on our webapp in azure enabled with application insights. But i did not see all the requests reflected there. I sent at least 10 in the last 1 hour, but I only see 1 request.

The itemcount column shows for that request is only 1. How to troubleshoot my missing requests?

The server sdk has adaptive sampling enabled by default. Would that be the cause? i.e it doest even send the telemetry to app insights?

**Comment by cijothomas** [comment]
Whats the version of SDK you are using?
Are your requests succeeding or failing? i.e are you seeing failed requests, but missing all successfull requests?
(there is an open issue https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/175 ) not sure if this is related.

**Comment by shkrishms** [comment]
I have the below packages. There were no failed request. All of them successful
packages\Microsoft.ApplicationInsights.2.2.0\lib\net46\Microsoft.ApplicationInsights.dll

**Comment by SergeyKanzhelev** [comment]
we will need more information to effectively investigate. Closing an issue. Please reopen if needed
