### ISSUE TITLE
Application Insights performance issues

### ISSUE THREAD

**Issue by shkrishms** [Microsoft/ApplicationInsights-Home#128]
Hi,
I am using experimental profiler to see my hot path. It seems like Application insights telemetry tracking seems to contribute to the latency. I have included the below snapshot.

![image](https://user-images.githubusercontent.com/25833342/26902678-06331872-4b8f-11e7-8d74-6a7751bc5f70.png)

**Comment by SergeyKanzhelev** [comment]
Closing as issue not actionable. Application Insights does some work in-process and expect to slow down an execution. If it increase the latency significantly - do you have numbers?
