### ISSUE TITLE
SQL dependency impossibly fast

### ISSUE THREAD

**Issue by rsitrifork** [Microsoft/ApplicationInsights-Home#130]
I have started tracking dependencies in a web project. Partly because we want to keep track of the SQL dependency timings to detect areas where we can do performance tuning. 

I wonder why so many of the dependencies take 0 ms? We are using the built-in SQL dependency tracking with the status monitor installed. 

![image](https://user-images.githubusercontent.com/29540761/27378211-7a6f779c-5677-11e7-9b0c-fdaf88082caf.png)

**Comment by dnduffy** [comment]
In older versions of the SDK there was a problem with the start and stop time for async calls leading to incorrect duration calculations.  Please try updating to the latest beta and see if that fixes the issue.
