### ISSUE TITLE
Detect path parameters in Operation Name

### ISSUE THREAD

**Issue by ishepherd** [Microsoft/ApplicationInsights-Home#131]
Application Insights Analysis doesn’t play nicely with RESTful resources in a lot of scenarios.

Example, GET /Microsoft/ApplicationInsights-Home –

I doubt GitHub would find this a useful Operation Name for analysis.
An Operation Name like ‘GET /{Organization}/{Repo}’ would be much more frequently useful.

[I am hacking this sort of thing with a custom ITelemetryInitializer and custom regexes.](https://stackoverflow.com/questions/44691658/stop-application-insights-including-path-parameters-in-the-operation-name) It’s a nasty solution. The routing is after all known to ASP.NET MVC, could Application Insights discover it with better integration?

**Comment by dnduffy** [comment]
Seems related to https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/430

**Comment by SergeyKanzhelev** [comment]
Dup of this: https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/176 Mark as moved and closing it here
