### ISSUE TITLE
timestamp in telemetry

### ISSUE THREAD

**Issue by saxenark** [Microsoft/ApplicationInsights-Home#133]
Hi,

I would like clarity on the interpretation of the timestamp field in app insights telemetry. Specifically, the documentation here https://docs.microsoft.com/en-us/dotnet/api/microsoft.applicationinsights.datacontracts.tracetelemetry?view=appinsights-2.3.0-beta3 says that is the timestamp of recording. 

However, I would like to know if it is
a) timestamp of the event in the sending client, or
b) timestamp of the event ingestion in app insights
c) something else.

Thanks,
Anubhav.

**Comment by saxenark** [comment]
Also, in case the telemetry event is logged from the client side js scripts, is the time stamp of the AI event, the time on the client machine or on the web server?

**Comment by SergeyKanzhelev** [comment]
@saxenark sorry for delay.

timestamp represents the time event was "created". For request and dependency telemetry it will be a start time of said request and dependencies (time when you called `StartOperation` method of telemetry client). For trace and event - time telemetry item was tracked (`Track` method of telemetry client was called).

It is always the SDK's timestamp.

I'll create an issue to improve the documentation of this property

**Comment by SergeyKanzhelev** [comment]
Please re-open if you have more questions. Feel free to send PR to help improve documentation
