### ISSUE TITLE
Dependency trend arrow incorrect colour

### ISSUE THREAD

**Issue by phatcher** [Microsoft/ApplicationInsights-Home#134]
On the weekly report, the dependency duration is shown as going up but the trend arrow is green not red -  surely longer is worse?

![dependencytime](https://user-images.githubusercontent.com/192778/28011395-12223f0c-655a-11e7-95dd-378a90bcff64.PNG)

**Comment by SergeyKanzhelev** [comment]
@SoubhagyaDash can you please track this request?

**Comment by SergeyKanzhelev** [comment]
closing. Please re-open if it is still an issue
