### ISSUE TITLE
Missing Type in ServiceCollection when upgrading Microsoft.ApplicationInsights.AspNetCore 2.1.0 to 2.1.1

### ISSUE THREAD

**Issue by JanEggers** [Microsoft/ApplicationInsights-Home#139]
i have a unittest that tries to create all services in my service collection.

while populating the service collection i call 

`services.AddApplicationInsightsTelemetry( configuration );`

in 2.1.0 i could create all services application insights adds

in 2.1.1 i get 

System.InvalidOperationException : failed to create Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet

System.InvalidOperationException : Unable to resolve service for type 'System.Text.Encodings.Web.JavaScriptEncoder' while attempting to activate 'Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet'.

am i supposed to call another add stuff method or should this type be registered in AddApplicationInsightsTelemetry

**Comment by SergeyKanzhelev** [comment]
Moved to aspnetcore repo
