### ISSUE TITLE
Error in sample: time ticks mismatch

### ISSUE THREAD

**Issue by SergKanz** [Microsoft/ApplicationInsights-Home#14]
Hey, @SoubhagyaDash, it seem you have an error in this code:
https://github.com/Microsoft/ApplicationInsights-Home/blob/master/Samples/AzureEmailService/WorkerRoleA/WorkerRoleA.cs#L96

Ticks of stopwatch doesn't equal ticks of TimeSpan. Please use StopWatch.Elapsed instead.

**Comment by SoubhagyaDash** [comment]
Fixed with https://github.com/Microsoft/ApplicationInsights-Home/commit/99d90de19a893ed00648b17e4f2a3d88fa351b14
