### ISSUE TITLE
CPU/Disk Usage per API

### ISSUE THREAD

**Issue by saxenark** [Microsoft/ApplicationInsights-Home#150]
Hi, 

I would like to know if AppInsights out of the box has supported for providing CPU/Disk performance counters per request of my web application hosted on IIS / IAAS environment

Thanks,
Anubhav.

**Comment by SergeyKanzhelev** [comment]
It depends on your scenario. If you looking for profiling a specific request - enable [Application Insights Profiler](https://docs.microsoft.com/azure/application-insights/app-insights-profiler).

If you looking for aggregated value for specific REST calls group - closest you can do is to correlate an overall CPU and disk with this page on Performance tab

![image](https://user-images.githubusercontent.com/9950081/28933130-e721bf28-7830-11e7-9bed-dd48ce68d556.png)

If you need more than those two - ask for a your scenario support at [User Voice](http://aka.ms/aiuservoice) or [in the .NET specific repo](https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues).

**Comment by saxenark** [comment]
Hi,

Thanks. 

I notice the following documentation

Limits
The default data retention is 5 days. Maximum 10 GB ingested per day.
There is no charge for the profiler service. Your web app must be hosted in at least the Basic tier of App Services.

a. Is this for all kinds of supported apps including IIS websites?
b. Can this be customized to store perf counters data for more number of days?

Also, I see that the CPU chart for the REST call group has data for just 5 minutes approx. 

![image](https://user-images.githubusercontent.com/2850526/28952710-916cf23a-78f0-11e7-9bb3-38fdfab4c8c6.png)

c) Can this duration that is visible on the widget be customized to show different times?
d) Is the CPU / perf counters data programmatically accessible using the Analytics / scripting?

Thanks,
Anubhav.

**Comment by SergeyKanzhelev** [comment]
@qubitron can you answer those questions please?

**Comment by SergeyKanzhelev** [comment]
>There is no charge for the profiler service. Your web app must be hosted in at least the Basic tier of App Services.
>a. Is this for all kinds of supported apps including IIS websites?

Yes, billing is independent of application type and platform

> b. Can this be customized to store perf counters data for more number of days?

No. Vote here: https://feedback.azure.com/forums/357324-application-insights/suggestions/17454031-longer-data-retention

> c) Can this duration that is visible on the widget be customized to show different times?

CPU counters sent once every minute. This is not customizable. See https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/142

> d) Is the CPU / perf counters data programmatically accessible using the Analytics / scripting?

Yes. in `performancecounters` table
