### ISSUE TITLE
Publish PDBs in NuGet packages

### ISSUE THREAD

**Issue by ohadschn** [Microsoft/ApplicationInsights-Home#152]
Including the PDBs even (especially?) with release builds can be extremely helpful for debugging. 
This is true for all AI-related assemblies (including packages for other platforms such as ASP.NET Core).
It seems like there is a dedicated NuGet package type (_Symbol Package_) for these type of things, so if that works, even better: https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages#publishing-a-symbol-package.

DotPeek has an [amazing PDB generation feature](http://confluence.jetbrains.com/display/NETCOM/dotPeek+Symbol+Server+and+PDB+Generation?pageVersion=11) that can be used in the meantime, but it's not quite the same as having the real thing.

**Comment by SergeyKanzhelev** [comment]
Symbols should be available on MS symbol server already. @cijothomas was working recently on making sure they are. 

@cijothomas can you please confirm asp.net core symbols available?

**Comment by ohadschn** [comment]
Looks like the PDB is there, I was able to download it using this handy tool: https://github.com/rajkumar-rangaraj/PDB-Downloader.

However, I can't seem to be able to use it to set a function breakpoint. For example, I tried setting a breakpoint for `Microsoft.ApplicationInsights.dll!Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.get_Active()` and it wasn't triggered. When I used the dotPeek-generated PDB instead it worked (even allowing me to step through the reverse-engineered code).

**Comment by SergeyKanzhelev** [comment]
I'm sorry, got distracted and haven't seen this response. 

Can it be because we are using [gitlink](https://github.com/GitTools/GitLink)? Do you try to set a breakpoint in cloned repo? Did you enable source server?

**Comment by ohadschn** [comment]
I enabled source server and .NET source stepping and I can now set. However I don't get the source ("Source not available", I can only see the assembler code), even when I disable "require source files to exactly match the original version".

What do you mean by setting a breakpoint in a cloned repo? If you mean clone the AI repo, run some test or something and set a breakpoint somewhere I'm pretty sure that would work (I have breakpoints generally working, even in this case with the dotPeek PDB), but I could try if you think it's worthwhile.

**Comment by SergeyKanzhelev** [comment]
OK. Created a bug to investigate. Closing this issue in home repo, thanks for reporting
