### ISSUE TITLE
[Feedback on format] Path based ids: hard when you have the “10000” span problem

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-Home#155]
Path based ids: hard when you have the “10000” span problem, the path based ids will get too long, @adriancole was suggesting we consider using extra metadata field for this

**Comment by jacpull** [comment]
I did not full get this concern. A vector spanning 10000 spans can be single stage. Was the reference to a 10000 depth?

**Comment by adriancole** [comment]
you are right that the concern is more about depth than total count of
spans. Basically, this will have a hard break at a particular depth (if
nothing else http limitations). That depth should be documented and kept in
mind when choosing encoding (or alternative means to encode). For example,
this is an issue when users do "profiler like" tracing where there is a
high depth of spans in a trace. TL;DR; trying to smoke out an assumption
that there's a fixed amount of spans per hop, which is actually an
implementation decision.
