### ISSUE TITLE
[Feedback on format] Base64 vs. Base16

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-Home#157]
Base64 vs. Base16
- @bogdandrutu has found that for small strings base16 is faster than base64
- For small strings base16 nicely fits into cache lines gives you memory advantage that allows you to be faster
- @adriancole has found a lot of people preferred using hex for scenarios where you are copy/pasting logs, and there is significant community momentum behind this
- printing `long` value as hex is much easier than as base64 to correlate trace id with the text log

**Comment by jacpull** [comment]
For the Vector/Path, a switch from Base10 to Base16 is acceptable. There is no difference on the sort. 

However, a switch from Base10 to Base64 is problematic w.r.t. backwards compatibility with Base10 formats. If the  cV/request Id is passed across services that are cV 2.0 compliant and cV vNext compliant, sort across components would need to take into account the version, which is not explicit. 

For the Base/Trace-Id, the overhead of 10 bytes is painful from Base64 to Base16.

**Comment by adriancole** [comment]
>
>
>    - printing long value as hex is much easier than as base64 to
>    correlate trace id with the text log
>
> long value used to be used in zipkin but has a couple limitations. It
can't have parity in json due to json's numeric field limitations. Also, it
leaves open whether to print as a number, which not only introduces endian,
but also sign concerns. For example, the sign concern was a primary factor
in the choice to switch from numeric to lowerhex encoding in zipkin.

>
