### ISSUE TITLE
Export Azure SQL telemetry data to application insight or kusto

### ISSUE THREAD

**Issue by GuofuZhong** [Microsoft/ApplicationInsights-Home#161]
we want to build some monitor and alert rules which are based on Azure SQL Database Query Performance Insight.
But I don't know how to implement it. 
From document I'm not find the way to send metric to application insight or kusto

**Comment by cijothomas** [comment]
Application Map UI pulls information from Azure SQL Performance Insights and shows in the UI. But this data is simply pulled from Azure SQL itself, not from application insights. (the data is not send to application insights at all, so no kusto query)

**Comment by GuofuZhong** [comment]
Hi @cijothomas Could you share more context for us? How to pull it to SQL DB？

**Comment by cijothomas** [comment]
Not clear on your question. Can you clarify a bit more? Are you asking about how to pull application insights data into SQL DB? If yes this links explains export in general..https://docs.microsoft.com/en-us/azure/application-insights/app-insights-export-telemetry

Or, are you asking about how to get data from SQL Insights into Application Insights - for this, there aren't any official sdks. But you can send pretty much everything to Application Insights using current SDK. 
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-custom-events-metrics

**Comment by GuofuZhong** [comment]
@cijothomas Thank you! I know how to do in application insights side. I want to export sql insights data to application insights.. I checked the document,But I'm not find how to export azure sql query performance insights data...

**Comment by SergeyKanzhelev** [comment]
I think this is the solution: https://docs.microsoft.com/azure/sql-database/sql-database-metrics-diag-logging

Please re-open issue if you need other logs or have more questions
