### ISSUE TITLE
Profiler not detected / running

### ISSUE THREAD

**Issue by onlyann** [Microsoft/ApplicationInsights-Home#163]
I have a .NET Framework 4.6.1 web application that is using version 2.4.0 of the SDK and is hosted as as an Azure App Service.

From the associated Application Insights instance, I enabled the profiler and it installed the extension. After a minute or so, the portal displays that the profiler is running.

I run a couple of requests against the web application but going to the Performance keeps displaying prompts that I need to enable profiler traces
![image](https://user-images.githubusercontent.com/1916218/30466883-3ed27798-9a24-11e7-8298-dde7cd6ef72c.png)

The configure pane sometimes shows the profile agent is running but often that it failed to check status
![image](https://user-images.githubusercontent.com/1916218/30466967-bfa1f4b6-9a24-11e7-85d0-5e356d3bbc45.png)

There is a continuous webjob in a running status. Available logs are:
```
[09/15/2017 03:53:45 > 35a450: SYS INFO] Status changed to Starting
[09/15/2017 03:53:45 > 35a450: SYS INFO] WebJob singleton setting is False
[09/15/2017 03:53:46 > 35a450: SYS INFO] Run script 'ApplicationInsightsProfiler.exe' with script host - 'WindowsScriptHost'
[09/15/2017 03:53:46 > 35a450: SYS INFO] Status changed to Running
[09/15/2017 03:53:46 > 35a450: INFO] Unpacking resources...
[09/15/2017 03:53:46 > 35a450: INFO] Executing Application Insights Profiler agent version 2.4.50410.1 with arguments: 
[09/15/2017 03:53:46 > 35a450: INFO] Welcome to Application Insights Profiler - to exit the program press 'Ctrl+C'.
[09/15/2017 03:53:46 > 35a450: INFO] Detected an Azure App Service sandbox.
[09/15/2017 03:53:46 > 35a450: INFO] Data cube: 9dd7e8ba-147c-4fc6-8a6f-203c52e51fdf
[09/15/2017 03:53:46 > 35a450: INFO] Collection endPoint: https://agent.azureserviceprofiler.net
[09/15/2017 03:53:47 > 35a450: INFO] Initializing agent...
[09/15/2017 03:53:47 > 35a450: INFO] Set up shutdown handler.
[09/15/2017 03:53:47 > 35a450: INFO] Shutdown handler set to watch D:\local\Temp\JobsShutdown\continuous\ApplicationInsightsProfiler2\fkxgjgu5.2gr.
[09/15/2017 03:53:49 > 35a450: INFO] Profiling is currently disabled.
[09/15/2017 03:53:49 > 35a450: INFO] Agent started to stand by.
```

**Comment by northtyphoon** [comment]
As the log shows, the agent was in stand-by mode as the profiler was disabled. If you click "Enable Profiler" button on the configure pane, the agent will start to profile.

**Comment by onlyann** [comment]
@northtyphoon I forgot to mention that clicking on the "Enable profiler" button results in *Failed to update Profiler enable status*
![image](https://user-images.githubusercontent.com/1916218/30507777-7d8f8932-9acc-11e7-9c46-68604392ae26.png)

**Comment by northtyphoon** [comment]
@onlyann Do you have the owner, contributor or application insights component contributor role?

**Comment by onlyann** [comment]
@northtyphoon I was going to say yes given I created the Application Insights resource but looking at the *Access Control* tab, I can see that I am in none of the roles you mentioned. I'll get added to *Application Insights component contributor* role then and will post the result. Thanks.

**Comment by northtyphoon** [comment]
@onlyann May I ask what role you had when you checked _Acess Control_ tab? Did you have any role listed in (https://docs.microsoft.com/en-us/azure/active-directory/role-based-access-built-in-roles)?

**Comment by onlyann** [comment]
@northtyphoon 

> Did you have any role listed in (https://docs.microsoft.com/en-us/azure/active-directory/role-based-access-built-in-roles)?

Not specifically a role but when I look at the permissions of `Application Insights Component Contributor`, I have all of them.

I have been assigned a non-built-in role with the following permissions:
Microsoft API Management | All
Microsoft Authorization | Partial (Read)
Microsoft Automation | All
Microsoft Azure EventHub | All
Microsoft Azure Notification Hub | All
Microsoft Azure ServiceBus | All
Microsoft Azure Stream Analytics | All
Microsoft Batch | All
Microsoft Cache | Partial
Microsoft Certificates | All
Microsoft Compute | All
Microsoft Data Catalog | All
Microsoft Data Factory | All
Microsoft DataLakeAnalytics | All
Microsoft DataLakeStore | All
Microsoft DevTest Labs | All
Microsoft DocumentDb | All
Microsoft Domains | Partial (Read)
Microsoft Feature | Partial
Microsoft Key Vault | All
Microsoft Logic | All
Microsoft Marketplace Ordering | All
Microsoft Monitoring Insights | All
Microsoft Network | Partial
Microsoft Operational Insights | All
Microsoft Recovery Services | All
Microsoft ResourceHealth | All
Microsoft Resources | Partial
Microsoft Scheduler | All
Microsoft Search | All
Microsoft SQL Database | Partial
Microsoft Storage | All
Microsoft Support | All
Microsoft Web Apps | All
Microsoft.Cdn | All
Microsoft.ContentModerator | All
Microsoft.HDInsight | All
Microsoft.Media | All

**Comment by northtyphoon** [comment]
@onlyann Thank you very much. The above information is very helpful. I think I know what's wrong. We will push a hotfix to address the issue. Will update you later.

**Comment by northtyphoon** [comment]
@onlyann please try it again and let me know if you can enable the profiler

**Comment by onlyann** [comment]
Thank you @northtyphoon, it works now. What was the issue?

**Comment by northtyphoon** [comment]
@onlyann it's due to a bug of validating the permission defined in the custom role. Thanks again for reporting the issue. By the way, if you have any question or suggestion, you can also send the email to serviceprofilerhelp@microsoft.com.

**Comment by larserikfinholt** [comment]
I got this issue: Failed to get Profiler enable status. The for each linked app I get a warning "Profiler is disabled." Each app got an right clik option of reinstalling the profiler, but still no luck.

What was the sln?

**Comment by SergeyKanzhelev** [comment]
@larserikfinholt - reopening to bring the issue to attention. @northtyphoon can you help?

**Comment by juliusl** [comment]
Hi @larserikfinholt - 

So for the first issue this could be an intermittent issue coming from the app insights resource provider, but I would like to dive in more. Could you please send me an email to serviceprofilerhelp@microsoft.com with your instrumentation key so I can look at telemetry on our side. For some context you require write permissions on the AI resource in order to disable or enable the profiler. 

For the second issue, could you take a look at the webjobs for your site to see if the profiler web job is running. If not you can enable it there. Also, to reinstall the profiler we actually reinstall the site extension. The site extension currently has an issue where a file could be in use which will block the update here is some documentation on that: https://docs.microsoft.com/en-us/visualstudio/debugger/debug-live-azure-apps-troubleshooting#site-extension-upgrade.

**Comment by joergjo** [comment]
I'm facing the same issue. I've tried this with App Services and Compute for ASP.NET and ASP.NET Core in West Europe, North Europe, and East US. I even managed to enable profiler for a Web App after stopping it, but later I saw that it had reverted itself to the disabled state. I've sent more details to [serviceprofilerhelp@microsoft.com](mailto:serviceprofilerhelp@microsoft.com).

**Comment by darrenferguson** [comment]
Hello, the email above is no longer valid - and I am receiving the same issue - I have the permission detailed above and have checked the webjob is running.

Can anyone assist?

![image](https://user-images.githubusercontent.com/2164132/35885761-d34cb630-0b86-11e8-9a7e-57c2a9edb700.png)

**Comment by pharring** [comment]
We're looking into it.
@darrenferguson two things:
1. The serviceprofilerhelp@microsoft.com alias was working this morning. We've been helping @joergjo on that alias. How do you know it's not valid? Did you get an undeliverable message?
2. Are you using Chrome? If so, can you try a different browser (Edge or IE)? That appears to be the common cause with other users hitting this problem.

**Comment by darrenferguson** [comment]
I've logged in this morning using IE and the profiler is enabled.... I didn't do anything additional.

Regarding the email address, I just got a message undelivered response.

I now have dependencies in the performance profiler but no "operations"....

**Comment by bayfall** [comment]
Same issue here "Failed to update Profiler enable status", despite the fact the Profiler Agent Status reports that all is fine. 
![insights](https://user-images.githubusercontent.com/1055626/35982311-675463bc-0ce7-11e8-9fce-9a786e30ab1b.png)

**Comment by juliusl** [comment]
@darrenferguson @bayfall We think we have a mitigation. Do you mind seeing if you still see the issue in the portal? Any browser is fine.

**Comment by juliusl** [comment]
+ @larserikfinholt
