### ISSUE TITLE
Application Insights Performance Counters + Service Fabric

### ISSUE THREAD

**Issue by Eneuman** [Microsoft/ApplicationInsights-Home#166]
We have a project containing 12 Service Fabric applications and 40 services running on 5 servers.
Using the default setup for Application Insights results in 200 services sending the same performance telemetry, like server CPU and server avail mem, to AI witch uses up all of our AI storage.
All services are using .Net Core 2.

We need to reduce the amount of performance data that gets transmitted to AI, but all exceptions (with stacktraces) and requests must be send.

Can this be done and in that case; what is the recommended way of handeling this?

We would like to see the following performance data in AI:
* CPU load of each server
* CPU load of each service
* Avail mem of each server
* Used mem for each service

**Comment by darivuki** [comment]
I would be interested in this as well.

**Comment by SergeyKanzhelev** [comment]
Version [2.2.0-beta3](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/61df2b6170396383c44dd732ea493f8e45c87c2f/CHANGELOG.md#version-220-beta3) of Performance Collector module introduced the `DefaultCounters` property that can be cleared out to get rid of automatic collection of un-needed counters.

>New property DefaultCounters in PerformanceCollectorModule to control the list of standard counters that will be collected

Closing this issue and I'll create another one in ServiceFabric repo
