### ISSUE TITLE
Application Insights Performance Counters support .net core

### ISSUE THREAD

**Issue by andreymir** [Microsoft/ApplicationInsights-Home#168]
Please, add support of collecting performance counters from .net core asp.net applications. We use Application Insights to monitor our web applications and in the Azure portal all charts with server metrics like CPU or memory usage are empty.
![image](https://user-images.githubusercontent.com/226866/32250034-04c9f6d8-be9c-11e7-845d-1726d57bea7e.png)

**Comment by cijothomas** [comment]
Duplicate: https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/470
.net core does not have an api to read perf counters. perf counters are collected if targetting full .net framework.

Will update on the original issue, if and when we plan to support this feature.

**Comment by andreymir** [comment]
Thanks! This should be documented in the article [System performance counters in Application Insights](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-performance-counters). There are no information in this guide that it is only for full .Net framework.

**Comment by cijothomas** [comment]
Thanks for reporting. Will update the documentation.
https://github.com/MicrosoftDocs/azure-docs/pull/3678/files

**Comment by SergeyKanzhelev** [comment]
Closing as we have a corresponding issue in proper repository
