### ISSUE TITLE
Compatibility with Google Analytics

### ISSUE THREAD

**Issue by ohadschn** [Microsoft/ApplicationInsights-Home#170]
I want to use Application Insights exclusively but the extremely annoying 0.0323 GB daily data cap prevents me from doing so (I have no intention of removing my account's spending limit).

How well does Application Insights play along with Google Analytics (whose 10M hits/month is well above my needs)? Are they stepping on each other's toes by registering to the same global handlers etc.?

**Comment by KamilSzostak** [comment]
Application Insights is more developer oriented. It collects performance metrics, exceptions, etc. which aren't collected by Google Analytics. 
On the other hand, Google Analytics collects a lot of usage metrics, which you can combine with your ad campaign, acquisition (e.g. Google's search queries which lead people to your page) or ad sense revenue.  All of that can be achieved in JavaScript SDK, but you will need to write some custom code to collect additional data. 

Personally, I think these tools serve a slightly different need. AppInsights is perfect for monitoring the health of your app, for instance: server and client side performance, exceptions with stack traces, live metrics, app map which shows a topology of your app (client, server, DB, etc.). 
Google Analytics provides more marketing, acquisition, and audience related metrics.

**Comment by ohadschn** [comment]
Thank you for the explanation, but that just makes my question even more interesting!
If they serve different goals, then it makes sense to have them side by side, which raises the question - is this a supported scenario that should work well?

**Comment by KamilSzostak** [comment]
Yes, I've seen customers using both AppInsights and Google Analytics on their websites. The JS SDK should work fine with any telemetry collection library. 
The JS SDK is monitoring all dependency calls, so if another library is using ajax to transmit telemetry you may even get some insights into how long does it take and what's a success rate :)

**Comment by ohadschn** [comment]
Nice, thanks for verifying :)
