### ISSUE TITLE
Unable to find assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.2.0

### ISSUE THREAD

**Issue by ligcire** [Microsoft/ApplicationInsights-Home#171]
Hi,

we are getting the following exception after we switch on appinsight on our web app, any idea what went wrong?

Unable to find assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

we have System.Diagnostics.DiagnosticSource 4.4.0 installed using nuget

Running AppInsight 2.4.0

**Comment by lmolkova** [comment]
Please check https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/613 - it's a known issue and there are few workarounds for it mentioned there.

**Comment by SergeyKanzhelev** [comment]
See https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/613 for details and workaround. Please re-open that issue if it still reproes for you. I'm closing this issue.

**Comment by SergeyKanzhelev** [comment]
=) @lmolkova - I wonder how many seconds before me you posted your reply

**Comment by SergeyKanzhelev** [comment]
ok. beat me 4 seconds!

**Comment by ewahner** [comment]
None of these workarounds work for me.  I have installed the latest pre-release of 4.4.1 and this is still a problem.  Do you have a solution for Azure hosted sites?

**Comment by lmolkova** [comment]
@ewahner the latest stable 4.4.1 does not have a fix, you would need 4.5.1 preview for it from dotnet myget feed, details how to obtain it are in the https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/613. It should work on Azure hosted sites.

**Comment by ewahner** [comment]
Still getting this error after adding the new version from the myget feed: Could not load file or assembly 'System.Diagnostics.DiagnosticSource' or one of its dependencies.

**Comment by lmolkova** [comment]
@ewahner could you please share the stack trace?

Also, could you repro it locally on your machine? would you be able to create a repro app?

**Comment by ewahner** [comment]
@lmolkova apparently one of my webjobs was causing the NuGet restore step to overwrite the version of the package.  Got that resolved and it does seem to work now.  Thanks.

**Comment by lmolkova** [comment]
@ewahner thanks for the update, good to know it works for you!

**Comment by jdemeuse1204** [comment]
I just had this same error with App Insights version 2.7.2.  I rolled back to version 2.3.0 which does not have a dependency on System.Diagnostics.DiagnosticSource.  Everything works just fine now with version 2.3.0

**Comment by SergeyKanzhelev** [comment]
@jdemeuse1204 I'd suggest to figure out this binding redirect issue. Most probably `web.config` was updated incorrectly or something. Many good feature in last versions of SDK =)

**Comment by trymtodalshaug** [comment]
This fixed the problem for me `Update-Package -Id System.Diagnostics.DiagnosticSource -Reinstall`

**Comment by Cudack** [comment]
> This fixed the problem for me `Update-Package -Id System.Diagnostics.DiagnosticSource -Reinstall`.
> 
> Doing the same through the package manager UI did not work for some reason.

Didn't help me :( Today I was updating couple Nuget packages and it happend after the update.

In my solution after the update I have below (in app.config files):
```
      <dependentAssembly>
        <assemblyIdentity name="System.Buffers" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0" />
      </dependentAssembly>
<dependentAssembly>
        <assemblyIdentity name="System.Diagnostics.DiagnosticSource" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.3.1" newVersion="4.0.3.1" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Memory" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.1.1" newVersion="4.0.1.1" />
      </dependentAssembly>
```
All of this assemblies have the same publicKeyToken. I've even tried to increase the oldVersion section in each assembly and still nothing. After I install my WPF application it's not working but it works right from Visual Studio (debug and release version).
Installing the prerelease version also didn't help.

The error I have:
```
Message: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The localized set manifest definition does not match the reference to the set.
Source: Microsoft.EntityFrameworkCore

StackTrace:    w Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.TryAddCoreServices()
   w Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.ApplyServices(IDbContextOptions options, ServiceCollection services)
   w Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c__DisplayClass4_0.<GetOrAdd>b__2(Int64 k)
   w System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   w Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)
   w Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
   w Microsoft.EntityFrameworkCore.DbContext..ctor()
   w System.Windows.Application.<.ctor>b__1_0(Object unused)
   w System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   w System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

TargetSite: Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder TryAddCoreServices()

Data: System.Collections.ListDictionaryInternal
```

Next step I would try is to install prerelease version of EF Core is there any.

**Comment by yildizmy** [comment]
Installing **System.Diagnostics.DiagnosticSource** on Nuget Package Manager fixed the problem for me.

**Comment by bpadhiyar4** [comment]
> Even though the package version of the System.Diagnostics.DiagnosticSource installed is the latest one e.g. 4.5.0 but the assembly version of the DLL is just 4.0.3. So adding binding redirect to your web.config may solve the problem.
> 
> `<dependentAssembly> <assemblyIdentity name="System.Diagnostics.DiagnosticSource" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral"/> <bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0"/> </dependentAssembly>`

How to do binding redirect in .Net Core
