### ISSUE TITLE
Installing on precompiled .NET App: Could not load file or assembly 'App_GlobalResources' or one of its dependencies

### ISSUE THREAD

**Issue by evertonmc** [Microsoft/ApplicationInsights-Home#172]
I get this error after installing AI Extension on Azure WebApps
Could not load file or assembly 'App_GlobalResources' or one of its dependencies. The system cannot find the file specified...

PS: My app is precompiled and has therefore no App_GlobalResources folde

**Comment by SergeyKanzhelev** [comment]
@aarongas please take a look at this issue with the Azure Web Apps extension

**Comment by clguimanMSFT** [comment]
@evertonmc Are you getting the same error if you add the AI SDK to your Visual Studio project?

**Comment by evertonmc** [comment]
I haven't tested it this way. I'm trying to run a non-invasive installation, without the need to rebuild...

**Comment by clguimanMSFT** [comment]
I meant a local test, you don't need to release your code.
Could you go to your Kudu console and get a diagnostic dump (Tools->Diagnostic dump)? Please send that file to clguiman@microsoft.com

**Comment by SergeyKanzhelev** [comment]
@clguimanMSFT is it fixed now? Can I close the issue?

**Comment by clguimanMSFT** [comment]
I've talked with @evertonmc offline and I was waiting for him to perform some debug actions. He hasn't replied in a while. 
I think you can close the issue if @evertonmc is ok with it.

**Comment by SergeyKanzhelev** [comment]
Closing for now than
