### ISSUE TITLE
Multiple role application map, dependencies not connected to the role

### ISSUE THREAD

**Issue by SvenVanHauwe** [Microsoft/ApplicationInsights-Home#173]
I have a solution with 2 aspnet core 2.0 web apps. A website and a web api. Configured them both to fill the Cloud.RoleName property. Both show up as seperate entities on the mult role application map.

The dependencies however are connected to a rectangle with the name of the application insights resource I used when I added application insights as a connected service.

Is there a way to set the RoleName context property on dependencies?

**Comment by SergeyKanzhelev** [comment]
See http://apmtips.com/blog/2017/10/18/two-types-of-correlation/ for details.

CC: @cijothomas on how to set role name on asp.net core.

**Comment by SvenVanHauwe** [comment]
@SergeyKanzhelev Thanks for the information.
In the multi role example in the blog post, the dependency starts from one of the components. In my case it does not.
![multi role application map](https://user-images.githubusercontent.com/18161108/33756998-773e443e-dbf8-11e7-9f22-139aee309869.PNG)

When I open the dependency data the property cloud_Roleinstance is filled, cloud_RoleName is not present.

**Comment by SergeyKanzhelev** [comment]
@SvenVanHauwe you'd need to set the RoleName from code than. Just add a [telemetry initializer](https://docs.microsoft.com/azure/application-insights/app-insights-api-filtering-sampling#add-properties-itelemetryinitializer) that will set the RoleName for all telemetry.

**Comment by SvenVanHauwe** [comment]
That's exactly what I have done, changed the template's Program.main method to
            `var webhost = BuildWebHost(args);`
            `TelemetryConfiguration.Active.TelemetryInitializers.Add(
new MultipleComponentTelemetryInitializer("Fictional api"));`
 `webhost.Run();`

The MultipleComponentTelemetryInitializer class just sets the cloud_rolename to the constructor parameter. I am using the Microsoft.ApplicationInsights.AspNetCore version 2.2.0 beta 1 package.
As you can see in the output only Pageviews and Requests seem to have the property filled in.
![analytics cloud_rolename](https://user-images.githubusercontent.com/18161108/33820215-9e022038-de4e-11e7-9686-8a3bdb726bfc.PNG)

**Comment by SvenVanHauwe** [comment]
@SergeyKanzhelev thanks, that works
