### ISSUE TITLE
Finally block will not be called for exceptions ending an application - examples correction needed

### ISSUE THREAD

**Issue by RicardoNiepel** [Microsoft/ApplicationInsights-Home#174]
At
https://docs.microsoft.com/en-us/azure/application-insights/application-insights-custom-operations-tracking

Most of the samples having the same pattern
```
try
{
    // do
}
catch (Exception e)
{
    telemetryClient.TrackException(e);
    throw; // rethrow
}
finally
{
    telemetryClient.StopOperation(operation); // gets never called
}
```

The issue is, that StopOperation get's never called because of the rethrow.

You can try it on your own:

```
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                throw new Exception("");
            }
            catch (Exception)
            {
                throw;
            }
            finally
            {
                Console.WriteLine("Get's never executed");
            }
        }
    }
```

**Comment by SergeyKanzhelev** [comment]
CC: @lmolkova 

It seems that this is by design and you need to account for this case in your code.

@lmolkova - it worth mentioning on the doc page. Can you send PR with this note?

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/try-finally

>Usually, when an unhandled exception ends an application, whether or not the `finally` block is run is not important. However, if you have statements in a `finally` block that must be run even in that situation, one solution is to add a catch block to the try-finally statement.

**Comment by lmolkova** [comment]
I'll be working on this document anyway, so I will mention it there. 
I'm not sure it scales well though. There are plenty of other language-related corner cases that we cannot cover in each code sample.

**Comment by SergeyKanzhelev** [comment]
I think a simple Note or Warning on the page will suffice

Like this:
![image](https://user-images.githubusercontent.com/9950081/33780161-a93e74e8-dc04-11e7-8b5a-a2f7147055bf.png)

**Comment by lmolkova** [comment]
We do have `Warning: in some cases unhanded exception may prevent finally to be called so operations may not be tracked.` [here](https://docs.microsoft.com/en-us/azure/application-insights/application-insights-custom-operations-tracking#outgoing-dependencies-tracking)
