### ISSUE TITLE
Error when using SnapshotCollector

### ISSUE THREAD

**Issue by thiagodds** [Microsoft/ApplicationInsights-Home#176]
I'm trying use SnapshotCollector version 1.1.0 and I'm trying send the exception to AI with this code:

`var telemetryClient = new TelemetryClient();
 telemetryClient.TrackException(exception);`

But this code throw this exception:

![image](https://user-images.githubusercontent.com/2293088/33887047-9ac7ae92-df2f-11e7-889d-1f43175bf253.png)

How do I fix this problem?

Ps: The dll is in the error path, but when I try execute SnapshotHolder_x86.exe, the .exe throws a error saying "api-ms-win-core-path-l1-1-0.dll not found".

**Comment by SergeyKanzhelev** [comment]
@pharring is it something you can help with?

**Comment by pharring** [comment]
@thiagodds what operating system are you using? If it's Windows 7 (or older), then this is not supported. The latest beta release (1.1.1-beta2) has a check for the necessary APIs and will disable the snapshot collector if they're not present.

**Comment by SergeyKanzhelev** [comment]
@pharring is it expected that it will surface as User Unhandled exception? What effect does it make on app? Will it crash?

**Comment by pharring** [comment]
In my experience, the TypeInitializationException is caught inside the Snapshot Collector before reaching the user (It looks like that screenshot comes from the Visual Studio debugger). The app doesn't crash, but you don't get any snapshots.  At this point, the symptoms look the same as https://stackoverflow.com/questions/47578218

**Comment by SergeyKanzhelev** [comment]
@pharring thank you for confirming. @thiagodds let us know if this is not a case and you see an application crash

**Comment by thiagodds** [comment]
@SergeyKanzhelev My app crash in the first time when the code try use the AI, but if I send the request again, the app works and doesn't save the snapshot.

**Comment by pharring** [comment]
@thiagodds I'm sorry to report that the Snapshot Collector relies on APIs (PssCaptureSnapshot) that are not present in Windows 7. To use Snapshot Collector, you will need to upgrade to Windows 8.1 or above.

**Comment by SergeyKanzhelev** [comment]
@pharring is the first crash that @thiagodds mentioned expected?

**Comment by pharring** [comment]
Yes, I believe it is. Please upgrade to 1.1.1-beta2 and also, if possible, move to Windows 8.1 or above.

**Comment by thiagodds** [comment]
Thank you guys. I can't upgrade to windows 10 now.

**Comment by SergeyKanzhelev** [comment]
Closing
