### ISSUE TITLE
Application Insights temp folders do not inherit permissions

### ISSUE THREAD

**Issue by ojasp** [Microsoft/ApplicationInsights-Home#179]
Looks like the temp folders created under C:\Windows\TEMP\Microsoft\ApplicationInsights\ folder are not inheriting permissions from the parent folder. The owner is inherited from ApplicatonInsights folder, however the permissions are not. Permissions on these folders are:

![image](https://user-images.githubusercontent.com/15022394/34618311-56e0958c-f20c-11e7-9ab8-92127709e24d.png)

The funny thing is that I am a member of Administrators group however I wasn't allowed to view the folder unless I clicked on Allow permissions to that folder, in the screenshot below. Once I click on continue, I have to go back to Advanced permissions and click on Enable Inheritance.

![image](https://user-images.githubusercontent.com/15022394/34618358-825c2082-f20c-11e7-939d-fac17c4b487e.png)

Thanks!
Ojas

**Comment by SergeyKanzhelev** [comment]
Great observation! This is totally intentional and the fact you seeing this behavior means that everything works. The idea here is to not allow one application to read telemetry of another.

Does this behavior cause any troubles for you? You can always override the folder to store telemetry to and SDK will not attempt to set permissions.

**Comment by SergeyKanzhelev** [comment]
Please tell us about your experience. Reopen the issue if it causes troubles for you.

**Comment by ojasp** [comment]
Ok, that makes sense. The issue that I am running into is that the websites are running as application pool user however we do asp .net impersonation which runs as a different user(devuser that you see in the screenshot above). The folders are created with full permissions to devuser however AI wants app pool user to have full access to those folders. I set full permissions for app pool users to application insights folder and was hoping that permissions would propagate. Any other way to accomplish that?

**Comment by SergeyKanzhelev** [comment]
So you see SDK complaining that it cannot persist data from the impersonated code? How does this warning surface for you?

Workaround would be to set `StorageFolder` for [channel](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/c3da6cc3c70fbd646de8c76ccae872e207365efe/src/ServerTelemetryChannel/ServerTelemetryChannel.cs#L189) explicitly - example is [here](http://apmtips.com/blog/2016/01/31/telemetry-channels-update/).

**Comment by SergeyKanzhelev** [comment]
I marked issue as enhancement. Let me know what how the issue surfaced so it potentially be changed to bug =) Hopefully not though

**Comment by ojasp** [comment]
Looks like setting StorageFolder under TelemetryChannel did the trick. No more access denied errors. Thanks Sergey.

**Comment by SergeyKanzhelev** [comment]
@ojasp can you comment on how this issue surfaced? As warnings in the portal? Or you saw first chance exceptions in Visual Studio? This info will help to classify it - bug or enhancement.

**Comment by ojasp** [comment]
I saw the errors under Live Metrics Stream on Azure Portal. I got the following error, and then I started digging a little and ended up here:

> AI (Internal): Unauthorized access dequeuing file, folder not accessible: b44704bea2fdce87cffb834ef57c1e7cbf49f05a6879fccf5fae1e6114e94660. Exception: System.UnauthorizedAccessException: Access to the path 'C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\ApplicationInsights\b44704bea2fdce87cffb834ef57c1e7cbf49f05a6879fccf5fae1e6114e94660' is denied.
 at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
 at System.IO.FileSystemEnumerableIterator`1.CommonInit()
 at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
 at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
 at Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.Implementation.PlatformFolder.GetFiles()
 at Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.Implementation.TransmissionStorage.GetTransmissionFiles()
 at Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.Implementation.TransmissionStorage.LoadFilesOrderedByDateFromFolder()
 at Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.Implementation.TransmissionStorage.GetOldestTransmissionFileOrNull()
 at Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.Implementation.TransmissionStorage.Dequeue().

**Comment by SergeyKanzhelev** [comment]
Thank you! I opened an issue to track in appropriate repository

**Comment by marcusvnac** [comment]
Hey there. I am facing the same problem here. Even after having added the setting described in the [example referenced before](http://apmtips.com/blog/2016/01/31/telemetry-channels-update/), the problem still happens. Actually, I hadn't seen any use of the folder specified in this example. I am using version 2.9.1
