### ISSUE TITLE
Insights not tracking Crashes on Universal Windows App

### ISSUE THREAD

**Issue by megamingus** [Microsoft/ApplicationInsights-Home#18]
I Can't seem to track crashes on my Universal Windows app (Win 10 app).

![image](https://cloud.githubusercontent.com/assets/1580038/8468403/5e43ebe2-2042-11e5-9a88-da2ed01b0a32.png)

**Comment by DesaiDarshan** [comment]
What version of the SDK are you using?

**Comment by megamingus** [comment]
Version 1.0.0

**Comment by abaranch** [comment]
There were several discussions on msdn forum:
https://social.msdn.microsoft.com/Forums/en-US/5f265ae0-8dad-4f55-af8a-aa0b1f4d7cfd/unable-to-access-crash-data?forum=ApplicationInsights
https://social.msdn.microsoft.com/Forums/en-US/f92e512a-ebdf-4884-966f-633542b0dba6/i-am-not-getting-crash-data?forum=ApplicationInsights
https://social.msdn.microsoft.com/Forums/en-US/ae7f78e8-a4e7-4574-866c-1829294d8745/what-am-i-missing-for-ai-crash-reports-to-show-on-dashboard?forum=ApplicationInsights

Also UWP support was recently removed from Application Insights API repo so there will be no new development of this SDK for this platform. You should check HockeyApp SDK that is part of ApplicationInsights now.
