### ISSUE TITLE
"Exceptions" metric not available in Add Alerts blade

### ISSUE THREAD

**Issue by twschiller** [Microsoft/ApplicationInsights-Home#180]
The "Exceptions" metric, which tracks incidences of Track Exception events [1] is not available as a metric in the Add Alert blade for Application Insights.

We're working with the Python client library [2], and trying to figure out how to set up alerts for server exceptions.

[1] https://docs.microsoft.com/en-us/azure/application-insights/app-insights-performance-counters#aspnet-and-application-insights-counts
[2] https://github.com/Microsoft/ApplicationInsights-Python

**Comment by SergeyKanzhelev** [comment]
@vgorbenko can you please check why there is no Exception metric available?

**Comment by twschiller** [comment]
For reference, here are a couple responses from Azure support:
> We do filter out synthetic traffic for alert generation

On the exclusion of "Exceptions" from the Add Alerts blade:
> I did talk to one of the devs that owns the Alerts blade and he did say that it’s by design.

**Comment by SergeyKanzhelev** [comment]
@twschiller thank you for posting resolution and filing issues in corresponding repositories. Closing it here
