### ISSUE TITLE
Ingestion Payload Size needs increment and Exception Telemetry Datastructure need to be tight bounded

### ISSUE THREAD

**Issue by dhaval24** [microsoft/ApplicationInsights-Home#181]
Exceptions can sometimes be very deep especially in Java where there can be a long chain of Throwable and it's causes. This can lead to potential explosion of json payload.

Today our Ingestion endpoint has maximum capacity to ingest max payload of 2^16 characters, which is considerably small for deep exception telemetry.

Our ExceptionTelemetry Data Structure does not imply strict restriction policy on its size (i.e there is no defined size for individual StackTrace (https://github.com/Microsoft/ApplicationInsights-Home/blob/master/EndpointSpecs/Schemas/Bond/ExceptionDetails.bond) Therefore the StackTrace vector can pile up to huge one thus creating a payload which would be rejected eventually.

Our current truncation mechanism for exception is also not robust. Currently 10 exceptions from the whole chain are retained, but this does not solve the above mentioned problem.

A single exception can have the long enough StackTrace vector to pass the 2^16 payload limit. Dropping the exceptions is a major flaw for APM product and should be a priority.

Crux: There needs to be some limit on payload size for ingestion (but 2^16 characters can be really small with modern application scenarios). There needs to be a more robust way of truncating the exception telemetry in a sense that it still preserves the intent and does not break the user experience.

**Comment by SergeyKanzhelev** [comment]
Ok. Which new limits do you propose to add. I'm all for limiting everything - please suggest reasonable numbers

**Comment by dhaval24** [comment]
@SergeyKanzhelev this is a debatable question. Do you have any idea on the norm in industry for JVM languages? If not I will do some research around this to propose a number.

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
