### ISSUE TITLE
App Insights - Continuos Export

### ISSUE THREAD

**Issue by premchandpl** [Microsoft/ApplicationInsights-Home#182]
Hi

I am configuring continuous export in app insight. I have the data in app insights from 31 Jan 2018. But I configured continuous export on 12th Feb 2018. In the blob storage, I am able to see the data from 12th Feb 2018 and not from 31st Jan 2018.

How do we get data into blob storage from App Insights starting from 31st Jan 2018

-Premchand

**Comment by Dmitry-Matveev** [comment]
Continuous export feature starts forwarding data into the blob of your choice from the moment that feature is configured - it works off the current data stream and not retrospectively.
To export data from the past, you can use [Application Insights API](https://dev.applicationinsights.io/).
