### ISSUE TITLE
Azure Web Sites Extension sets AppInsights JS SDK across all Web Apps in App Service Plan

### ISSUE THREAD

**Issue by hrboyceiii** [microsoft/ApplicationInsights-Home#184]
Hello --- apologies if this is not the right forum...

I'm seeing an issue whereby, if I host multiple Web Apps in the same app service plan and install the extension (2.4.8 as of 21 Feb 2018), all web apps get the JS SDK from the first site that installs the extension.  Example:

- Provision Service Plan A
- Provision App Insights Component A1 (iKey 1234)
- Provision Web App 1 in Service Plan A
-- Add Azure Web Sites extension (adds JS SDK using iKey 1234)
- Provision App Insights Component A2 (iKey 5678)
- Provision Web App 2 in Service Plan B
-- Add Azure Web Sites extension (adds JS SDK using iKey 1234; should be 5678)

I believe this is caused by an over-aggressive appHost XDT that is applying a rewrite rule at the server level.  The impact for me is that I've added the JS SDK into my app so I'm seeing duplicate code in my application for client telemetry and sending page view events to 2 App Insights resources.

What is the best way to handle this? Is it a bug in the extension? I'd like to have the extension because of the addition of the profiler web jobs, etc. and, because we're running in an App Service Environment, we intend to run our non-production environment Web Apps (DEV/QA/UAT) in the same App Service Plan to help reduce costs.

I appreciate any advise/suggestions anyone can provide.  Thank you in advance!

**Comment by hrboyceiii** [comment]
Any thoughts on this? Is it possible to deploy a different version of the extension?

Thank you

**Comment by SergeyKanzhelev** [comment]
+ @iusafaro, @clguimanMSFT and @pharring to help with Azure Web App extension question

**Comment by hrboyceiii** [comment]
@clguimanMSFT the app setting is not present.  I need to get approval to send the dumps and web app name but once I do, I'll send you the email.  Thanks for the response.

**Comment by cijothomas** [comment]
For any apps, set APPINSIGHTS_JAVASCRIPT_ENABLED=false explicitly and there wont be any js snippet injection. Previously, this did not work for asp.net core. 
This fix is being rolled out to all Azure Web Apps instances.

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
