### ISSUE TITLE
Transition Azure Web App extension to nuget.org

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-Home#185]
See instructions: https://github.com/Azure/app-service-announcements/issues/87

CC: @clguimanMSFT @AlexKlim @pharring

**Comment by Mikhail-Pranovich** [comment]
this should be resolved now. The WebApp extension is published on nuget.org

**Comment by MS-TimothyMothra** [comment]
@Mikhail-Pranovich can you provide a link to the package?
What name is it published as?

**Comment by Mikhail-Pranovich** [comment]
https://www.nuget.org/packages/Microsoft.ApplicationInsights.AzureWebSites/
