### ISSUE TITLE
Allow to customize live metrics UI based on platform / app type

### ISSUE THREAD

**Issue by figuerres** [microsoft/ApplicationInsights-Home#186]
I am looking at using AI on an Angular 4/5/6 SPA.
the client js version i see is 1.xxx  in the portal the live stream view refers to installing the asp.net server package.
so is Live stream dependant on an IIS server ?
can a JS / SPA app get live stream ?

please create a document that lists what AI features can be used by which application types.

**Comment by zakimaksyutov** [comment]
@figuerres, good point about a list of features per type.

Answering your question about live stream. Currently the following languages are supported: Java, .NET Core, .NET Classic

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
