### ISSUE TITLE
Add isolated application support to dotNet Base

### ISSUE THREAD

**Issue by ScottColson** [Microsoft/ApplicationInsights-Home#191]
I frequently create plugins as dotNet extensions to the Microsoft Dynamics
CRM platform. These plugins generally run in isolation and don't have 
access to the host drive or Environment data. Therefore the plugins will
error out with a security exception when AI initializes.

I have developed work around to this issue that allows the calling app
to inject a custom platform via TelemetryConfiguration as part of the
TelemetryClient creation. 

However, to make this work I need to make the IPlatform interface and
the IDebugOutput interface public as well as add an alternate constructor
for TelemetryConfiguration. 

Is this something that would be beneficial to a larger user base?

**Comment by SergeyKanzhelev** [comment]
We fixed one of partial trust issue: https://github.com/Microsoft/ApplicationInsights-Home/issues/87 

It will be helpful if you can identify other problems. If you can make it in form of PR for the unit tests projects - it will be very helpful.

**Comment by ScottColson** [comment]
The plugins that I create for CRM use NET4.5.2 and need to run within a Microsoft.crm.sandbox.workerprocess. I know how to create unit tests and PRs but I don't know how to create a unit test that simulates what this process host allows and my searches have not yielded much. Do you have some recommended resources about simulating sandboxed services during unit test?  

I have identified the following additional areas where the existing AI SDK implementation is not compatible with the sandboxed host process:

Transmission.SendAsync() implementation for NET45 fails, but if I use the implementation that was put in place for NETSTANDARD1_3 then it works as expected. I presume the same will be true for NET46.

CallContextHelpers for NET45 are based on System.Runtime.Remoting and cause security exceptions. I don't have  a good alternate implementation, so for my current testing I have simply made all of the helpers inert. This will be a problem when running more threads.

There are also issues within the Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing classes that I still need to fully explore, but when things do wrong and the DebugTelementryModule is called upon to report the issue back to AI, my plugin fails with a security exception.

**Comment by SergeyKanzhelev** [comment]
Thank you for analysis. Ultimately you can load test assembly in separate AppDomain as a plugin. See [here](https://stackoverflow.com/questions/1357231/restrict-plugin-access-to-file-system-and-network-via-appdomain) for instance. Remoting namespace call you mentioned [requires](https://msdn.microsoft.com/en-us/library/system.runtime.remoting.messaging.callcontext.logicalgetdata%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) `SecurityPermissionFlag.Infrastructure`

**Comment by SergeyKanzhelev** [comment]
Moved to the proper repo.
