### ISSUE TITLE
Code simplified for ExceptionDetails and StackFrame

### ISSUE THREAD

**Issue by Savanete** [Microsoft/ApplicationInsights-Home#20]
Hi,
I think that ExceptionConverter and StackFrame could be unified in RT and PCL platforms with the others using the ExceptionDetails.ParsedStack property and making some implementation using regular expressions. The next approach doesn't give a correct result in the assembly name (returns the namespace) but we simplify the number of implementations for ExceptionDetails: 

        private static List<StackFrame> GenerateStackFrames(Exception exception, out bool fullStack)
        {
            fullStack = true;
            int length = 0;
            var frames = new List<StackFrame>();
            Regex regex = new Regex(@"at (?<namespace>.*\.)*((?<method>\w+\s\(.*\)).*) in (?<filename>.*)\:(?linenumber>\d+)\s*");
            string stackTrace = exception.StackTrace;
            if (!string.IsNullOrEmpty(stackTrace))
            {
                var stackFrames = stackTrace.Split(Environment.NewLine.ToCharArray());
                foreach (string stackFrame in stackFrames)
                {
                    if (length + stackFrame.Length > 32768)
                    {
                        fullStack = false;
                        break;
                    }
                        //readability
                    else
                    {
                        Match match = regex.Match(stackFrame);
                        if (match.Success)
                        {
                            var frame = new StackFrame
                            {
                                assembly = match.Groups["namespace"].Value,
                                method = match.Groups["method"].Value,
                                fileName = match.Groups["filename"].Value,
                                line = int.Parse(match.Groups["linenumber"].Value),
                                level = stackFrames.Length - frames.Count
                            };
                            frames.Add(frame);
                        }
                        length += stackFrame.Length;
                    }
                }
            }
            return frames;
        }

Regards!

**Comment by SergeyKanzhelev** [comment]
Can you please submit pull request to sign contribution agreement. It is a formality to make sure we can use the code you are suggesting to fix the mentioned issue. Also if you can give specific example of the issue - it will be great. If the name of assembly should contain whitespace or path?

**Comment by abaranch** [comment]
RT implementation was removed from Application Insights API repo
