### ISSUE TITLE
Status Monitor update button un-discovereable

### ISSUE THREAD

**Issue by SergeyKanzhelev** [microsoft/ApplicationInsights-Home#200]
Update of Status Monitor is important so latest SDK with many critical bug fixes will be used. However the update button is not discoverable:

![image](https://user-images.githubusercontent.com/9950081/38599880-00b1ac04-3d17-11e8-87ea-cba6992ffb5b.png)

![image](https://user-images.githubusercontent.com/9950081/38599882-036480ac-3d17-11e8-8de5-e3e1fb3cc195.png)

Without an update old version is used by Status Monitor:

![image](https://user-images.githubusercontent.com/9950081/38599888-08ce56c6-3d17-11e8-86ef-691362ae5920.png)

**Comment by seanksullivan** [comment]
Actually, we need a newer, official, core Application Insights release... probably: 2.5.1.
Does the status monitor tool code exist within GitHub?

**Comment by SergeyKanzhelev** [comment]
@seanksullivan this issue is about UI problem. Can you please create a separate one with the request to update the version of SDK? Thank you in advance

And - no, Status Monitor is closed source now

**Comment by MS-TimothyMothra** [comment]
Today I've released the Release Candidate for Status Monitor v2.
Because this is the replacement for the original Status Monitor, I'm going to close this issue.

Please review or documentation to get started: https://docs.microsoft.com/en-us/azure/azure-monitor/app/status-monitor-v2-overview
