### ISSUE TITLE
Wrong error message on timeout: No valid or unexpired Microsoft Azure subscriptions available

### ISSUE THREAD

**Issue by SergeyKanzhelev** [microsoft/ApplicationInsights-Home#201]
Status Monitor shows incorrect error message on timeout of reading the subscriptions

![image](https://user-images.githubusercontent.com/9950081/38600008-7129b7b0-3d17-11e8-9f7e-2cbf2f5f4a4d.png)

Long wait:

![image](https://user-images.githubusercontent.com/9950081/38600022-77372796-3d17-11e8-94af-728b2ca7d818.png)

**Comment by MS-TimothyMothra** [comment]
Today I've released the Release Candidate for Status Monitor v2.
Because this is the replacement for the original Status Monitor, I'm going to close this issue.

Please review or documentation to get started: https://docs.microsoft.com/en-us/azure/azure-monitor/app/status-monitor-v2-overview
