### ISSUE TITLE
Status Monitor do not allow valid ARM resource groups

### ISSUE THREAD

**Issue by SergeyKanzhelev** [microsoft/ApplicationInsights-Home#202]
Single letter names for resource groups are allowed by Azure, but not allowed by Status Monitor:

![image](https://user-images.githubusercontent.com/9950081/38600034-866d8fac-3d17-11e8-8760-a90962ddbb9f.png)

**Comment by MS-TimothyMothra** [comment]
Maybe this changed at some point in time.

I found the official requirements: [Naming Rules and Restrictions](https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions#naming-rules-and-restrictions)
`Resource Group Length 1-90`

StatusMonitor is currently using these rules:
```
internal class AzureHelpers
public static void ValidateResourceGroupName(string name)
{
            const int MaxLengthForResourceGroupName = 64;
            const int MinLengthForResourceGroupName = 2;
```

**Comment by MS-TimothyMothra** [comment]
Today I've released the Release Candidate for Status Monitor v2.
Because this is the replacement for the original Status Monitor, I'm going to close this issue.

Please review or documentation to get started: https://docs.microsoft.com/en-us/azure/azure-monitor/app/status-monitor-v2-overview
