### ISSUE TITLE
Need to change CONTRIBUTING.md to ask PR for develop, not master

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-Home#21]
In [CONTRIBUTING.md](https://github.com/Microsoft/ApplicationInsights-Home/blob/master/CONTRIBUTING.md) we ask for contribution into master, not develop. Need to change it.

**Comment by JoshuaWeber** [comment]
I agree with this, the repos are expecting development on the develop branch, not master. I think we also have a link to GitFlow explaining our reasoning for this design flow choice. Feel free to submit the pull request. :)

**Comment by lumaxis** [comment]
Should be fixed in #22 :)
