### ISSUE TITLE
Negative CPU values on Server Details

### ISSUE THREAD

**Issue by rstirling** [Microsoft/ApplicationInsights-Home#212]
Hi,

My application is presenting negative CPU values at Server>Server Details panel. This behavior is normal?
![image](https://user-images.githubusercontent.com/7254787/38936964-083962d0-42f0-11e8-8ef0-6c9ec3ae09dc.png)

**Comment by SergeyKanzhelev** [comment]
What language? Where an application was deployed?

**Comment by rstirling** [comment]
Hi @SergeyKanzhelev ,

The application is deployed on development machine. The default language is English. It's a Java application running on Tomcat Server using version 2.0.2 AI agent/libs.

**Comment by SergeyKanzhelev** [comment]
Thank you for details! I moved issue to correct repository so owners will take a look and reply to you.
