### ISSUE TITLE
What's the usage of Envelope.name property?

### ISSUE THREAD

**Issue by yantang-msft** [microsoft/ApplicationInsights-Home#219]
I'm wondering what's the usage of the [Envelope.name](https://github.com/Microsoft/ApplicationInsights-Home/blob/master/EndpointSpecs/Schemas/Bond/Envelope.bond#L15) property?
This is a required field, but it looks like I can put any strings and the telemetry is still processed correctly.
However, it feels like there is a longer latency before the telemetry can be queried, not sure if it's a misperception or not.

**Comment by SergeyKanzhelev** [comment]
`Envelope.name` is used as a type now. There are discussions to use it as `name` or remove it.

Any latency you may see is just a perception

**Comment by yantang-msft** [comment]
I believe the endpoint is actually using [Base.baseType](https://github.com/Microsoft/ApplicationInsights-Home/blob/master/EndpointSpecs/Schemas/Bond/Base.bond#L9) as the telemetry type.
That's why I'm asking this question, because I set a random value for Envelope.name and see no difference in the data.

I'm working on a log forwarding scenario and currently require the ```Envelope.name``` to be there to meet the schema. But if this value is not used at all, I can loose the requirement and put a random value if it's not there.

**Comment by SergeyKanzhelev** [comment]
I'd suggest to keep the name consistent with other SDKs. It is used by internal teams when they redirect telemetry to their backend systems.

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
