### ISSUE TITLE
Status Monitor needs to be updated to the latest Application Insights SDK

### ISSUE THREAD

**Issue by seanksullivan** [microsoft/ApplicationInsights-Home#220]
The Status Monitor needs to be updated to the latest Application Insights SDK.  As of 05/04/2018, the latest SDK 'release' version is 2.5.1.  This SDK version allegedly possesses the ability to track and correlate  dependencies that originated from async requests - of which is needed now more than ever.

The Status Monitor is currently using the Application Insights SDK version that was released in July 2017.

**Comment by SergeyKanzhelev** [comment]
@AlexKlimovMS can you please schedule this work? It is important to keep Status Monitor up to date with the latest SDK versions.

**Comment by MS-TimothyMothra** [comment]
Today I've released the Release Candidate for Status Monitor v2.
Please review or documentation to get started: https://docs.microsoft.com/en-us/azure/azure-monitor/app/status-monitor-v2-overview

This ships with SDK 2.9.
This is still not the latest version so I'm leaving this issue open for now.
