### ISSUE TITLE
Is there any way to know the size of the Telemetry payload, especially for Exceptions?

### ISSUE THREAD

**Issue by nikhilgirraj** [Microsoft/ApplicationInsights-Home#222]
I am trying to understand if we are sending a lot of information to our Application Insights instance. Maybe I am attaching some really long stacktraces for well known exceptions.

I already know that I can go an set daily quota quota for ingesting telemetry on the Azure portal. What I am interested in, is knowing if my code is adding too much information in the each packet of CustomEvent, Request or Exception telemetry.
Can this be done on the portal or log analytics? If not, is there a workaround or a plan for any such feature in the future?

**Comment by SergeyKanzhelev** [comment]
Do you mean programmatically from code? In this [msdn article](https://msdn.microsoft.com/en-us/magazine/mt808502.aspx) search for "Telemetry Processor for Item Size Calculation".

Please re-open this issue if it's not what you are looking for.

**Comment by nikhilgirraj** [comment]
Sergey, thanks for writing.
Although the idea of creating a Telemetry processor is useful, I am rather looking to measure the sizes of my existing, recieved telemetry on the application insights portal. Checking it from the code would be useful if I am still developing it, and the thing is that I want to find out if I need fix something it or not.

**Comment by SergeyKanzhelev** [comment]
So you need to know the size of individual item? You can use `strlen` function on individual field and than sum up sizes in Analytics. It may give you some estimated size. 

Something like: `requests | project itemId, size = strlen(id) + strlen(url) + strlen(source)  + ...`

You can run `requests | getschema ` to print out the list of fields in every table.

**Comment by nikhilgirraj** [comment]
That is a good idea. Do you think that the size that I get after summing up all the strlen'ed columns is the size that's considered while applying ingestion quota? Or is this just a very close estimate?

**Comment by SergeyKanzhelev** [comment]
@nikhilgirraj it is a close estimate. Actual size will include some JSON attributes like quotes and commas. Also date formatting for instance may differ.

**Comment by nikhilgirraj** [comment]
Thank you Sergey. This was very helpful.
