### ISSUE TITLE
4.6 Framework improvements

### ISSUE THREAD

**Issue by pgmorozov** [microsoft/ApplicationInsights-Home#225]
Hi,
What are the improvements made for 4.6 Framework AI version in comparison to the 4.5 version?
My customer considers moving to the 4.6 and wants to know what they will get from the monitoring point of view.
Thank you!

**Comment by pharring** [comment]
Is this question still relevant?

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
