### ISSUE TITLE
Can't enable exception collection in Visual Studio 17

### ISSUE THREAD

**Issue by florinciubotariu** [microsoft/ApplicationInsights-Home#226]
In Visual Studio 17, we can configure our Application Insights Configuration from the UI.
The third step is meant to Enable exception collection.

If you already have a AiHandleErrorAttribute file that is excluded from the project, you will never be able to successfully Enable Exception Collection.
Further more, this happens if you have an empty ErrorHandler folder.

In order to solve this, you have to manually delete the ErrorHandler folder, restart VS and after that, clicking Enable exception collection works.

I think it is a good idea to give more details about why we couldn't enable exception collection if possible.

**Comment by gardnerjr** [comment]
@SergeyKanzhelev which version is "the newest version" here?  what's the minimum version that can do this autoregistration, and what happens if it was already specified? (like someone upgrading from an older sdk to a newer one?)

**Comment by lmolkova** [comment]
@gardnerjr  the auto registration of unhanded exceptions was enabled in [the Web SDK 2.6.0-beta3](https://github.com/Microsoft/ApplicationInsights-dotnet-server/releases/tag/2.6.0-beta3)

Here is [ms docs article](https://github.com/lmolkova/azure-docs-pr/blob/9675bbb844b038206c6708c3ff5db7e67b4c4866/articles/application-insights/app-insights-asp-net-exceptions.md#mvc) about it.

If exceptions are tracked manually (via `AiHandleErrorAttribute` or in any other way), they will be tracked twice and manual collection via `AiHandleErrorAttribute` could be removed. 

Alternatively auto-injection could be disabled with `ExceptionTrackingTelemetryModule.EnableMvcAndWebApiExceptionAutoTracking` property set to `false` in ApplicationInsights.config or programmatically.

**Comment by gardnerjr** [comment]
so when we update VS to include final (non beta) versions of 2.6+, we should probably

1. remove the code we have to add exception filter/etc
2. add code to detect the double case and warn about it, possibly with an option to remove the code or disable auto tracking?

**Comment by lmolkova** [comment]
Yes, I think p1 is correct, this code should be removed. I'm not an expert in AI integration with VS, but I doubt p2 is feasible - users may change `AiHandleErrorAttribute` file\class name, modify it's content, etc... Also, it's likely nuget update scenario and AI wizards are not involved. 
If you see a good way to make p2 work - having warning would be awesome.

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
