### ISSUE TITLE
After updating v1.1 to v1.2: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by mschmeller** [Microsoft/ApplicationInsights-Home#23]
Hello,
after updating Application-Insights.Web from v1.1 to 1.2 we get the following error several times at runtime in our Azure cloud Service (others too http://stackoverflow.com/questions/31993394/application-insights):

[NullReferenceException]: Object reference not set to an instance of an object.
   at Microsoft.ApplicationInsights.TelemetryClient.Track(ITelemetry telemetry)
   at Microsoft.ApplicationInsights.TelemetryClient.TrackException(ExceptionTelemetry telemetry)
   at Microsoft.ApplicationInsights.TelemetryClient.TrackException(Exception exception, IDictionary`2 properties, IDictionary`2 metrics)
   at System.Web.Http.ExceptionHandling.ExceptionLogger.LogAsync(ExceptionLoggerContext context, CancellationToken cancellationToken)
   at System.Web.Http.ExceptionHandling.CompositeExceptionLogger.LogAsync(ExceptionLoggerContext context, CancellationToken cancellationToken)
   at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.WebHost.HttpControllerHandler.<ProcessRequestAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

How can we avoid this?

Best Regards
Martin Schmeller

**Comment by SergeyKanzhelev** [comment]
It looks like channel wasn't properly initialized. We made some changes in naming to work around ```MAX_PATH``` limitation when developing and testing cloud services. @abaranch mentioned it in my [blog](http://apmtips.com/blog/2015/08/29/web-sdk-1-2-1-structure-changes/). Please make sure that the correct channel is configured in ```ApplicationInsights.config```. More on channels [here](http://apmtips.com/blog/2015/09/03/more-telemetry-channels/). I created [issue](https://github.com/Microsoft/ApplicationInsights-dotnet/issues/45) to make error more informative

**Comment by mschmeller** [comment]
Hi Sergey,
thanks for your answer. In ApplicationInsights.config there is configured:
<TelemetryChannel Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.ServerTelemetryChannel, Microsoft.AI.ServerTelemetryChannel"/>

Microsoft.AI.ServerTelemetryChannel.dll was copied to the output folder therefore it should be in the azure cloud service publish package.
I have no idea what I was to see - what could be wrong with this channel?

**Comment by SergeyKanzhelev** [comment]
I'm sorry that it wasn't just configuration issue. Can you please check what version of ```ApplicationInsights.config``` do you have in ```bin``` folder of your project? Is it worker role or web role you are monitoring with Application Insights?

**Comment by mschmeller** [comment]
Hi Sergey,
in the Properties of the ApplicationInsights.config we have set "copy if newer" and in den bin-Folder there is the actual ApplicationInsights.config. We are monitoring a web role.
Running in AzureEmulator we tested
1)
var telemetryClient = new TelemetryClient();
telemetryClient.TrackException(new DivideByZeroException("This is just a Test."));
with the same NullReference-Exception
2)
var telemetryClient = new TelemetryClient(TelemetryConfiguration.Active);
telemetryClient.TrackException(new DivideByZeroException("This is just a Test."));
with the same NullNullReference-Exception
3)
var config = TelemetryConfiguration.CreateDefault();
var telemetryClient = new TelemetryClient(config);
telemetryClient.TrackException(new DivideByZeroException("This is just a Test."));
here we got the following exception with CreateDefault()
System.Reflection.TargetInvocationException was unhandled by user code
  HResult=-2146232828
  Message=Ein Aufrufziel hat einen Ausnahmefehler verursacht.
  Source=mscorlib
  StackTrace:
       bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
       bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
       bei System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
       bei System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
       bei Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryConfigurationFactory.LoadProperties(XElement instanceDefinition, Object instance)
       bei Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryConfigurationFactory.LoadInstance(XElement definition, Type expectedType, Object instance)
       bei Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryConfigurationFactory.LoadFromXml(TelemetryConfiguration configuration, XDocument xml)
       bei Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryConfigurationFactory.Initialize(TelemetryConfiguration configuration)
       bei Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.CreateDefault()
       bei x2.Cloud.Server.Host.WebApiApplication.Application_Start() in c:\TFS.Walluf\ixx.zwo\proj\dev\dev\src\Cloud\Server\Host\Global.asax.cs:Zeile 72.
  InnerException: System.ArgumentNullException
       HResult=-2147467261
       Message=Der Wert darf nicht NULL sein.
Parametername: value
       Source=Microsoft.ApplicationInsights
       ParamName=value
       StackTrace:
            bei Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.set_InstrumentationKey(String value)
       InnerException: 

Just to let you know, we did not specify the instrumentation key in the ApplicationInsights.config because we have three different deployment Environments. We specify the instrumentation key in the settings of each ServiceConfiguraton cscfg and set the Instrumentation key in the Global.asax.cs on the TelemetryConfiguration.Active.InstrumentationKey property.

Maybe this is no longer working with v1.2.0 ???

**Comment by SergeyKanzhelev** [comment]
I'm sorry for delayed reply. We are trying to repro this problem. Meanwhile I believe that symptoms you've described indicates that configuration loading was unsuccessful and it caused telemetry channel being not initialized.

I've created PR to make the error message more friendly when channel wasn't set in the next version: https://github.com/Microsoft/ApplicationInsights-dotnet/pull/51

Next, we definitely need to make configuration reading logic more robust and easier to troubleshoot.

This is a typical ```ApplicationInsights.config``` file you should get. Please compare names of types:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<ApplicationInsights xmlns="http://schemas.microsoft.com/ApplicationInsights/2013/Settings">
  <InstrumentationKey>Foo</InstrumentationKey>
  <TelemetryModules>
    <Add Type="Microsoft.ApplicationInsights.DependencyCollector.DependencyTrackingTelemetryModule, Microsoft.AI.DependencyCollector"/>
    <Add Type="Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.PerformanceCollectorModule, Microsoft.AI.PerfCounterCollector"/>
    <Add Type="Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule, Microsoft.ApplicationInsights"/>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.DeveloperModeWithDebuggerAttachedTelemetryModule, Microsoft.AI.WindowsServer"/>
    <Add Type="Microsoft.ApplicationInsights.Web.RequestTrackingTelemetryModule, Microsoft.AI.Web"/>
    <Add Type="Microsoft.ApplicationInsights.Web.ExceptionTrackingTelemetryModule, Microsoft.AI.Web"/>
  </TelemetryModules>
  <TelemetryChannel Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.ServerTelemetryChannel, Microsoft.AI.ServerTelemetryChannel"/>
  <TelemetryInitializers>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.AzureRoleEnvironmentTelemetryInitializer, Microsoft.AI.WindowsServer"/>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.DomainNameRoleInstanceTelemetryInitializer, Microsoft.AI.WindowsServer"/>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.BuildInfoConfigComponentVersionTelemetryInitializer, Microsoft.AI.WindowsServer"/>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.DeviceTelemetryInitializer, Microsoft.AI.WindowsServer"/>
    <Add Type="Microsoft.ApplicationInsights.Web.SyntheticTelemetryInitializer, Microsoft.AI.Web"/>
    <Add Type="Microsoft.ApplicationInsights.Web.ClientIpHeaderTelemetryInitializer, Microsoft.AI.Web"/>
    <Add Type="Microsoft.ApplicationInsights.Web.UserAgentTelemetryInitializer, Microsoft.AI.Web"/>
    <Add Type="Microsoft.ApplicationInsights.Web.OperationNameTelemetryInitializer, Microsoft.AI.Web"/>
    <Add Type="Microsoft.ApplicationInsights.Web.OperationIdTelemetryInitializer, Microsoft.AI.Web"/>
    <Add Type="Microsoft.ApplicationInsights.Web.UserTelemetryInitializer, Microsoft.AI.Web"/>
    <Add Type="Microsoft.ApplicationInsights.Web.SessionTelemetryInitializer, Microsoft.AI.Web"/>
  </TelemetryInitializers>
</ApplicationInsights>
```

**Comment by SergeyKanzhelev** [comment]
We saw the same behavior on one of our applications and it was in fact bad name of one of initializer. So please make sure you don't have any of them left over from the previous version of SDK.

As a result of this issue I've created two new issues:
- https://github.com/Microsoft/ApplicationInsights-dotnet/issues/55
- https://github.com/Microsoft/ApplicationInsights-dotnet/issues/45

Closing this issue for now. Feel free to re-open it.
