### ISSUE TITLE
How to deal with parallel logging from multiple threads

### ISSUE THREAD

**Issue by jstawski** [microsoft/ApplicationInsights-Home#230]
Hello, we followed the sample applications [here](https://github.com/Microsoft/ApplicationInsights-Home/tree/master/Samples/AzureEmailService/WorkerRoleA) and [here](https://github.com/Microsoft/ApplicationInsights-Home/tree/master/Samples/AzureEmailService/WorkerRoleB) on how to use requests to group all of our telemetry in a Worker Role application. This worked fine until we started to see weird results in the portal. For example we saw some requests with no dependencies and others with dependencies with huge (~15 min) gaps between them. Furthermore, the request duration did not match the timeline: a 1 minute request duration with a timeline of more than 20 mins.

We believe the issue is related to concurrency, something the sample application doesn't have to deal with. Our Request starts inside a task that can be ran in parallel with one or more tasks (we are using the On Message Received callback of ServiceBus). Furthermore, inside of each task there are multiple `awaits` with `ConfigureAwait(false)`. We believe that there are a lot of switching back and forth between threads and the `telemetry.Context.Operation.Id = (string)CallContext.LogicalGetData(CORRELATION_SLOT);` line from [here](https://github.com/Microsoft/ApplicationInsights-Home/blob/master/Samples/AzureEmailService/WorkerRoleA/Telemetry/ItemCorrelationTelemetryInitializer.cs) is the one to blame. Is it possible to be able to maintain the same `Operation Id` with all the context switching?

**Comment by Dmitry-Matveev** [comment]
@jstawski, newer AI SDKs leverage Activity object for correlation and context propagation. An example of new Operation Correlation Telemetry Initializer code is [here](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/39a5ef23d834777eefdd72149de705a016eb06b0/src/Microsoft.ApplicationInsights/Extensibility/OperationCorrelationTelemetryInitializer.cs#L18).

Activity is supposed to survive `ConfigureAwait(false)`, therefore you should be able to get right `Activity.Current` at your custom telemetry initiliazer.

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
