### ISSUE TITLE
Flags for envelope

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-Home#232]
New field `flags` on envelope will be used to set transport level characteristics for events. First one will be an ability to instruct endpoint to drop IP address. 

We are working on feature to enable collection of [full IP addresses](https://feedback.azure.com/forums/357324-application-insights/suggestions/13088763-allow-full-ip-to-be-collected). There will be a setting to opt-out from this behavior for entire Application Insights resource. Flags will enable to hide IP address for a single event. This way one can configure per-tenant or per-feature IP address collection to satisfy privacy requirements for a given app better.

**Comment by SergeyKanzhelev** [comment]
Resolved via #233

**Comment by cijothomas** [comment]
Please clarify what'll be the default behaviour by back-end.
