### ISSUE TITLE
Wierd Cloud role instances and linking together front-end & back-end for Funnels

### ISSUE THREAD

**Issue by Ruud-cb** [microsoft/ApplicationInsights-Home#236]
**Back-end:**
ASP.NET Core
Microsoft.ApplicationInsights.AspNetCore v2.2.0

**Front-end:**
applicationinsights-js v1.0.15
angular v5.0.1, typescript v2.3.2 if needed

I have some issues:
- The role instance name is incorrect, it tells me it is the staging environment while all of the data within the production environment.
![image](https://user-images.githubusercontent.com/10037514/41844830-c0af449a-7871-11e8-89fa-37b78a58a032.png)

When I do use the staging environment to test out the Funnels feature, I have selected one of my own items and clicked on "All available telemetry for this user session":

![image](https://user-images.githubusercontent.com/10037514/41846162-25ab0c36-7876-11e8-885c-55df7340ed5a.png)

Where **undefined** shows the TRACE, VIEW and EVENT items I manually sent from the front-end.
Where **RD003FF5F2FC4** shows the actual Controller REQUEST. I believe they are sent via the back-end code because I can recognize additional filters and adjustments I configured in the back-end by using a custom telemetry processor and initializer.
Where **bbwebshopprod-bbwebshopprodstaging.a...** shows the TRACE and EVENT from the back-end.

While this seems great at some point: It does link front-end and back-end requests to the same user. But unfortunately it is also missing items.

For examle, the last 4 items of this user (myself) that are linked together:

![image](https://user-images.githubusercontent.com/10037514/41846572-62b7053e-7877-11e8-83fe-eeeb82132dcf.png)

However, I know that I made this event as well (3 seconds earlier) and I would be the only one browsing to this application version (that is in the message)

![image](https://user-images.githubusercontent.com/10037514/41846658-ab368938-7877-11e8-9586-2249ff97d993.png)

What I am trying to do is create a custom event that is always fired first (this one is fired from the HomeController). After I got that I can know which user uses what application version.
Reason is because the application version is not within the Page View events so I have to use another method to distinguish users from one to another during A/B testing.
 
![image](https://user-images.githubusercontent.com/10037514/41846817-3c2df282-7878-11e8-9a03-6df1b7e8fcfd.png)
(And it is failing to retrieve data).

I don't have examples at this moment but I see it more often that some requests are not linked to a user, for example the option "All available telemetry for this user session" is not available.

**Comment by SergeyKanzhelev** [comment]
@cijothomas can you please take a look?

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
