### ISSUE TITLE
Http status code >=400  returned from middle ware is not showing as response codes in failure section of the application insights telemetry

### ISSUE THREAD

**Issue by sajibcefalo** [Microsoft/ApplicationInsights-Home#239]
Hello,
I have an asp .net web api application. There is a custom middleware placed after telemetry middleware before the asp. net web api. In some cases, the middleware return http status code 429. I have gone to the application insights failure section and  Http status code 429 is not listed in top 3 response codes. I have also tried to return other error code such 401 but nothing is listed in response code.  I guess if we return any http status code other than 200 from middleware it is always listed as http status code 200.

I have also returned 400+ http status code from web api action method, filter and delegate handler. In each case, in application insights failure section's Top 3 response codes section, the status code is enlisted.

Is this expected behavior? I am intended to show http status code 400+ returned from middleware in top 3 response code. How can I do it?

**Comment by SergeyKanzhelev** [comment]
Moving to the appropriate repo for further investigation...

**Comment by Dmitry-Matveev** [comment]
Depending on the execution sequence of certain .NET callbacks informing about end of the request you may be able to modify Request Telemetry items before they are sent to Application Insights backend. If said callback has not yet happened before your middleware is invoked, you can access Request Telemetry object about to be sent with the following code:

ASP.Net Core: `RequestTelemetry requestTelemetry = HttpContext.Features.Get<RequestTelemetry>();`
.Net: `RequestTelemetry requestTelemetry = HttpContext.Current?.GetRequestTelemetry();`

With that you can set result code in Request Telemetry object to the same value your middleware will set. This should ensure that AI will display the codes you actually send.
