### ISSUE TITLE
On demand profiling failed.

### ISSUE THREAD

**Issue by MarcelSalla** [Microsoft/ApplicationInsights-Home#240]
Hi, I'm trying to do a performance profiling on a WebApp hosted on Azure and every time I try I always get the error "On demand profiling failed." and the Azure app portal profiling blade always says that there was a timeout.
The portal says that profiling is enabled for the WebApp. When I right-click from the profiling "Open extension" from the portal it shows a page where it says that the profiling agent is properly configured and profiling is active and up to date.
Is there anything I'm doing wrong? How should I proceed to get more information about the error?

**Comment by lmolkova** [comment]
@pharring @clguimanMSFT could you guys please have a look?

**Comment by xiaomi7732** [comment]
@MarcelSalla Thanks for the feedback. I am sorry that the **Profile Now** doesn't work for you. Please try these [troubleshoot steps](https://github.com/CawaMS/Profiler-doc/blob/master/app-insights-profiler.md#troubleshooting-on-demand-profiler).
If it still is not working, send an e-mail to serviceprofilerhelp@microsoft.com with your instrumentation key that we can troubleshoot from there.
And please do **NOT** post your instrumentation key here.

**Comment by MarcelSalla** [comment]
Hi, sorry for the late response (time difference). I finally have solved the problem this is what I did:

1- First I tried reinstalling the Profiling extensions on the same WebApp. This failed and the azure portal was showing some errors of files in use by another process during the reinstallation. The profiling ended up broken unable to start new profiling sessions and the azure portal showing the profiling extension as not installed.
2. I redeployed the webapp we use a staging slot+swap. After that I was finally able to reinstall the profiling extenisions again in the Webapp but still not working, always getting a timeout error when trying to start a new profile, same as before reinstallation.
3.  I was using an Appinsights account in a different region than the Webapp (Appinsights->Central Us and WebApp->West europe) so I tried to create another Appinsights account in the same region of the WebApp I was trying to profile. This solved the problem and I was able to perform some profiling without any more issues.
I hope this helps someone else having similar problems.

Thanks for the tips on website deploys, we'll add some of this to our deployment process for sure.

**Comment by MarcelSalla** [comment]
I'm having the issue again. It seems it was a temporary fix. 
Every time I do onDemand profiling i get "Profiling timeout. Refresh and try again"...

**Comment by xiaomi7732** [comment]
@MarcelSalla Sorry this is flecky at this point. It seems that your configuration is working.
Due to some limitations, we are currently set the timeout on the client to be 15 minutes. We have been seeing profiling data **not** showing up within 15 minutes lately as well.
Could you please confirm, after the timeout, give it another 15~30 minutes, refresh the page, will you be able to see the session in the existing session list?

We are looking into how to deal with the timeout issue on the server end. We might deploy some mitigation soon but it will take a while before we can totally fix the issue.

Thanks again for your posting the progress!

**Comment by MarcelSalla** [comment]
Hi, I tried it again today. Still getting "Profiling timeout. Refresh and try again" every time.
![image](https://user-images.githubusercontent.com/32520010/42436914-bf48c528-835b-11e8-98da-b88f5d1cb0fa.png)

**Comment by xiaomi7732** [comment]
@MarcelSalla 
Thanks for the detailed info. Could you please share your iKey with us to serviceprofilerhelp@microsoft.com, once I have the iKey, I can look into the telemetry to investigate what had happened.

**Comment by Dmitry-Matveev** [comment]
@xiaomi7732, it looks like @MarcelSalla is still experiencing an issue, can you please take a look?

**Comment by MarcelSalla** [comment]
Hi yesterday i tried the on-demand profiling twice and it worked, so I'm going to close the issue.
I don't know exactly what happened but it seems to be working now.
Thanks for your help

**Comment by pharring** [comment]
If anyone else runs into issues with the Application Insights Profiler on App Service, please ensure you're running the latest Application Insights site extension (version 2.6.5 at time of writing). That version contains a fix for a bug where profiling will completely stop after a while. Upgrade from the "Extensions" blade for your App Service in the Azure Portal.
