### ISSUE TITLE
Release annotation script is failing to get redirect link

### ISSUE THREAD

**Issue by xt0rted** [Microsoft/ApplicationInsights-Home#242]
I just went to do a deploy, which uses [CreateReleaseAnnotation.ps1](https://github.com/Microsoft/ApplicationInsights-Home/blob/master/API/CreateReleaseAnnotation.ps1) to create a release annotation once the deploy finishes, and the script failed to run saying:

>Failed to find the redirect link to create a release annotation

Going to the url manually results in being redirected to a page that's giving a 401 error.

The last time this successfully worked for me was July 17th at 4:38 PM EDT.

**Comment by xt0rted** [comment]
Maybe this was a premature issue, looks like my calls to the fwlink url are succeeding now. I was just able to create a new release annotation with that script.

**Comment by SergeyKanzhelev** [comment]
Great! re-open if it will repeat again
