### ISSUE TITLE
ExceptionConverter null reference exception when logging an exception

### ISSUE THREAD

**Issue by freever** [Microsoft/ApplicationInsights-Home#243]
I am using Application Insights to log telementry from a Xamarin.Forms application. I currently am getting an exception when attempting to TrackException on an exception thrown by my application. The exception I am trying to track happens to be an Autofac resolution exception, and when I call telementryClient.TrackException(e) on it, ApplicationInsights throws a NullReferenceException, the abridged stack trace for which follows.

I tried throwing an arbitrary DivideByZeroException, and this does NOT cause the same problem, so I'm thinking it must be something odd about the Autofac exception that is causing this. Ioc exceptions tend to have a lot of inner exceptions (this one only has 2 though). 

Here's the stack trace:  

> at Microsoft.ApplicationInsights.Extensibility.Implementation.ExceptionConverter.GetStackFrame (System.Diagnostics.StackFrame stackFrame, System.Int32 frameId) [0x00014] in <23fec81bf9274095a03fbadce8d0faf4>:0 
>   at Microsoft.ApplicationInsights.Extensibility.Implementation.ExceptionConverter.SanitizeStackFrame[TInput,TOutput] (System.Collections.Generic.IList`1[T] inputList, System.Func`3[T1,T2,TResult] converter, System.Func`2[T,TResult] lengthGetter) [0x0003b] in <23fec81bf9274095a03fbadce8d0faf4>:0 
>   at Microsoft.ApplicationInsights.Extensibility.Implementation.ExceptionConverter.ConvertToExceptionDetails (System.Exception exception, Microsoft.ApplicationInsights.Extensibility.Implementation.External.ExceptionDetails parentExceptionDetails) [0x00013] in <23fec81bf9274095a03fbadce8d0faf4>:0 
>   at Microsoft.ApplicationInsights.DataContracts.ExceptionTelemetry.ConvertExceptionTree (System.Exception exception, Microsoft.ApplicationInsights.Extensibility.Implementation.External.ExceptionDetails parentExceptionDetails, System.Collections.Generic.List`1[T] exceptions) [0x00024] in <23fec81bf9274095a03fbadce8d0faf4>:0 
>   at Microsoft.ApplicationInsights.DataContracts.ExceptionTelemetry.ConvertExceptionTree (System.Exception exception, Microsoft.ApplicationInsights.Extensibility.Implementation.External.ExceptionDetails parentExceptionDetails, System.Collections.Generic.List`1[T] exceptions) [0x0009a] in <23fec81bf9274095a03fbadce8d0faf4>:0 
>   at Microsoft.ApplicationInsights.DataContracts.ExceptionTelemetry.ConvertExceptionTree (System.Exception exception, Microsoft.ApplicationInsights.Extensibility.Implementation.External.ExceptionDetails parentExceptionDetails, System.Collections.Generic.List`1[T] exceptions) [0x0009a] in <23fec81bf9274095a03fbadce8d0faf4>:0 
>   at Microsoft.ApplicationInsights.DataContracts.ExceptionTelemetry.UpdateExceptions (System.Exception exception) [0x00006] in <23fec81bf9274095a03fbadce8d0faf4>:0 
>   at Microsoft.ApplicationInsights.DataContracts.ExceptionTelemetry.set_Exception (System.Exception value) [0x00007] in <23fec81bf9274095a03fbadce8d0faf4>:0 
>   at Microsoft.ApplicationInsights.DataContracts.ExceptionTelemetry..ctor (System.Exception exception) [0x0002a] in <23fec81bf9274095a03fbadce8d0faf4>:0 
>   at Microsoft.ApplicationInsights.TelemetryClient.TrackException (System.Exception exception, System.Collections.Generic.IDictionary`2[TKey,TValue] properties, System.Collections.Generic.IDictionary`2[TKey,TValue] metrics) [0x00024] in <23fec81bf9274095a03fbadce8d0faf4>:0

**Comment by SergeyKanzhelev** [comment]
Fixed couple weeks back: https://github.com/Microsoft/ApplicationInsights-dotnet/pull/832 Please update to the latest version
