### ISSUE TITLE
Change telemetry item information in Search results

### ISSUE THREAD

**Issue by MatthewDavidCampbell** [microsoft/ApplicationInsights-Home#248]
Using latest Application Insights via Azure portal....

With traces there is a set of properties shown in the item in the results when choosing the Search page.  For example, a normal trace has the timestamp and log level in the bold title followed by the message property and there after device type plus security level.  Is it possible through the portal or powershell (other) to switch out say security level with another property (say a custom dimension)?  Have google:ed without finding a similar issue.

![image](https://user-images.githubusercontent.com/1491747/44645786-1cbdd380-a9d9-11e8-9931-3ccd08f25513.png)

**Comment by SergeyKanzhelev** [comment]
You can write custom queries in Analytics. See https://docs.microsoft.com/azure/application-insights/app-insights-analytics

Is it what you need?

**Comment by SergeyKanzhelev** [comment]
Are you talking about set of properties which are shown or values of those properties? If first - custom query is the answer. If second - you need to tell what kind of app (C#?) you monitor and how you enabled monitoring.

**Comment by MatthewDavidCampbell** [comment]
The search page in the picture (regardless of where the telemetry is coming from i.e. dot net, spring, etc.) shows a group of **default** properties for every telemetry item in the result set.  This default set of properties must be defined somewhere in the Azure portal for Insights.  Seeing the _Device type_ (as PC) for isn't to helpful and we would like to adjust | change | set that particular default property to something else (say coming from a custom dimension or whatever that is part of the telemetry).  There don't seem to be any GUI controls for this in the Azure portal.  Thought maybe there might be a PowerShell or aks command (thus the original question).  Of course we can just us the query API but would like to also alter the information presented by the search page.

**Comment by SergeyKanzhelev** [comment]
Got it. It's a dup of this than: https://github.com/Microsoft/ApplicationInsights-Home/issues/216

Thanks for detailed explanation. I think the official answer is still to use analytics and operator `project` to define which properties you want to see in results.

You can upvote https://feedback.azure.com/forums/357324-application-insights/suggestions/19323058-show-different-trace-colors-based-on-severity and https://feedback.azure.com/forums/357324-application-insights/suggestions/34117813-show-message-within-list-of-events

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
