### ISSUE TITLE
Any way to alert on HeartBeatState for a specific server in a resource?

### ISSUE THREAD

**Issue by efunkenbusch** [Microsoft/ApplicationInsights-Home#250]
We have an ApplicationInsights resource that has multiple servers in it.  Using the HeartBeatState will not tell us if one of the servers goes down.  Is there any way to create an alert that filters to specific machines in the resource?

**Comment by Dmitry-Matveev** [comment]
Yes, new feature in Azure Monitor is [alert on logs](https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitor-alerts-unified-log). You may produce a query that filters down to the machines you'd like and then alert on specific count yielded from the query.
