### ISSUE TITLE
Error retrieving exception data in Azure Portal due to unescaped backslashes

### ISSUE THREAD

**Issue by fadamsen** [Microsoft/ApplicationInsights-Home#251]
My apologies if this is the wrong place to report this issue, but I have tried sending feedback through the feedback option in the Azure Portal with no luck.

We are sending telemetry from PHP and the data is showing up in Application Insights just fine. However, we're having trouble accessing exception telemetry inside the Failures experience.

We can see the exceptions just fine:

![image](https://user-images.githubusercontent.com/4189385/44896256-dd082c00-acf7-11e8-9b10-081d890e906d.png)

We can also drill into the exceptions if we just press the ´1 Exceptions` button:

![image](https://user-images.githubusercontent.com/4189385/44896270-ef826580-acf7-11e8-9ca2-626f0f478d69.png)

However, we are unable to click on Exception Problem Ids.

![image](https://user-images.githubusercontent.com/4189385/44896277-f6a97380-acf7-11e8-86cd-62b170ab4498.png)

Looking at the requests, we receive 400 Bad Request with the following JSON body:

```json
{"error":{"message":"The request had some invalid properties","code":"BadArgumentError","innererror":{"code":"SyntaxError","message":"Syntax Error"}}}
```

I have tried copying the query and executing it in Log Analytics, and that also results in a syntax error. Here is the query for reference:

```
set truncationmaxrecords=10000;set truncationmaxsize=67108864;let OperationIdsWithExceptionType = (excType: string) { exceptions | where timestamp > datetime("2018-08-30T06:13:00.000Z") and timestamp < datetime("2018-08-31T06:13:00.000Z") | where tobool(iff(excType == "null", isempty(type), type == excType)) | distinct operation_Id };let OperationIdsWithFailedReqResponseCode = (respCode: string) { requests | where timestamp > datetime("2018-08-30T06:13:00.000Z") and timestamp < datetime("2018-08-31T06:13:00.000Z")| where iff(respCode == "null", isempty(resultCode), resultCode == respCode) and success == false | distinct operation_Id };let OperationIdsWithFailedDependencyType = (depType: string) { dependencies | where timestamp > datetime("2018-08-30T06:13:00.000Z") and timestamp < datetime("2018-08-31T06:13:00.000Z")| where iff(depType == "null", isempty(type), type == depType) and success == false | distinct operation_Id };let OperationIdsWithFailedDepResponseCode = (respCode: string) { dependencies | where timestamp > datetime("2018-08-30T06:13:00.000Z") and timestamp < datetime("2018-08-31T06:13:00.000Z")| where iff(respCode == "null", isempty(resultCode), resultCode == respCode) and success == false | distinct operation_Id };let OperationIdsWithExceptionBrowser = (browser: string) { exceptions | where timestamp > datetime("2018-08-30T06:13:00.000Z") and timestamp < datetime("2018-08-31T06:13:00.000Z") | where tobool(iff(browser == "null", isempty(client_Browser), client_Browser == browser)) | distinct operation_Id }; exceptions | where timestamp > datetime("2018-08-30T06:13:00.000Z") and timestamp < datetime("2018-08-31T06:13:00.000Z") | where ((problemId == "TypeError at AskCody\ApplicationInsights\TelemetryClient::startDependency(Activity) in C:\Workspace\AskCody\concinnity\src\AppBundle\Service\Azure\ApplicationInsights\GuzzleMiddleware.php:42"))   | where (client_Type != "Browser") | summarize sum(itemCount)by problemId, bin(timestamp, 5m)| project problemId, timestamp, sum_itemCount| order by timestamp asc
```

To me, it seems like the backslashes are not escaped properly. I guess backslashes don't show up in as many places using stuff other than PHP (although they might be in file paths on Windows, I suppose), but I feel that it should work regardless. We are going to modify our exception telemetry to use something other than backslashes for now, but it would be nice not having to do that.

Here are some Ids that I hope will be helpful:

x-ms-client-request-id: 74120371-1946-6f85-db93-11b1f6e187cc
x-ms-client-request-id: 0647b2c6-4dbc-c37d-e4d5-b439f2c5945f
x-ms-client-request-id: 13dc56a5-33ea-0d1b-52a3-725c3bcae6b9
x-ms-client-session-id: a662c41590fa463db78fb946bd6d029e

**Comment by SergeyKanzhelev** [comment]
@zakimaksyutov , please direct as appropriate

**Comment by SergeyKanzhelev** [comment]
@fadamsen thank you for reporting! GitHub is a good place to report the issue. You can also use a "smiley face" button in right upper corner of the Azure portal to file issues.

**Comment by madeleinefletcher** [comment]
Thanks for reporting! We have checked in a fix for this that should be deployed next week. I'll update the thread when the fix is deployed so you can verify.

**Comment by fadamsen** [comment]
Awesome, thanks!

**Comment by madeleinefletcher** [comment]
Apologies for the delay. It seems our first fix wasn't quite enough. I verified and checked in a new fix that should be deployed by Tuesday next week.

**Comment by fadamsen** [comment]
Thanks for letting us know. We'll just keep our current workaround, which works quite well, in place.

**Comment by fadamsen** [comment]
Hello again! The fix for exception problem IDs containing backslashes is working, but we are now unable to drill into exceptions containing backslashes:

![image](https://user-images.githubusercontent.com/4189385/45671780-a8350b00-bb26-11e8-956c-57a48cd1383d.png)

x-ms-client-request-id: 9b7942c3-6705-ea0b-fc1c-a62d078d6a36

**Comment by fadamsen** [comment]
This still doesn't work as per my previous comment. Any updates?

**Comment by fadamsen** [comment]
The issue I reported on [Sep 18](https://github.com/Microsoft/ApplicationInsights-Home/issues/251#issuecomment-422288536) has been fixed since my last comment. Thanks!
