### ISSUE TITLE
Application insights service does not honor modified values in DependencyTelemetry

### ISSUE THREAD

**Issue by RamjotSingh** [microsoft/ApplicationInsights-Home#252]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1. Download [TestAppInsightsDependencyTelemetry.zip](https://github.com/Microsoft/ApplicationInsights-dotnet/files/2299020/TestAppInsightsDependencyTelemetry.zip)
2. Add the AI key to Startup.cs
3. Run the code
4. Open https://localhost:8890/api/values
5. Notice the DependencyTelemetry flowing out

##  Actual Behavior
Target is set to bing.com

## Expected Behavior
ExternalRequestTelemetryProcessor should write a custom value for Target instead of bing.com

## Version Info 
SDK Version : ApplicationInsights 2.5.1 + ApplicationInsights.ASPNetCore 2.2.1
.NET Version :	NetCore2.1 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : Visual Studio
OS : Windows 10
Hosting Info (IIS/Azure WebApps/ etc) : Local hosting using Kestrel

#### What is the application doing? 
ApplicationInsights automatically tracks all the outgoing requests and assign the Target field to applications which are well known. I tried writing a TelemetryProcessor that would assign well known names to dependencies I recognize. This is done by writing the details in AsyncLocal and then reading these details as part of TelemetryProcessor and writing them into DependencyTelemetry. This works till the point the call is in my system i.e. if I was to edit the endpoint and send the telemetry to non-AI endpoint (in the above given zip look at line 30 of startup.cs) it will be sent correctly, it however seems that when the call lands on AppInsight service the data is reprocessed and target is changed the base url of the call which overrides any values set by code.
Attached code has a special listener which can receive AI events and dump them into console. If this is used correct target name is used, however when I use log analytics to search for data, the wrong value (bing.com) is shown.

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
