### ISSUE TITLE
[Open for Comments] Documentation for Local Storage

### ISSUE THREAD

**Issue by MS-TimothyMothra** [Microsoft/ApplicationInsights-Home#257]
This document addresses an SDL concern:
Our telemetry channel persists data to a local storage, without calling out that this storage is not encrypted.
This could have implications for customers considering PII or HIPAA and they need to be made aware of this storage.

I propose to add this to the article: [Data collection, retention, and storage](https://docs.microsoft.com/azure/application-insights/app-insights-data-retention-privacy)

---

## Does the SDK create temporary local storage?

Yes, certain Telemetry Channels will persist data locally if an endpoint cannot be reached. Please review below to see which frameworks and telemetry channels are affected.

Telemetry channels that utilize local storage create temp files in the TEMP or APPDATA directories which are restricted to the specific account running your application. This may happen when an endpoint was temporary unavailable or you hit the throttling limit. Once this issue is resolved, the telemetry channel will resume sending all the new and persisted data.

This persisted data is **not encrypted** and it is strongly recommended to restructure your data collection policy to disable the collection of private data. (See [How to export and delete private data](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-customer-data#how-to-export-and-delete-private-data) for more information.)

If a customer needs to configure this directory with specific security requirements it can be configured per framework. Please make sure that the process running your application has write access to this directory, but also make sure this directory is protected to avoid telemetry being read by unintended users.

### Java

`C:\Users\username\AppData\Local\Temp` is used for persisting data. This location isn't configurable from the config directory and the permissions to access this folder are restricted to the specific user with required credentials. (See [implementation](https://github.com/Microsoft/ApplicationInsights-Java/blob/40809cb6857231e572309a5901e1227305c27c1a/core/src/main/java/com/microsoft/applicationinsights/internal/util/LocalFileSystemUtils.java#L48-L72) here.)

###  .Net

By default `ServerTelemetryChannel` uses the current user’s local app data folder `%localAppData%\Microsoft\ApplicationInsights` or temp folder `%TMP%`. (See [implementation](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/91e9c91fcea979b1eec4e31ba8e0fc683bf86802/src/ServerTelemetryChannel/Implementation/ApplicationFolderProvider.cs#L54-L84) here.)

Via configuration file:
```
<TelemetryChannel Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.ServerTelemetryChannel,   Microsoft.AI.ServerTelemetryChannel">
    <StorageFolder>D:\NewTestFolder</StorageFolder>
</TelemetryChannel>
```

Via code:

- Remove ServerTelemetryChannel from configuration file
- Add this snippet to your configuration:
```
ServerTelemetryChannel channel = new ServerTelemetryChannel();
channel.StorageFolder = @"D:\NewTestFolder";
channel.Initialize(TelemetryConfiguration.Active);
TelemetryConfiguration.Active.TelemetryChannel = channel;
```

### NetCore

By default `ServerTelemetryChannel` uses the current user’s local app data folder `%localAppData%\Microsoft\ApplicationInsights` or temp folder `%TMP%`. (See [implementation](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/91e9c91fcea979b1eec4e31ba8e0fc683bf86802/src/ServerTelemetryChannel/Implementation/ApplicationFolderProvider.cs#L54-L84) here.) 
In a Linux environment, local storage will be disabled unless a storage folder is specified.

The following code snippet shows how to set `ServerTelemetryChannel.StorageFolder` in the `ConfigureServices()` method of your `Startup.cs` class:

```
services.AddSingleton(typeof(ITelemetryChannel), new ServerTelemetryChannel () {StorageFolder = "/tmp/myfolder"});
```

(See [AspNetCore Custom Configuration](https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Custom-Configuration) for more information. )

### NodeJS

The local folder can be overridden by changing the runtime value of the static variable `Sender.TEMPDIR_PREFIX` found in [Sender.ts](https://github.com/Microsoft/ApplicationInsights-node.js/blob/7a1ecb91da5ea0febf5ceab13d6a4bf01a63933d/Library/Sender.ts#L384). This value controls the subfolder within the TEMP directory.

**Comment by MS-TimothyMothra** [comment]
@Dmitry-Matveev @OsvaldoRosado please review and add your comments or amend the sections above.

**Comment by OsvaldoRosado** [comment]
Some comments:
> This channel implements exponential retry intervals and respect Retry-After header set by the server.
This isn't true in Node. No idea about others.

>By default we use the current user’s local app data folder `%localAppData%\Microsoft\ApplicationInsights`
This particular subfolder folder is only true for .NET AFAIK

Should we discuss more that `TEMPDIR_PREFIX` only changes the subfolder within the TEMP directory?

**Comment by OsvaldoRosado** [comment]
>These folders are restricted to the specific account running your application.
This statement is true at a high level but UNIX permissions and NTFS ACLs have different characteristics. Should we expand on how this works per-platform?

**Comment by MS-TimothyMothra** [comment]
@OsvaldoRosado,
Expanding on the specifics of directory permissions may be out of scope for this document. If you think a there is a better way to make that statement, please share. :)

I updated the NodeJS description using your comment about TEMP subfolders. 

Let me sync up with Dmitry to discuss the best way to describe default folders.

Thanks for your feedback!

**Comment by Dmitry-Matveev** [comment]
"Local Storage is not encrypted' is too generic and implies that "a channel" has it, so implies all SDKs that have "a channel" act the same way. We may want to be more specific and simply list channels that implement such storage or SDKs we consider in-scope for this article. Alternatively, you can omit/change sentences that are .NET-specific, such as "this channel does X" and replace with "AI channels that utilize local storage typically do X.." or something along those lines.

Also, the header screams "not secure", however, by default AI ACLs on Windows, uses in-memory on Linux, sets permissions in node.js on both platforms, so is actually either securing the folder or uses no storage. Is there a way we can make it more informative and less provocative?

**Comment by Dmitry-Matveev** [comment]
> This affects .Net's ServerTelemetryChannel. By default we use the current user’s local app data folder %localAppData%\Microsoft\ApplicationInsights or temp folder %TMP%.

We can re-word it as follows (I think we can remove "This affects" since we phrased topic as a question):
"By default ServerTelemetryChannel uses ..."

While in the context of the specific language/SDK (not in common), we can also mention that .NET ACLs folder to the current process's identity. (Although, not necessary).

**Comment by dhaval24** [comment]
@MS-TimothyMothra java SDK uses `C:\Users\username\AppData\Local\Temp` this location for persisting telemetry if the end point is not available. This location isn't configurable from the config directory and the permissions to access this folder is restricted to the specific user with required credentials. 

We do have exponential retry mechanism in Java SDK and we do respect the response headers. Let me know if you need anything extra here.

**Comment by OsvaldoRosado** [comment]
> but also make sure this directory is protected to avoid telemetry being read by unintended users

This has me thinking. If the intention of this is that users are on their own to protect the directory, should we also give instructions on how to stop attempting to ACL/chmod the selected directory? Could this SDK behavior potentially work against whatever the customer was trying to do by changing directories?

**Comment by MS-TimothyMothra** [comment]
I've created a PR against [Azure Docs](https://github.com/MicrosoftDocs/azure-docs/pull/14902) and am closing this issue.
Thank you everyone!
