### ISSUE TITLE
Documentation for schema and valid values for availabilityResults

### ISSUE THREAD

**Issue by alfredmyers** [Microsoft/ApplicationInsights-Home#259]
I can't find the schema documentation and acceptable values for the fields in `availabilityResults` when querying in Analytics.
For instance:
- Does the column `id` contain the *primary key* for the availability result?
- What are the possible values for `success`?
- The column `message` correlates with `success`?
- What are the columns operation_Id and operation_ParentId for?

**Comment by Dmitry-Matveev** [comment]
Analytics provides an operator `| getschema` to read the schema of the underlying table.
Not sure if there is a documentation beyond that, currently.

I can suggest `| summarize by success` to figure out possible values for success and the other fields before you introduce filters into the query.

`id` is expected to be unique. `operation_Id` and `operation_ParentId` are typically used for correlation and by looking at all items having this `operation_Id` you may find how this transaction looks end to end with all requests and associated telemetry it produced if AI SDK is installed everywhere along the way of the request propagation:

```
union * | where operation_Id == "..." // If data is reported to 1 AI resources
union app("AIResource1").*, app("AIResource2").* | where operation_Id == "..." // If data is reported to several AI resources
```
