### ISSUE TITLE
Telemetry channel should be configured for telemetry configuration before tracking telemetry.

### ISSUE THREAD

**Issue by lukepuplett** [Microsoft/ApplicationInsights-Home#26]
I get this message upon WebAPI start-up.

`Telemetry channel should be configured for telemetry configuration before tracking telemetry.`

This just started happening, though to be honest, someone on the team screwed-up a merge (as usual) so I'm not sure what's happened.

I did a forced reinstall of the NuGet packages, we're on 2.0.0-beta3 because I need some stuff in that version to correct a false negative on a WCF dependency.

I have a unit test that checks the API's initialization routine and that fails with:

`System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.InvalidOperationException : Type 'Microsoft.ApplicationInsights.Web.UserAgentTelemetryInitializer, Microsoft.AI.Web' could not be loaded.`

I've no clue.

**Comment by lukepuplett** [comment]
I copied the applicationInsights.config from another Web API and its now working.

I think you need to make the loading more robust and handle loading exceptions and emit a very clear error message with suggested remedial advice, or reconsider the approach of using config files.

**Comment by lukepuplett** [comment]
Actually, it might have been a corrupt config file.

I think we remmed out the line adding the Performance collector because of a serious bug that hangs the whole app at random points. But because the default MS config file has a comment inside the <add ...> tag the tag is not on a single line, like all the others, so remming just that line actually breaks the XML.

The XML is not checked or something by the AI systems and seems to ignore the bad file and try and load stuff, and fail.

**Comment by SergeyKanzhelev** [comment]
@lukepuplett, thanks for reporting. I want to assure you we are working with CLR team on resolution on hang issue. Meanwhile, would you please comment with the snippet of bad config file in this issue - I think they are related: https://github.com/Microsoft/ApplicationInsights-dotnet/issues/55

**Comment by lukepuplett** [comment]
Thanks Sergey. I think the general conclusion in the link is correct, i.e. that problems with config aren't surfaced in a discoverable way.

**Comment by SergeyKanzhelev** [comment]
This was resolved. Please use 2.0 stable
