### ISSUE TITLE
Send client session id to backend api

### ISSUE THREAD

**Issue by NickSevens** [Microsoft/ApplicationInsights-Home#262]
I have a client side application which calls a .net core API.
What I would like is to have Application Insights match events tracked in both client and server, so that they would both end up in the same sessionId.
Is this possible? I searched for ways to pass the sessionId to the backend but couldn't find a solution there.
Is there any guidance on how to achieve this?
Or is there another way to make sure frontend and backend actions are "grouped"?

Thanks in advance

**Comment by SergeyKanzhelev** [comment]
Send cookie: http://apmtips.com/blog/2016/07/09/tracking-users-in-api-apps/.

Reopen if this doesn't help
