### ISSUE TITLE
Missing stacktrace of inner exceptions in Service Fabric project

### ISSUE THREAD

**Issue by gemas** [Microsoft/ApplicationInsights-Home#264]
We have a Service Fabric application. Existing out of an WebAPI and a Stateless Service.

When the WebAPI does a remote call to the Stateless Service and an Exception is thrown in the Service we catch this in the WebAPI.
While debugging we inspect this exception in the WebAPI, we see the Exception contains a lot of inner exceptions, the lowest one containing the stacktrace of the Service.
When we call the function TrackException(ex) the exception is logged in Application insights.
But the stacktraces of the inner exceptions are not.
So we dont know where it went wrong.

We use version 2.7.2 of ApplicationInsights

**Comment by SergeyKanzhelev** [comment]
Moved to appropriate repo. I'll answer there.
