### ISSUE TITLE
[Work In Progress] Documentation for Azure Functions

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-Home#266]
### This doc has been published: 
https://docs.microsoft.com/azure/application-insights/azure-functions-supported-features?toc=/azure/azure-monitor/toc.json

I'm using this issue to track future work.
We can't publish future features on the official docs.
As soon as the "Coming Soon" features are released, we will update the official doc.

### Next Steps:

**TODO**: Need up update doc after these PRs are merged:

- Http tracking and distributed tracing
Azure/azure-webjobs-sdk#2073

- Functions v1: Update ApplicationInsights to 2.6.4 and enable heartbeats
Azure/azure-webjobs-sdk#1967

- App Insights request detail logging 
https://github.com/Azure/azure-functions-host/issues/2447

### Tracking Functions Releases:

- [Azure WebJobs SDK](https://github.com/Azure/azure-webjobs-sdk/releases)
- [Azure Functions Host](https://github.com/Azure/azure-functions-host/releases)

----------

## Application Insights for Azure Functions supported features [COMING SOON]

| Azure Functions                   	| V1            	| V2 (Ignite 2018) 	| 
|-----------------------------------	|---------------	|------------------	|
| **Application Insights .Net SDK**     	| **2.5.0**  (2.6.4 Coming Soon)       	| **2.7.2** (2.9.0 Coming Soon)            	|
| **Application Insights Asp.Net Core SDK** 	|               	| (2.6.0 Coming Soon)                 	| 
| | | | 
| **Supported Features**                	|               	|                  	|           	
| &bull; Heartbeats                      	| (Coming Soon) 	| Yes              	| 
| | | | 
| **Correlation**                       	|               	|                  	|           	
| &bull; Incoming Requests                        	|               	| (Coming Soon)                 	| 
| &bull; W3C                             	|               	| (Coming Soon)                 	|

**Comment by MS-TimothyMothra** [comment]
@mrbullwinkle Do you have anything to add to this?

Where do you think would be the best place to store this document?
In my opinion, it should be under our Azure Monitor TOC instead of the Azure Functions TOC.
When customers want support they frequently come to us looking for details. Second, we are going to be far more knowledgeable about our product than the Azure Functions team will be.

Thanks

**Comment by cijothomas** [comment]
@MS-TimothyMothra Great to see us addressing doc issues!

small comments:

W3C => maybe under correlation category.
QuickPulse => Change to QuickPulse/LiveMetrics  (as live metrics is the official name)

Application Insights .NetCore SDK => Application Insights Asp.Net Core SDK

**Comment by lmolkova** [comment]
here is the link to current AzureFunctions monitoring docs: https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring - it's relevant for v1 only

@MS-TimothyMothra  thanks for doing this!!!

**Comment by lmolkova** [comment]
**Dependency Collection** should probably appear under **Automatic Collection of**

**Comment by mrbullwinkle** [comment]
@MS-TimothyMothra I think we should definitely be able to find a home for this in the Azure Monitor TOC. The only thing we would need to be careful of is the **V2+ (TBD) column**. 

They have a rule in the docs.microsoft.com contributors guide that the Final PR reviewers check and treat as a merge blocking item, which says we can only publish things that exist today, so any statement regarding future plans are generally not allowed in the docs. 

Getting around this could be as simple as swapping TBD with Preview or Beta as long as those features exist in one of the beta builds/releases. But, if it is functionality that a customer can't test out today we won't be able to document it until it is ready for a customer to preview/test.

**Comment by MS-TimothyMothra** [comment]
Thanks @mrbullwinkle.
@lmolkova is very knowledgeable about the Azure Functions vocabulary. I'll touch base with her to see if "Preview" is appropriate.

It's important to express to our customers that these specific features (rows) are NOT supported at this time and when we expect them to be supported. If you have any suggestions on how to do this better, I would love to hear them.

Thanks!

**Comment by mrbullwinkle** [comment]
@MS-TimothyMothra and yes to **Reference** for the TOC location.

**Comment by MS-TimothyMothra** [comment]
@mrbullwinkle 
I got clarification that **V2+** will not be a separate product, but a future update to the existing **V2**. With this in mind, I removed the 3rd column and added a **Coming Soon** to the 2nd column.

I understand that this still may be blocked for the official docs.microsoft. 
I think a fair argument could be made for wanting to distinguish "Not Currently Supported" vs "Never Supported".
Regardless, if this is non-negotiable we can track this internally by our team and omit it from the final document :)

**Comment by cijothomas** [comment]
https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/759#issuecomment-426687852 Seems like adding TelemetryInitializer is already supported. @brettsam

**Comment by MS-TimothyMothra** [comment]
I updated the draft to show TelemetryInitializer.
@brettsam, is it safe to assume your same demo would work for TelemetryProcessors as well?

**Comment by lmolkova** [comment]
@MS-TimothyMothra yes it does. Basically all AspNetCore AI SDK configuration options and documentation is applicable to Azure functions now.

**Comment by MS-TimothyMothra** [comment]
@lmolkova thanks, that's great.
What's the best way to phrase that for a feature matrix? :)

**Comment by MS-TimothyMothra** [comment]
First draft has been merged and will be published soon! :)

We can't publish future features on the official docs.
As soon as the "Coming Soon" features are released, we will update the official doc.

**Comment by cijothomas** [comment]
Related : https://github.com/Microsoft/ApplicationInsights-dotnet/issues/941

**Comment by MS-TimothyMothra** [comment]
FYI: Need to update document after this PR is deployed to Production: [Functions v1: Update ApplicationInsights to 2.6.4 and enable heartbeats](https://github.com/Azure/azure-webjobs-sdk/pull/1967)

**Comment by MS-TimothyMothra** [comment]
FYI: Need to update document after this PR is deployed to Production: [Enable AppInsights http requests collection and W3C distributed tracing support](https://github.com/Azure/azure-webjobs-sdk/pull/1965)

**Comment by MS-TimothyMothra** [comment]
**TODO**: Need up update doc after these PRs are merged.

- Configure performance counters collection
https://github.com/Azure/azure-webjobs-sdk/pull/2067

- Http tracking and distributed tracing
https://github.com/Azure/azure-webjobs-sdk/pull/2073

- Functions v1: Update ApplicationInsights to 2.6.4 and enable heartbeats
https://github.com/Azure/azure-webjobs-sdk/pull/1967
