### ISSUE TITLE
how to set the session_id and user_id

### ISSUE THREAD

**Issue by imeya** [Microsoft/ApplicationInsights-Home#267]
it's a very simple asp.net standard web mvc project.
To customize the session_id and user_id, I add the following code like below:
```
namespace WebMVCStandard
{
    public class UserTrackingTelemetryInitializer:ITelemetryInitializer
    {
        public void Initialize(ITelemetry telemetry)
        {
            if (HttpContext.Current?.Session == null)
                return;

            if (HttpContext.Current.Session["UserId"] == null)
            {
                HttpContext.Current.Session["UserId"] = Guid.NewGuid().ToString();
            }

            telemetry.Context.User.Id = (string)HttpContext.Current.Session["UserId"];
            telemetry.Context.Session.Id = HttpContext.Current.Session.SessionID;
        }
    }
}
```

Then register it in the ApplicationInsights.config:
`<Add Type="WebMVCStandard.UserTrackingTelemetryInitializer,WebMVCStandard"/>`

After that, I started to execute it. But the session_id and user_id is not the one I set in code.
After searching, there is a related doc about this issue: https://github.com/MicrosoftDocs/azure-docs/issues/11721 .

So I tried to write code in Session_OnStart() in Global.asax.cs like below:
```
protected void Session_OnStart()
        {
            RequestTelemetry telemetry = new RequestTelemetry();
            if (HttpContext.Current?.Session == null)
                return;

            if (HttpContext.Current.Session["UserId"] == null)
            {
                HttpContext.Current.Session["UserId"] = Guid.NewGuid().ToString();
            }

            telemetry.Context.User.Id = (string)HttpContext.Current.Session["UserId"];
            telemetry.Context.Session.Id = HttpContext.Current.Session.SessionID;
        }

```
But those velues are still not set correctly(still return something like NVhLF etc.), if I set a breakpoint in session_OnStart(), I can see the values can be set there. So I assume in somewhere, it's changed again.

Could somebody let me know how to set those values? thanks.

PS:
However, if I use TrackTrace() / TrackRequest() and other Trackxxx() method, the session_id and user_id can be set correctly.

**Comment by Dmitry-Matveev** [comment]
I think that referenced doc bug you mentioned actually implies that you'd need to modify the existing `RequestTelemetry` object in `Session_OnStart` method instead of creating a new one.
You can access an existing object via HttpContext or HttpContextBase [extension method](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/3cc166e3c9ec9d3f4ce77f48d3ab8c6bd6218808/Src/Web/Web.Shared.Net/HttpContextExtension.cs) AI SDK provides: 
`httpContext.GetRequestTelemetry()`

**Comment by imeya** [comment]
thank you. I will take a try.

**Comment by imeya** [comment]
@Dmitry-Matveev , I tried modify the existing `RequestTelemetry `on `Session_OnStart` method. But only the userid and sessionid in the first request(like first request to home page) is changed, then in the following requests, it keeps the short string like NVhLF. The code like below:


```
protected void Session_OnStart()
        {
            
            RequestTelemetry telemetry = Context.GetRequestTelemetry();
            //or RequestTelemetry telemetry = HttpContextExtension.GetRequestTelemetry(HttpContext.Current);

            if (HttpContext.Current?.Session == null)
                return;

            if (HttpContext.Current.Session["UserId"] == null)
            {
                HttpContext.Current.Session["UserId"] = Guid.NewGuid().ToString();
            }
            telemetry.Context.User.Id = (string)HttpContext.Current.Session["UserId"];
            telemetry.Context.Session.Id = HttpContext.Current.Session.SessionID;
        }
```

And also I found that the  [docs ](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-usage-send-user-context#aspnet-apps-setting-the-user-context-in-an-itelemetryinitializer)may be updated, so I followed this doc, it's ok for all the requests telemetry, but for trace telemetry, it still keeps the short string like NVhLF, for both userid and sessionid.

Could you please point me out if something I'm missing? Thanks you.

**Comment by Dmitry-Matveev** [comment]
It may happen that Trace Telemetry is skipped in the code you referenced above because it has non-empty user Id by the time it reaches Telemetry Initializer. You may choose to always overwrite user with what you think the right value is and that may help to change the value reported in Trace Telemetry, for instance:

```
  public class MyTelemetryInitializer : ITelemetryInitializer
  {
    public void Initialize(ITelemetry telemetry)
    {
        var ctx = HttpContext.Current;

        // If telemetry initializer is called as part of request execution and not from some async thread
        if (ctx != null)
        {
            var requestTelemetry = ctx.GetRequestTelemetry();

            // Set the user and session ids from requestTelemetry.Context.User.Id, which is populated in Application_PostAcquireRequestState in Global.asax.cs.
            if (requestTelemetry != null && !string.IsNullOrEmpty(requestTelemetry.Context.User.Id))
            {
                // Set the user id on the Application Insights telemetry item.
                telemetry.Context.User.Id = requestTelemetry.Context.User.Id;

                // Set the session id on the Application Insights telemetry item.
                telemetry.Context.Session.Id = requestTelemetry.Context.User.Id;
            }
        }
    }
  }
…
  protected void Application_PostAcquireRequestState()
  {
      var requestTelemetry = Context.GetRequestTelemetry();
      if (HttpContext.Current.Session != null && requestTelemetry != null && string.IsNullOrEmpty(requestTelemetry.Context.User.Id))
      {
          requestTelemetry.Context.User.Id = Session.SessionID;
      }
  }
```

Also, you may try commenting default User Telemetry Initializer in ApplicationInsights.config and it will stop setting the default user IDs.
