### ISSUE TITLE
No data to AI when running Net Core in Docker container

### ISSUE THREAD

**Issue by jedjohan** [microsoft/ApplicationInsights-Home#270]
Built a simple Core 2.1 Console app sending trace to AI. Works fine (sends data to AI) when running on my computer. Built a docker image and when running the (same) app in container nothing gets through to Application Insights. Am I missing something vital ?

Core Console App:

            TelemetryConfiguration configuration = TelemetryConfiguration.Active;
            configuration.InstrumentationKey = "instrKey";
            var telemetryClient = new TelemetryClient();
            telemetryClient.TrackTrace("Hello World!");
            
            // before exit, flush the remaining data
            telemetryClient.Flush();

            // flush is not blocking so wait a bit
            Task.Delay(7000).Wait();

Dockerfile:
```
FROM microsoft/dotnet:2.1.403-sdk
WORKDIR /app
COPY *.csproj ./
RUN dotnet restore
WORKDIR /app
COPY . ./
RUN dotnet publish -c Release -o out
ENTRYPOINT ["dotnet", "out/CoreAITester.dll"]
```

**Comment by lmolkova** [comment]
> var telemetryClient = new TelemetryClient();

Please pass telemetry configuration to the client.

`var telemetryClient = new TelemetryClient(configuration);`

**Comment by jedjohan** [comment]
Well yes and thanks, but it does work, as long as I dont run it in a docker container. I tried passing configuration, same behavior.

**Comment by lmolkova** [comment]
Depending on how you configure network for your container, AppInsights endpoints might not be accessible.
Please check if you can reach these endpoints manually from inside the container: 

https://docs.microsoft.com/en-us/azure/application-insights/app-insights-ip-addresses

**Comment by jedjohan** [comment]
Pining from container (docker exec) shows that dc.services.visualstudio.com is available from running container (it doesnt answer on ping of course but container can resolve it):

`Pinging weu-breeziest-in.cloudapp.net [40.114.241.141] with 32 bytes of data:`

I updated my small test app to:

`httpClient.GetAsync("https://dc.services.visualstudio.com");`

and the response is, as expected, "Page not found"

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
