### ISSUE TITLE
Incomplete Installation of Status Monitor 

### ISSUE THREAD

**Issue by shanjp** [microsoft/ApplicationInsights-Home#273]
Hello,

I have following queries.

1. We have installed the status monitor in 2 servers and in the second one the installation is incomplete (missing SDK folder and 2.4.1 folder). We are not sure what's causing this - the server has internet access. I am attaching the diagnostics.log which is generated when opening the status monitor (it never opens actually).
[diagnostics.log](https://github.com/Microsoft/ApplicationInsights-Home/files/2484959/diagnostics.log)
![image](https://user-images.githubusercontent.com/9873114/47048275-cc4c3200-d14e-11e8-8f55-75118a2159ef.png)

2. Also is there a status monitor installation complete package which doesn't need internet during installation (our servers have restricted internet access and hence need a standalone complete install package - we will get access only to the Azure urls for posting telemetry data).

Thanks,
Shankar

**Comment by seanksullivan** [comment]
I have found that the Status Monitor does not communicate via TLS 1.2 - from looking at your log, I am guessing that your server is set to require TLS 1.2 (common nowadays).

It seems this tool is old, and not updated often; which is too bad - some of it's functionality is far better than the alternative.

**Comment by SergeyKanzhelev** [comment]
CC: @Mikhail-Pranovich @Dmitry-Matveev 

Looks like security issue that needs to be fixed

**Comment by Dmitry-Matveev** [comment]
@Mikhail-Pranovish, has this been prioritized yet, so we can put an appropriate milestone?

**Comment by Mikhail-Pranovich** [comment]
@MS-TimothyMothra who is looking at StatusMonitor vNext.

**Comment by MS-TimothyMothra** [comment]
Hello All,
I’ve just published v0.1-alpha of IISConfigurator. This is our replacement for StatusMonitor.

I’ve organized all our docs for the IISConfigurator here:  https://github.com/Microsoft/ApplicationInsights-Home/blob/master/Samples/IISConfigurator/TOC.md
This includes:
	- A Quick Start Guide
	- Detailed getting started instructions
	- API reference for the new PowerShell Module
	- A page dedicated to Troubleshooting and Known Issues


Disclaimer: This is a prototype application. We do not recommend using this on your production environments.
Please pay close attention to the known issues.
Your apps may have issues if they include any of the following DLLs in the bin directory:
	· Microsoft.ApplicationInsights.dll
	· Microsoft.AspNet.TelemetryCorrelation.dll
	· System.Diagnostics.DiagnosticSource.dll
 


I am very interested in your feedback!
Please don’t hesitate to contact me if you have any issues or comments.
Specifically,
	- I would love to hear about your experiences getting started
	- And what you would like to see moving forward

Thank you,

**Comment by MS-TimothyMothra** [comment]
Today I've released the Release Candidate for Status Monitor v2.
Because this is the replacement for the original Status Monitor, I'm going to close this issue.

Please review or documentation to get started: https://docs.microsoft.com/en-us/azure/azure-monitor/app/status-monitor-v2-overview
