### ISSUE TITLE
Include Multi-Segment Example in dev.applicationsignishts.io Metrics documentation

### ISSUE THREAD

**Issue by kylebrandt** [Microsoft/ApplicationInsights-Home#274]
When you ask the Metrics API to request more then one dimension the response nests:

```

{
  "end": "2018-10-11T17:35:00Z",
  "interval": "PT1M",
  "segments": [
    {
      "end": "2018-10-11T17:31:00Z",
      "segments": [
        {
          "operation/name": "POST /Something",
          "segments": [
            {
              "cloud/roleInstance": "aclient-web01",
              "requests/duration": {
                "avg": 20
              }
            }
          ]
        },
        {
          "operation/name": "GET /Something",
          "segments": [
            {
              "cloud/roleInstance": "aclient-web02",
              "requests/duration": {
                "avg": 0
              }
            },
            {
              "cloud/roleInstance": "aclient-web01",
              "requests/duration": {
                "avg": 0
              }
```

My default expectation is that just all the tags would be properties on the segment object that actually contains the value. Therefore I think it is worth including the multi-segment example on https://dev.applicationinsights.io/documentation/Using-the-API/Metrics

(Sorry if this is the wrong place, couldn't find the repo for that particular link).

**Comment by alexeldeib** [comment]
@kylebrandt Thanks for the feedback, I've written up a blurb for our doc site (not deployed yet) and [added an example to our swaggers](https://github.com/Azure/azure-rest-api-specs/pull/4311) (on GitHub [here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/applicationinsights/data-plane/microsoft.insights/preview/v1/AppInsights.json)).

In the future feel free to open an issue on the spec repo -- it's the starting point of integration with the whole pipeline for docs/sdks/tooling for the query pipeline. We don't have an issue page for the doc site itself; eventually much of this content will be integrated with docs.microsoft.com, and integrated with their repos (and issue tracking).
