### ISSUE TITLE
DeveloperMode true on production

### ISSUE THREAD

**Issue by SergeyKanzhelev** [microsoft/ApplicationInsights-Home#275]
Moved from https://github.com/Microsoft/ApplicationInsights-dotnet/issues/951

posted by: @bwaldron

When debugging a performance issue we noticed in AI event logging that the Service Profiler custom event is reporting the DeveloperMode is true.  We are using the default configuration installed from visual studio and not setting that propery in code.  

![image](https://user-images.githubusercontent.com/981749/47105343-7df36d80-d1f8-11e8-998c-73c14529e465.png)

I would expect this value to be false and concerned that is will be sending data immediately and not respecting production sending policies.  Our application is compiled in release mode.

## Version Info 
SDK Version : 2.7.2
.NET Version :	4.6.2						
How Application was onboarded: Visual Studio 
OS : Windows
Hosting Info (IIS/Azure WebApps/ etc) : Azure Web App

**Comment by pharring** [comment]
I created a bug in our backlog to address this. https://dev.azure.com/devdiv/DevDiv/_workitems/edit/710362 (if you have access)

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
