### ISSUE TITLE
Can't tell when flush is complete

### ISSUE THREAD

**Issue by breyed** [Microsoft/ApplicationInsights-Home#276]
`TelemetryClient.Flush` performs is an async void method. It performs the flush in the background, without reporting when the flush completes. The [documented workaround](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-custom-events-metrics#flushing-data) is to "wait and hope" via a delay.

It would be faster and more reliable if `Flush` returned `Task`, so that the app would not need to wait as long, or fail to get the data if it didn't wait long enough.

**Comment by Dmitry-Matveev** [comment]
@breyed, there are couple issues opened about non-blocking Flush:
- [#407](https://github.com/Microsoft/ApplicationInsights-dotnet/issues/407)
- [#482](https://github.com/Microsoft/ApplicationInsights-dotnet/issues/482)

I can suggest a workaround of using InMemoryTelemetryChannel that would connect to AI endpoint when the associated TelemetryClient is flushing. As per my understanding, the initial implementation of ServerTelemetryChannel as PersistentChannel would flush synchronously to local storage to make sure data is saved but not that data is sent immediately. Some remains of this are still present in the product and hence the bugs above.

Alternatively, you can leverage [custom channel](http://apmtips.com/blog/2016/11/10/sync-channel/) that would flush as per your app requirements.

**Comment by SergeyKanzhelev** [comment]
Closing as we already tracking this item
