### ISSUE TITLE
How long does the data would be deleted after use the purge api

### ISSUE THREAD

**Issue by imeya** [microsoft/ApplicationInsights-Home#279]
I followed this [link](https://docs.microsoft.com/en-us/rest/api/application-insights/components/purge), and try to delete the trace data in application insights, and it executes successfully(return 202).

When I try to select the trace data in azure portal -> application insights -> search, I still can see the trace data. So I want to know how long until the data deleted after the above execution?

I also found an answer in stackoverflow, it said it would take 1 or 2 days, but no official link.

**Comment by SergeyKanzhelev** [comment]
According to [this](https://docs.microsoft.com/azure/log-analytics/log-analytics-personal-data-mgmt)

> While the vast majority of purge operations may complete much quicker than the SLA, due to their heavy impact on the data platform used by Application Insights, the formal SLA for the completion of purge operations is set at 30 days.

![image](https://user-images.githubusercontent.com/9950081/48014918-95799400-e0dc-11e8-980b-1dd2b2f93bd7.png)

**Comment by marcelriegr** [comment]
Why would it take up to 30 days just to delete some data that's not even 500 KB big?

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
