### ISSUE TITLE
Loss of dependency and performance counter telemetry

### ISSUE THREAD

**Issue by gregjhogan** [Microsoft/ApplicationInsights-Home#28]
Sometimes our on-prem IIS servers stop sending dependency and performance counter telemetry.  We have the status monitor installed, and re-installing the status monitor resolves the issue.  SCOM is being used, and I came across the below article which seems to accurately describe what I am seeing since AI uses the same registry settings.
https://docs.newrelic.com/docs/agents/net-agent/troubleshooting/resolve-net-scom-conflicts

**Comment by SergeyKanzhelev** [comment]
What version of SCOM agent do you use? Latest versions of it knows about Status Monitor. In fact - with the latest OMS agent (that is basically the most updated version of SCOM Agent) you do not need Status Monitor to collect dependencies at all.

**Comment by gregjhogan** [comment]
@SergeyKanzhelev it is 2012 R2, can you tell me what version I need to get to so that it doesn't remove the Environment registry key?

**Comment by gregjhogan** [comment]
@SergeyKanzhelev if I update to [System Center 2012 R2 Update Rollup 8](https://support.microsoft.com/en-us/kb/3096378) will it stop clearing out the Environment registry setting? Thanks!

**Comment by SergeyKanzhelev** [comment]
This side by side support was implemented in the next version of MMA - [2016 technical preview](https://www.microsoft.com/en-us/evalcenter/evaluate-system-center-technical-preview). 

Alternatively you can use agents from Operational Insights. 

- [64-bit windows](https://go.microsoft.com/fwlink/?LinkID=517476)
- [32-bit windows](https://go.microsoft.com/fwlink/?LinkID=615592)

**Comment by gregjhogan** [comment]
@SergeyKanzhelev we probably don't want to run a technical preview version in produciton, are you saying that no version of System Center 2012 R2 will solve this problem?

RE: Operational Insights, are you saying that just installing it will set things up for app insights (even if I don't use operational insights) and then the System Center 2012 R2 agent won't come through and remove the configuration?

Thanks!

**Comment by SergeyKanzhelev** [comment]
Operational Insights agent is back compatible with SCOM 2012 R2. I'm not sure about cadence of releases and whether they picked up UR9 fixes. 

Anyway, using Operational Insights agent will set everything up for Application Insights and will not compete with Status Monitor for registry keys.

**Comment by SergeyKanzhelev** [comment]
Closing for now. Let us know if you had a chance to play with Operational Insights' agent and it worked for you.
