### ISSUE TITLE
How to update ApplicationInsights via nuget package manager console

### ISSUE THREAD

**Issue by phatcher** [microsoft/ApplicationInsights-Home#280]
I'm finding it difficult to update a project's AI version each month due to the tight dependency coupling between the versions.  The instruction on the [documentation](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-asp-net#upgrade-to-future-sdk-versions) suggests updating Microsoft.ApplicationInsights.Web but if I issue that as a command I get...
```
NU1605: Detected package downgrade: Microsoft.ApplicationInsights from 2.8.1 to 2.7.2. Reference the package directly from the project to select a different version. 
 MyApp.Api -> Microsoft.ApplicationInsights.Log4NetAppender 2.8.1 -> Microsoft.ApplicationInsights (>= 2.8.1) 
 MyApp..Api -> Microsoft.ApplicationInsights (>= 2.7.2)
NU1605: Detected package downgrade: Microsoft.ApplicationInsights from 2.8.1 to 2.7.2. Reference the package directly from the project to select a different version. 
 MyApp..Api -> Microsoft.ApplicationInsights.Web 2.8.1 -> Microsoft.ApplicationInsights (= 2.8.1) 
 MyApp..Api -> Microsoft.ApplicationInsights (>= 2.7.2)
NU1605: Detected package downgrade: Microsoft.ApplicationInsights.WindowsServer from 2.8.1 to 2.7.2. Reference the package directly from the project to select a different version. 
 MyApp.Api -> Microsoft.ApplicationInsights.Web 2.8.1 -> Microsoft.ApplicationInsights.WindowsServer (>= 2.8.1) 
 MyApp.Api -> Microsoft.ApplicationInsights.WindowsServer (>= 2.7.2)
NU1605: Detected package downgrade: Microsoft.AspNet.TelemetryCorrelation from 1.0.4 to 1.0.3. Reference the package directly from the project to select a different version. 
 MyApp.Api -> Microsoft.ApplicationInsights.Web 2.8.1 -> Microsoft.AspNet.TelemetryCorrelation (>= 1.0.4) 
 MyApp.Api -> Microsoft.AspNet.TelemetryCorrelation (>= 1.0.3)
```
 I can't find a sequence of commands that allows me to update the packages and I prefer to be able to use a command rather than the VS UI so that we can automate this as part of our devops process.

I know this is basically a nuget issue but this is exacerbated by the tight coupling between the components, i.e. all the components are require exact version matches.

Could you..

1. Relax the version constraints slightly
2. Document the order in which components can be updated

**Comment by SergeyKanzhelev** [comment]
@karann-msft, @jainaashish another question for you. Here is a situation - we have two packages `B1` references `A1`, `C1` references `A1`.

Now we releasing versions `B2->A2` and `C2->A2`. So all packages needs to be updated in a single command.

Is there a command like this?

**Comment by karann-msft** [comment]
I belive the op is right, there shouldn't be such tight coupling or ship it as a single nuget package.

**Comment by SergeyKanzhelev** [comment]
@karann-msft do you mean that it is incorrect to ship an update to package A and have new versions of B and C depending on that update?

**Comment by karann-msft** [comment]
Clearly this over simplified example is not helpful.

What are the steps to repro what the op is experiencing?

**Comment by SergeyKanzhelev** [comment]
@phatcher did you install `Log4NetAppender` explicitly or it was added automatically?

**Comment by SergeyKanzhelev** [comment]
@phatcher I failed to repro trying different versions. Can you please give VS version, NuGet extension version installed there and steps to repro.

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
