### ISSUE TITLE
AI .Net SDK 2.8.1 breaks Application Insights Profiler

### ISSUE THREAD

**Issue by juliusl** [Microsoft/ApplicationInsights-Home#283]
The latest AI .NET SDK 2.8.1 (available on nuget) breaks profiler ability to receive rich payload events from the emitting application.

The issue is that one of the internal payload data type has changed from string to long. This is a link to the PR which has caused this issue: https://github.com/Microsoft/ApplicationInsights-dotnet/pull/928

Filing this issue for tracking and notice purposes. We will be making a fix on our side and updating this issue with our progress. 

For now the workaround is to drop to a lower version of the AI SDK.

**Comment by ojasp** [comment]
Hi Julius, 
Do you have a timeline for the fix? We'll downgrade the version to 2.7.2 unless the fix is around the corner.
Thanks,
Ojas

**Comment by juliusl** [comment]
Hey @ojasp, 

I was actually going to send an update today! So I just double checked and confirmed that the roll-out of our agent with the fix for AI SDK 2.8.1 has completed in App Services. I also tested my repro app and saw that it could see activities with the 2.8.1 SDK installed.

If you update your app service with the latest extension from our tool in the portal (Settings/Application Insights) there should be a button for you to update. You should then be able to update your SDK to 2.8.1 and deploy your app.

Thanks for your patience!

**Comment by ojasp** [comment]
Thanks Julius! 2.8.1 nuget package was last updated a month ago, is the fix a part of 2.9.0-beta2 nuget package?

**Comment by juliusl** [comment]
The fix isn't a part of the AI SDK. The change that broke us was a significant performance improvement so we didn't want that reverted. Instead we opted to fix it from our side which means that it's fixed at the agent level, so 2.8.1 should work with our latest extension.

**Comment by ojasp** [comment]
Just confirmed that we are able to run profiler with 2.8.0. Thanks guys.

**Comment by joshuapetryk** [comment]
Hi - this is still an open issue for Azure Cloud Services, as it looks like the diagnostic extension doesn't have the fix. Is this being tracked elsewhere?

**Comment by juliusl** [comment]
@joshuapetryk Sorry for the late reply. Yes we have this fix in WAD and we're waiting for the WAD team to deploy our changes. I'll give you an update as soon as I find out progress on that.
