### ISSUE TITLE
timestamp from server instead of SDK

### ISSUE THREAD

**Issue by vpnchoudhary** [microsoft/ApplicationInsights-Home#291]
Is there a way to get timestamp from AI server instead of client ?

**Comment by cijothomas** [comment]
Can you elaborate the qn a bit more? The timestamp for telemetry items are from the server it is collected, and has nothing to do with AI backend server to which items are sent. And i dont think there is any way to know when exactly did ai receive it.

**Comment by vpnchoudhary** [comment]
machine time is off on some of our client where we are collecting telemetry. Wondering if we could use server time instead.

**Comment by cijothomas** [comment]
@Dmitry-Matveev Do you know if sdk leaves timestamp blank, does AI ingestion stamps the receivedtime as the timestamp?

**Comment by Dmitry-Matveev** [comment]
As far as I can tell, the processing pipeline uses client time to identify whether it should ingest the item or drop it because it's couple days old, so I'd think it won't accept an item without time at all and will simply drop it.

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
