### ISSUE TITLE
Does AI truncates Property value if it exceeds limit ?

### ISSUE THREAD

**Issue by vpnchoudhary** [Microsoft/ApplicationInsights-Home#292]
Does AI SDK or server truncates Property value if it exceeds limit ? Does it take care of keeping json/xml format intact after truncation?

**Comment by cijothomas** [comment]
Yes, property values are trimmed off if exceeding limit.
As per docs, https://github.com/Microsoft/ApplicationInsights-Home/tree/master/EndpointSpecs/Schemas/Docs

Max key length: 150
Max value length: 8192

SDK does not do anything other than trimming - if the value was some json/xml it may be broken.

(You can written own TelemetryInitializers/Processors to do the trimming yourself keeping any relevant formats intact)
