### ISSUE TITLE
Update ReadMe to point to App Center SDK instead of HockeySDK

### ISSUE THREAD

**Issue by elamalani** [microsoft/ApplicationInsights-Home#293]
Hello,

I'm a PM in App Center team owning both HockeySDK and App Center SDK. App Center is the next generation of HockeyApp. Can you please update the deprecated section in the ReadMe file and point it to [App Center SDK ](https://docs.microsoft.com/en-us/appcenter/sdk/)instead of HockeySDK?

Thanks!

**Comment by SergeyKanzhelev** [comment]
@elamalani please review https://github.com/Microsoft/ApplicationInsights-Home/pull/323

Also do you think it's time to hide those repositories? Does anybody still need those sources in the open?

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
