### ISSUE TITLE
Question: Disable sampling when creatin TelematryClient object

### ISSUE THREAD

**Issue by stridsbr** [microsoft/ApplicationInsights-Home#296]
I use application insights for my tracelogging in .net framework. But the logs are sampled.
This is how I create the client:
```csharp
var client = new TelemetryClient()
            {
                InstrumentationKey = _instrumentationKey
            };
```
How can I modify this code so it dont get sampled?
Or that Trace and exception logs won't get sampled?

I use TelematryClient from a common logging library. I prefere to use that class so I don't have to rewrite all the code that referense that library.

**Comment by cijothomas** [comment]
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-sampling#alternative-configure-adaptive-sampling-in-code

**Comment by stridsbr** [comment]
So the telematryClient object inside that UseAdaptiveSampling callback is created as I wrote but after the last line in that sample?

The TelemetryConfiguration.Active.TelemetryProcessorChainBuilder builds the default configuration for any new TelematryClient object created with the empty constructor?

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
