### ISSUE TITLE
If the location of app insights is far away from the app service, does it will result in some performance issue?

### ISSUE THREAD

**Issue by imeya** [microsoft/ApplicationInsights-Home#299]
When create an app insights, if I select a location which is far away from the app service, ie. location for app insights is at East US, and the app service is at Southeast Asia. 

In this situation, does it will result in some performance issue? and any documents about it?

thanks.

**Comment by cijothomas** [comment]
Application insights sends data to their backend asynchornously - so the actual network RT time should not matter.

Also, even though the app insights is in East US, the 'ingest' endpoints are globally distributed, and telemetry is always sent to the nearest available 'ingest' point.

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
