### ISSUE TITLE
Full .NET SDK is not available

### ISSUE THREAD

**Issue by advancedrei** [Microsoft/ApplicationInsights-Home#3]
I would like to make some contributions to the core SDKs, but they are not available on here yet. Is there an ETA for when the source for the existing NuGet packages for .NET will be available? Thanks!

**Comment by JakubOleksy** [comment]
We have it on the backlog, but don't have a firm date yet. 

What contributions are you considering?

**Comment by raymens** [comment]
Does that backlog for releasing the source code include the current ASP.NET Web Application package?

**Comment by JakubOleksy** [comment]
Yes, our intention is to have all our SDKs fully public.

**Comment by bondarenkod** [comment]
https://github.com/Microsoft?utf8=%E2%9C%93&query=ApplicationInsights
OSX (!!!), CPP(!!!!!!)? 
Where is SDK for MS *native* platform - Windows Phone?

**Comment by JakubOleksy** [comment]
Yes, we are actively working on this. Our .Net SDK was the first one we worked on and at the time weren't thinking about making it open source, so it is lagging behind as we get the code-base ready to publish. Stay tuned.

**Comment by raymens** [comment]
Any update on this?

**Comment by JakubOleksy** [comment]
Yes, sorry, forgot to update here. We've made it open source:
https://github.com/Microsoft/ApplicationInsights-dotnet

**Comment by advancedrei** [comment]
I would like this re-opened, because this is not the full SDK. The WindowsServer bits are still not open-source, and that is arguably the most important part.

**Comment by JakubOleksy** [comment]
We are working on some changes on the Windows SDK and felt it would not be appropriate to make it public at this time. When the new one is ready, we will make it public.
