### ISSUE TITLE
I can't use the persistence channel with App Insights 2.0.0-beta4

### ISSUE THREAD

**Issue by dbohls** [Microsoft/ApplicationInsights-Home#30]
The latest persistence channel is version 2.0.0-beta3. I just using App Insights Core 2.0.0-beta4 but I don't think that would matter. I get System.MethodAccessException somewhere down in the constructor for the persistence channel.

**Comment by SergeyKanzhelev** [comment]
Please see http://apmtips.com/blog/2016/01/31/telemetry-channels-update/

@Izikl and @JoshuaWeber on the plans of migration

**Comment by dbohls** [comment]
Thanks for that link. I left a comment on that blog post, which I'm concerned may not be monitored for responses. One thing I like about the persistence channel is that I didn't have to insert some arbitrarily long thread.sleep to ensure no telemetry is lost. I tested the server telemetry channel with calling flush on app close, and found that some events never showed up in the azure portal. I poked around the server channel source and the transmitter is commented as being synchronous but it looks to me as though it is asynchronous similarly to the in-memory channel. I'd really like to see a channel that tries to send telemetry but persists if it can't and ensures no telemetry is lost.

**Comment by SergeyKanzhelev** [comment]
Replied =) So you decided to go with server telemetry channel in your WPF application? You are right - it's not quite designed for desktop scenarios, but might work for you. 

What kind of telemetry are you using from your application? 

CC: @ashtom

**Comment by dbohls** [comment]
I evaluated the server telemetry channel, but decided not to use it because of the lost events near shutdown.

For now, I've downgraded to 2.0.0-beta3 and when back to using the persistence channel. We just have a WPF desktop app, and we have some events at startup and some events on shutdown, and a few other events that are UI driven so we can know what parts of our app are getting used. Sometimes our app will be used used without an internet connection available so we need persistence when that happens. Which channel should I be using? The persistence channel seems like it was best for us, but it has been deprecated, right?

**Comment by izikl** [comment]
For a WPF application I would recommend using:
1. https://www.nuget.org/packages/Microsoft.ApplicationInsights/1.2.3
2. https://www.nuget.org/packages/Microsoft.ApplicationInsights.PersistenceChannel/1.2.3

Non of these NuGets is deprecated. 

when using the Persistene Channel calling flush will save telemetry to disk, so next time the app is opened it will send the telelmetry.

**Comment by rbarcelos** [comment]
Hi,

I am trying to update to the latest version of the AppInsights nuget and I am hitting also the MethodAccessException:

System.MethodAccessException was unhandled
Message: An unhandled exception of type 'System.MethodAccessException' occurred in Microsoft.WindowsAzure.ServiceRuntime.dll
Additional information: Attempt by method 'Microsoft.ApplicationInsights.Channel.PersistenceChannel..ctor(System.String, Int32)' to access method 'Microsoft.ApplicationInsights.Channel.TelemetryBuffer..ctor()' failed.

Any ideas what I am missing?

Thanks

**Comment by SergeyKanzhelev** [comment]
Please see https://github.com/Microsoft/ApplicationInsights-dotnet/issues/210 There will be a separate mitigation plan on how to migrate to Hockey App SDK. Keep the latest 1.X version of Application Insights for now

**Comment by rbarcelos** [comment]
Thanks for the heads up, however I am getting this when updating the AppInisghts on my service and not the mobile app

**Comment by SergeyKanzhelev** [comment]
Please switch to this channel: https://www.nuget.org/packages/Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel/ It is more suitable for Azure  Web Services and was updated to 2.0 when persistence channel will be transitioned to Hockey App SDK as all devices soon.

More about telemetry channels difference: http://apmtips.com/blog/2015/09/03/more-telemetry-channels/

**Comment by Laibalion** [comment]
I know it's an old tread, but Hockey App SDK is not suited for Win32 desktop applications as there is no way to integrate with any of the SDK's (we've tried).

Hockey App only allows limited number of 'event types', which is hugely lacking for large (+1M loc) applications.

We didn't have any other option than to go with version 1.2.3 of both the Insights SDK and PersistenceChannel.

**Comment by SergeyKanzhelev** [comment]
CC: @JakubOleksy, @Redwing1010 

@Laibalion persistent channel was designed for desktop apps which can go offline often and may have short lifespan - opens and closes often without background CPU allowance. If your win32 app has this reuqirements - you'd need to implement persistent channel yourself. If an app is often online and can send events in background you can use standard Application Insights channel. You can also do something like this: http://apmtips.com/blog/2016/11/10/sync-channel/. This article is not 100% up to date - channel cannot throw exception out of `TrackFoo` method any longer, but the idea is the same.

**Comment by Laibalion** [comment]
The scenarios you indicate are suitable for the persistance channel is exactly what the op asked for. You suggested HockeyApp as an alternative, but ita hugely lacking in integration capabilities in win32 desktop applications.
So as others in this thread already mentioned sticking to 1.2.3 sdk with the 1.2.3 persistance channel is the easiest road to walk. And its exactly what we are using in our MFC application (via c++/cli and nuget).

**Comment by RodrigoGroener** [comment]
> can i get the code for using persistance channel in wpf application @dbohls @SergeyKanzhelev

i think you can find it here https://github.com/Microsoft/ApplicationInsights-dotnet/blob/1648ecd5bf32cc151557d15cbb0886cb86e84270/src/TelemetryChannels/PersistenceChannel/Shared/PersistenceChannel.cs#L53
