### ISSUE TITLE
How to use ISupportProperties in a custom TelemetryInitializer

### ISSUE THREAD

**Issue by imeya** [Microsoft/ApplicationInsights-Home#300]
When write a custom App insights telemetry initializer, there is a compiler warning, saying that Context.Properties is obsolete, and recommend us to use ISupportProperties.

Regarding ISupportProperties, the only way I find we can use is to cast the ITelemetry to ISupportProperties, like below:

```
public void Initialize(ITelemetry telemetry)
     {
          //cast ITelemetry to ISupportProperties
          ISupportProperties propTelemetry = (ISupportProperties)telemetry;

          if (!propTelemetry.Properties.ContainsKey("isuport_key"))
          {
              propTelemetry.Properties.Add("isuport_key", "isupport_value");
          }

      }
```

So my question is, without the explicitly cast, is there any way we can use it(not the cast way)?

**Comment by cijothomas** [comment]
Yes you need to cast ITelemetry to ISupportProperties.

**Comment by imeya** [comment]
@cijothomas , no other ways?

**Comment by cijothomas** [comment]
No. The other alternate to avoid cast is to use telemetry.Context.GlobalProperties. (GlobalProperties are simply copied to Properties during serialization now) - but this is not recommended as its meant for different purpose, and the behaviour of GlobalProperties being automatically copied to Properties might change)

**Comment by imeya** [comment]
thank you very much!
