### ISSUE TITLE
Application Insights Status Monitor Instrumentation Breaks App

### ISSUE THREAD

**Issue by isaac2004** [microsoft/ApplicationInsights-Home#301]
I have a .NET Framework 4.6.1 Project without AI instrumented deployed to IIS. If I run the Instrumentation tool, loading the app results in this exception

> Could not load file or assembly 'System.Diagnostics.DiagnosticSource' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) 

What is happening is that the version referenced in the injected section of web.config is wrong.

Web.config snippet

```
<dependentAssembly>
    <assemblyIdentity name="System.Diagnostics.DiagnosticSource" publicKeyToken="cc7b13ffcd2ddd51"/>
    <bindingRedirect oldVersion="0.0.0.0-4.0.2.1" newVersion="4.0.2.1"/>
</dependentAssembly>
```
And referenced DLL installed in bin
![image](https://user-images.githubusercontent.com/8878502/49031749-dcf1be00-f178-11e8-8469-0219e9c97c82.png)

The issue is that the newest version of the DLL is [4.5.1](https://www.nuget.org/packages/System.Diagnostics.DiagnosticSource/). Updating the config resolves this issue

**Comment by MS-TimothyMothra** [comment]
Thanks for reporting.
Yes, the SDK updated the dependency on DiagnosticSource and StatusMonitor needs the same update.

**Comment by isaac2004** [comment]
@MS-TimothyMothra any idea when published version will have this fix?

**Comment by MS-TimothyMothra** [comment]
@isaac2004 Sorry, but I don't have a date to share. We're targeting Q1 2019.
We want to have a private preview available in January. Would you be interested in testing that and providing feedback?

**Comment by isaac2004** [comment]
Sure, feel free to message me internally

**Comment by isaac2004** [comment]
@MS-TimothyMothra update?

**Comment by MS-TimothyMothra** [comment]
Today I've released the Release Candidate for Status Monitor v2.
Because this is the replacement for the original Status Monitor, I'm going to close this issue.

Please review or documentation to get started: https://docs.microsoft.com/en-us/azure/azure-monitor/app/status-monitor-v2-overview
