### ISSUE TITLE
Orchard CMS may fail when extension is installed

### ISSUE THREAD

**Issue by SergeyKanzhelev** [microsoft/ApplicationInsights-Home#302]
Long time ago there were reports that Orchard CMS will not work when Azure Web Site extension is enabled. The root cause was an incompatible versions of Application Insights SDK used by application and by extension. Since Orchard CMS loaded application Insights dependencies from `App_Data/Dependencies`, not from the `bin` folder and loaded them lazily - quite late in process initialization pipeline, extension were failing to initialize it.

Publishing this issue now for tracking and testing purposes.

**Comment by MS-TimothyMothra** [comment]
Do we know how common is this lazy load strategy?
I don't know that this is something we could detect, and may not be able to support.

What are your thoughts?

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
