### ISSUE TITLE
SQL Dependency result code is “-2”

### ISSUE THREAD

**Issue by imeya** [Microsoft/ApplicationInsights-Home#304]
The original post is [here](https://stackoverflow.com/questions/53515728/application-insights-sql-dependency-result-code-2).

The customer encounters one strange thing, the sql dependency result code is -2, refer to screenshot below:

![sql-dependency](https://user-images.githubusercontent.com/25738099/49204835-17ad5d80-f3e8-11e8-9f9e-62ab6c2ea14d.JPG)

it's registered under dependencies and not exceptions. what does this result code "-2"
 means?

**Comment by lmolkova** [comment]
which ApplicaitonInsights SDK do you use (.NET, .NET Core, Java, Node.js) and which version?
Can you check SDK version on the telemetry properties (click 'show all') and paste it here?

Thanks!

**Comment by lmolkova** [comment]
If you are using .NET, this is Sql Exception number:

https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/cc645611%28v%3dsql.105%29


-2 |   |   | Timeout expired. The timeout period elapsed prior to completion of the operation or the server is not responding. (Microsoft SQL Server, Error: -2).
-- | -- | -- | --

**Comment by ToyMakerGR** [comment]
@lmolkova OP here. AI SDK: rddf:2.7.2-19477, .NET Core version.
What does the .NET version / SDK have to do with this SQL-specific result code? Wouldn't it be the same regardless?

**Comment by cijothomas** [comment]
https://github.com/Microsoft/ApplicationInsights-Home/blob/master/EndpointSpecs/SDK-VERSIONS.md
the version prefix indicates the sdk mechanism used to collect the dependency, and it can affect result code collected.
