### ISSUE TITLE
Can we get the raw data from the application map?

### ISSUE THREAD

**Issue by imeya** [microsoft/ApplicationInsights-Home#305]
we got lot of environments and sometimes it is hard to view the application map every time to find the end point and details. **if in a way I can get json extract** , I can write some smarts to view it in regular basis. The thing our environment connects with various backends and source. it may change on request. it is time consuming to lookup in Azure .

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
