### ISSUE TITLE
Please reconsider marketing-driven sentence in README

### ISSUE THREAD

**Issue by RobertoPrevato** [microsoft/ApplicationInsights-Home#307]
This sentence in the README: __"Community Supported SDKs. These SDKs are not recommended for production applications."__ is subjective and should be elaborated. In my opinion it would be best to just remove it. A REST api is just a REST api: it doesn't matter how you generate web requests to log data inside Application Insights. Why community supported SDKs should be avoided for production applications? Don't we have examples of community driven libraries that were done better than official Microsoft libraries and eventually were adopted by MS itself, (see Newtonsoft.JSON, XUnit or NUnit vs Microsoft.Test); and many community-driven libraries and frameworks that are used in production systems for .NET (AutoMapper, MediatR, Serilog, NLog, many implementations of dependency injection). That sentence looks anachronistic, thinking of what Microsoft is today. It is marketing-driven: not supported by facts.

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
