### ISSUE TITLE
application insights SLA

### ISSUE THREAD

**Issue by imeya** [microsoft/ApplicationInsights-Home#308]
I noticed that in application insights SLA [V1.0](https://azure.microsoft.com/en-us/support/legal/sla/application-insights/v1_0/) and [v1.1](https://azure.microsoft.com/en-us/support/legal/sla/application-insights/v1_1/), it says **We guarantee that the data latency of the Application Insights Service will not exceed two hours 99.9% of the time.** , so in the left 0.01% of time outside the SLA, could the the data (send by trackTrace() or trackEvent() etc.) would be losted? or definitely sent to application insights (2 hours later)?

And in the latest version [v1.2](https://azure.microsoft.com/en-us/support/legal/sla/application-insights/v1_2/), it changes the Data latency SLA to Query availability SLA, what is the difference between the change?

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
