### ISSUE TITLE
Huge Block Time in Profiler in Azure App Service Response

### ISSUE THREAD

**Issue by imeya** [microsoft/ApplicationInsights-Home#309]
The original post is [here](https://stackoverflow.com/questions/53630529/huge-block-time-in-profiler-in-azure-app-service-response).

The customer encounters an issue: From the past few days, he is Getting Huge Block Time when seen in the profiler, so he wonders why there is so much block Time in request processing?

A screenshot as below:

![hugetimeblock](https://user-images.githubusercontent.com/25738099/49639372-c9323b80-fa45-11e8-9887-775d307b262b.JPG)

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
