### ISSUE TITLE
Is it possible to convert the query results(from the anylytic api) to c# object, like datatable or any other object?

### ISSUE THREAD

**Issue by imeya** [microsoft/ApplicationInsights-Home#316]
When using the application insights analytics [api](https://dev.applicationinsights.io/) to fetch the results, like the results of CustomEvents. 

The return value is a json string, and contains some dynamic value(in CustomDemesion node), so is there a way to convert sunc json to c# object? like datatable or some other object? 

Thanks.

**Comment by SergeyKanzhelev** [comment]
@pdrayton are you aware of any ORM-like frameworks for Analytics data?

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
