### ISSUE TITLE
SnapShot Collector - Angularjs

### ISSUE THREAD

**Issue by saravana13** [Microsoft/ApplicationInsights-Home#317]
Is Snapshot collector available for angularjs. If no , is there a way to collector the  snapshot in angularjs apps?

**Comment by SergeyKanzhelev** [comment]
Snapshot Collector is working for server side code today, not for the client side. So you can capture server exception caused by angularjs app in a backend (i.e. passing invalid arguments), but not the client side code that led to the problem.

CC: @pharring

**Comment by pharring** [comment]
That's correct. SnapshotCollector is for .NET only.

**Comment by SergeyKanzhelev** [comment]
@saravana13 please re-open the issue if you have more questions or suggestions
