### ISSUE TITLE
Telemetry keeps disappearing from search in Azure Portal

### ISSUE THREAD

**Issue by rudfoss** [microsoft/ApplicationInsights-Home#319]
I'm testing out basic logging of events and exceptions in a simple nodejs application (using express). I'm trying to use trackException and trackTrace to log errors and general log messages and view the messages in the Search panel of the Azure Portal.

My assumption was that I would be able to view all my exceptions including correlated trace events in the portal after a short delay. I set up a simple application with two endpoints. One that when called throws an error using express built in `next()` function

```
next(new Error("error"))
```

And another that uses:
```
client.trackException({
    exception: new Error("error")
})
```

Both of the enpdoints also log something using `trackTrace` that I was hoping to correlate with the exception itself.

However when I try to refresh the search in the portal it only shows my exceptions perhaps every 100th time. I am not doing anything with the filters or time range and only hitting refresh, but it seems to suddenly drop the exceptions from the data set.

Here is a short gif of what's happening. I've been sitting refreshing almost continuously for a few minutes and suddenly my exceptions appear. Then I hit refresh once more and they are gone.
![disappearing-exceptions-azure-portal](https://user-images.githubusercontent.com/1716298/51539253-d4092a00-1e53-11e9-9847-d39c1a137bed.gif)

I'm using:
node v10.13.0
applicationinsights 1.0.8
express 4.16.4

**Comment by MS-TimothyMothra** [comment]
@zakimaksyutov can you help with the UX?

**Comment by zakimaksyutov** [comment]
@rudfoss, do you still experience this issue?

**Comment by rudfoss** [comment]
@zakimaksyutov I left it alone for a while and tried again with a new instance of Appinsights. It has so far seemed to work fine. I've not had any more disappearing exceptions as far as I can tell. Any idea what might have been the cause?

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
