### ISSUE TITLE
AppInsights site extension for AppService logs only "GET /" requests but no others

### ISSUE THREAD

**Issue by tknerr** [Microsoft/ApplicationInsights-Home#320]
We are using the "Application Insights site extension" for our App Services. However, we noticed that the request logging is incomplete in a sense that only "GET /" requests are logged in appInsights, but no other requests.

Any other requests not being the root resource (e.g. "GET /index.html", "GET /some/file.json", etc...) are not appearing at all in appInsights.

What we deploy to the AppService is a simple, client-side only .html website via zip push deployment.

In Azure Portal it looks like that (note that the site extension is enabled, but everything else is left at the defaults): 

![image](https://user-images.githubusercontent.com/365744/51784827-29dd1b00-214f-11e9-8c29-39e98f409447.png)
 
In the "Application Settings" we specified both the `APPINSIGHTS_INSTRUMENTATIONKEY = <our key>` and `ApplicationInsightsAgent_EXTENSION_VERSION = ~2`:

![image](https://user-images.githubusercontent.com/365744/51784853-8a6c5800-214f-11e9-89ab-03564d9750e1.png)

What we see in AppInsights though is only the requests targeted at the root URL (i.e. "/"), all other requests (such as "GET /some/image.jpg" or "GET /config.json" etc) will not appear at all:

![image](https://user-images.githubusercontent.com/365744/51784892-357d1180-2150-11e9-81bd-b939c519979f.png)

One thing I noticed that is probably related is that all request are processed by a "metric extractor" which in this case seems to be `(Name:'Requests', Ver:'1.1')`

![image](https://user-images.githubusercontent.com/365744/51784914-81c85180-2150-11e9-96a9-d5a2f1cf07b8.png)

Is there any way to enable complete request logging with the AppInsights site extension for App Services?

**Comment by cijothomas** [comment]
"What we deploy to the AppService is a simple, client-side only .html website via zip push deployment."

So is your application not a Asp.net application?

**Comment by tknerr** [comment]
Hi @cijothomas,

no, indeed it's not. Our backend runs in Service Fabric, and only the Frontend SPA (single page application) runs within the App Service -- so since there is no server side backend code involved, only client-side javascript, I simplified it to a "client-side only .html website"

The Application Insights site extension still adds request logging, but as described only for requests hitting "/", not for all the others

**Comment by cijothomas** [comment]
I am wondering what SDK is logging the 'Requests' you are seeing.. Can you check the SDK version in the 'requests' ?

**Comment by tknerr** [comment]
Hi @cijothomas ,

yes sure, the skdVersion is `ar_web:2.9.0-3904`

Full request details here:

![image](https://user-images.githubusercontent.com/365744/51970550-7ee29f00-2477-11e9-8985-e29dd3b0c091.png)

**Comment by cijothomas** [comment]
@tknerr Not sure whats going on here. 'ar_web' doesn't look like standard .net sdk, but i do see metricextractor, which is only part of .net sdk.... @SergeyKanzhelev can you help ?

**Comment by tknerr** [comment]
@SergeyKanzhelev any feedback on this so far?

**Comment by tknerr** [comment]
bump (being desperate :-/)

**Comment by Dmitry-Matveev** [comment]
@tknerr, if web app is mainly client-side based app with no .NET Managed processing on the server side, then with the default settings AI won't detect anything beyond root calls into the app that may go through the managed handler. (AI SDK is mostly managed code instrumentation and static files do not go through that pipeline for a reason).

However, for the servers where you have access to the web server settings the workaround might be to set "Use Managed Handler for all requests" setting in IIS Web Server or alike. This will force all file requests to go through managed pipeline as well (essentially making them slower for the amount of milliseconds necessary for Managed pipeline invocation) and managed tools such as AI SDK for .NET will see them. I think it can be doable for App Service as well (e.g. with ApplicationHost or Web.config transformation).

**Comment by tknerr** [comment]
Hi @Dmitry-Matveev, thanks for the clue!

I'm still tapping in the dark, but I guess you mean this setting exposed in Azure Portal GUI?

![image](https://user-images.githubusercontent.com/365744/53265489-ae837080-36de-11e9-9eb0-9e8027fafb74.png)

Otherwise, any more clues on the concrete setting name in Web.config?

Will dig deeper in the meantime...

**Comment by tknerr** [comment]
Ok, I guess I found it here: https://serverfault.com/a/610203

```xml
<system.webServer>
  <modules runAllManagedModulesForAllRequests="true">
  ...
  </modules>
  ...
</system.webServer>
```

That looks promising indeed. I will give it a spin and report back here if it's working or not...

**Comment by tknerr** [comment]
This seems to work as expected now, i.e. we get all the requests properly logged now:

![image](https://user-images.githubusercontent.com/365744/53269227-a03a5200-36e8-11e9-9f14-83067f6dd1f7.png)

Thanks a lot @Dmitry-Matveev for pointing out the final clue! 👍 

(I owe you a 🍻for that :))

**Comment by Dmitry-Matveev** [comment]
@tknerr , you are welcome! Glad it helped.
