### ISSUE TITLE
Is it possible to target multiple AI instances?

### ISSUE THREAD

**Issue by jacobslusser** [Microsoft/ApplicationInsights-Home#322]
Is there a supported way of specifying more than one instrumentation key and thus target multiple instances of Application Insights? If not, could this feature be added?

Cheers.

**Comment by cijothomas** [comment]
You can use multiple TelemetryClients, each with different ikeys, and make 2 Track() calls, one each on the clients.

Or is your use case more like 
`var tc = new TelemetryClient(ikey1,ikey2); tc.Track() `
and you want exact same telemetry to goto both ikey1 ikey2?

The latter is not quite supported. There is a concept of 'TelemetrySinks' which can be configured to broadcast data to multiple places. We dont have official docs on it yet though, but i can point to some samples codes....

**Comment by jacobslusser** [comment]
I would be very interested in the possibility of `new TelemetryClient(ikey1,ikey2);` and knowing more about "TelemetrySinks". Please share.

**Comment by cijothomas** [comment]
new telemetryClient(key1,key2) dont exist now :(  so the closest is TelemetrySinks. Only doc as of now is unit tests:
https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/Test/Microsoft.ApplicationInsights.Test/Shared/Extensibility/TelemetrySinkTests.cs
I'll try to get a working example. It may not be super obvious.

Another alternative is to write a TelemetryProcessor which can send telemetry to an additional ikey.

**Comment by jacobslusser** [comment]
Awesome. Thanks. I'll review this.
