### ISSUE TITLE
Azure Docs: NetCore & Javascript Enabled

### ISSUE THREAD

**Issue by MS-TimothyMothra** [Microsoft/ApplicationInsights-Home#327]
I added a description of the APPINSIGHTS_JAVASCRIPT_ENABLED issue to our public documentation to address the flood of support tickets we were receiving. Now that Cijo fixed this issue, I need to remove this issue from our docs. 

I would do this today, but our docs are frozen for maintenance until 3/11. 

https://docs.microsoft.com/en-us/azure/azure-monitor/app/azure-web-apps#appinsightsjavascriptenabled-causes-incomplete-html-response-in-net-core-web-applications

**Comment by cijothomas** [comment]
Lets leave it there for now. There are still a few cases where this can cause the issue.

**Comment by MS-TimothyMothra** [comment]
okay. :)
how long do you think is appropriate to leave it up? a month?

**Comment by cijothomas** [comment]
Dont think we need to remove it anytime soon. (Also we are considering making a dedicated troubleshooting page for extensions - so it does n't hurt to have a long list)
