### ISSUE TITLE
CreateReleaseAnnotation fails using service account

### ISSUE THREAD

**Issue by roryprimrose** [Microsoft/ApplicationInsights-Home#33]
I'm trying to run this from Octopus Deploy. This means that the PowerShell script is getting executed using a local service account on the machine. The script fails because call to Invoke-WebRequest (and I suspect Invoke-RestMethod) use IE and Dom parsing. This doesn't work under a service account where IE was never started up first. 

The failure is:

The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again.

I have tried setting -UseBasicParsing and this also does not appear to work.

**Comment by SergeyKanzhelev** [comment]
@barustum, can you please help with this?

**Comment by roryprimrose** [comment]
Looks like the -UseBasicParsing switch did work for Invoke-WebRequest. The failure I now get seems to be in creating the annotation. Unfortunately there is not much information available in the logging.

```
05:55:51   Verbose  |       Octopus Server version: 3.2.21+Branch.master.Sha.5f3f4ee5402e9a70efb239e93fef2f701f2784c3
05:55:51   Info     |       Executing script on 'Octopus Server'
05:55:58   Verbose  |       Octopus Deploy: Calamari version 3.1.31+Branch.master.Sha.eb19e6867a24b7ca17e4a03a104af31b3689a39f
05:56:09   Verbose  |       Name                           Value
05:56:09   Verbose  |       ----                           -----
05:56:09   Verbose  |       PSVersion                      4.0
05:56:09   Verbose  |       WSManStackVersion              3.0
05:56:09   Verbose  |       SerializationVersion           1.1.0.1
05:56:09   Verbose  |       CLRVersion                     4.0.30319.42000
05:56:09   Verbose  |       BuildVersion                   6.3.9600.17400
05:56:09   Verbose  |       PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
05:56:09   Verbose  |       PSRemotingProtocolVersion      2.2
05:56:20   Info     |       Invoke a web request to create a new release annotation. Attempting 1
05:56:23   Info     |       Invoke a web request to create a new release annotation. Attempting 2
05:56:23   Info     |       Invoke a web request to create a new release annotation. Attempting 3
05:56:29   Info     |       Invoke a web request to create a new release annotation. Attempting 4
05:56:29   Info     |       Invoke a web request to create a new release annotation. Attempting 5
05:56:29   Error    |       Failed to create an annotation with Id: 0b7918b3-b63f-43be-aeb0-af86c8ed6dbc.
05:56:29   Error    |       Error Unknown, Description: Unknown.
05:56:29   Error    |       At C:\Octopus\Work\20160303055552-715\Script.ps1:120 char:3
05:56:29   Error    |       +      throw $output
05:56:29   Error    |       +      ~~~~~~~~~~~~~
05:56:29   Error    |       + CategoryInfo          : OperationStopped: (Failed to creat...ption: Unkn
05:56:29   Error    |       own.:String) [], RuntimeException
05:56:29   Error    |       + FullyQualifiedErrorId : Failed to create an annotation with Id: 0b7918b3
05:56:29   Error    |       -b63f-43be-aeb0-af86c8ed6dbc. Error Unknown, Description: Unknown.
05:56:33   Error    |       The remote script failed with exit code 1
```

**Comment by roryprimrose** [comment]
I'll add some more logging but I think there is an issue in the script.

```
		try {
			$result = Invoke-RestMethod -Uri "$grpEnv/applications/$applicationId/Annotations?api-version=2015-11" -Method Put -Body $bodyJson -Headers $headers -ContentType "application/json; charset=utf-8" -UseBasicParsing
		} catch {
		    if ($_.Exception -and $_.Exception.Response) {
				$createResultStatus = $_.Exception.Response.StatusCode.value__
				$createResultStatusDescription = $_.Exception.Response.StatusDescription
			}
		}

		if ($result -eq $null) {
			if ($createResultStatus -eq $null) {
				$createResultStatus = "Unknown"
			}
			if ($createResultStatusDescription -eq $null) {
				$createResultStatusDescription = "Unknown"
			}
		}
 		else {
			    $success = $true			         
        }
```

The create status and description variables assigned in the catch will get wiped out in the test of the result. The result would be null if an exception was thrown, in which case the values get set to "Unknown".

**Comment by barustum** [comment]
Thanks Rory. I'll take a look now.

**Comment by barustum** [comment]
Hi Rory,
Good catch on the "IE was never started up" issue. Invoke-RestMethod does not support the named parameter UseBasicParsing, that is why the request is failing for you. Can you try switching to Invoke-WebRequest instead of Invoke-RestMethod? Let me know if that works and I can make the change and add better logging.

**Comment by roryprimrose** [comment]
That was a stab in the dark, but based on the documentation. The info at https://technet.microsoft.com/en-us/library/hh849971.aspx does include the UseBasicParsing switch but it definitely fails when used. I'll give it another spin as per your suggestion.

I was also wrong about the variable assignment above. Looking at it again, the value won't get trumped because it checks whether there is already a value. Ignore that one :)

There is still an issue with the logging however in the scenario where there is an exception that doesn't have a response. In that scenario the exception information is lost. I'm running with the following:

```
		} catch {
		    if ($_.Exception){
		        if($_.Exception.Response) {
    				$createResultStatus = $_.Exception.Response.StatusCode.value__
    				$createResultStatusDescription = $_.Exception.Response.StatusDescription
    			}
    			else {
    				$createResultStatus = "Exception"
    				$createResultStatusDescription = $_.Exception.Message
    			}
		    }
		}
```

**Comment by roryprimrose** [comment]
FYI, my version of this script as an Octopus Deploy script step is at https://github.com/roryprimrose/Library/commit/300a8b15bc9da062ee7f6d375b8267d123e269d4

**Comment by SergeyKanzhelev** [comment]
@alancameronwills , @barustum does it make sense to add instructions on using this powershell at this page: https://azure.microsoft.com/en-us/documentation/articles/app-insights-annotations/

Also you can mention script for Octopus Deploy from @roryprimrose there

**Comment by barustum** [comment]
@roryprimrose Thanks for the Octopus Deploy step. Very Useful

@SergeyKanzhelev We already have a blog post for this here: https://azure.microsoft.com/en-us/blog/application-insights-powershell-script-available-for-creating-release-annotations/. I will talk to Mike Gresley about referencing Rory's Octopus step

**Comment by roryprimrose** [comment]
That would be great, although you may want to wait until my pull request is accepted by @PaulStovell and the Octopus Deploy team. At that time the build step should be published to http://library.octopusdeploy.com/#!/listing which would be a much nicer reference than the pull request itself.
