### ISSUE TITLE
SnapshotCollector: SnapshotUploader.exe locked

### ISSUE THREAD

**Issue by OneCyrus** [microsoft/ApplicationInsights-Home#336]
we are running multiple webs on the same server and are seeing that SnapshotCollector is having issues with the snapshotuploader blocked by other processes. is there a way to have custom folders for each web without changing to multiple users?

```
System.IO.IOException: The process cannot access the file 'C:\WINDOWS\TEMP\SnapshotUploader\SnapshotUploader.exe' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Microsoft.ApplicationInsights.SnapshotCollector.ShadowCopy.ExtractResources(Assembly assembly, IEnumerable`1 resourceNames, String destinationFolder)
   at Microsoft.ApplicationInsights.SnapshotCollector.Uploader.TryStartUploader()
```

**Comment by SergeyKanzhelev** [comment]
@pharring have you seen this question?

**Comment by pharring** [comment]
Thanks for the ping. I missed this question.
@clguimanMSFT FYI too.
You can set the ShadowCopyFolder property in SnapshotCollectorConfiguration.
It supports environment variable expansion if necessary (e.g. `%TEMP%\snapshotuploader\app1` )

**Comment by OneCyrus** [comment]
great! does this create subfolders (e.g. app1)? and is there a way to set this dynamically or random so we don‘t have those conflicts?

**Comment by pharring** [comment]
Yes, the folder will be created if necessary.

For dynamic values, if there's an environment variable that identifies each web app you could use that (e.g. WEBSITE_NAME) as part of the folder name.

To avoid the problem entirely, make sure that all apps are using the same version of the SnapshotCollector nuget. The Snapshot Collector checks the "last write time" on SnapshotUploader.exe to see if it needs updating and it will only try to update if the file's last write time is less than (older than), the last write time of the Microsoft.ApplicationInsights.SnapshotCollector.dll assembly.

I admit the algorithm here has its quirks. In particular -- the case you're hitting -- if an older SnapshotUploader is already running, the update will fail and there's no attempt to recover.

**Comment by OneCyrus** [comment]
the new AddSnapshotCollector() helped a lot to fix this issue for us. We set now a dynamic ShadowCopyFolder path.
This works very well with .Net Core projects but the AddSnapshotCollector() extension is not available in ASP.Net Core running on the Full .Net Framework. Is this by design or an issue?

**Comment by pharring** [comment]
Tagging @clguimanMSFT FYI

The `AddSnapshotCollector()` extension method is included only in the netcoreapp2.0 target of the SnapshotCollector nuget. If your project targets anything else, it'll likely pick up the netstandard2.0 target.

Assuming you're already referencing Microsoft.ApplicationInsights.AspNetCore version 2.1.1 or newer, you could write the extension method yourself. Here's the source code.

```csharp
using System;
using System.ComponentModel;
using Microsoft.ApplicationInsights.AspNetCore;
using Microsoft.ApplicationInsights.SnapshotCollector;
using Microsoft.Extensions.Options;

namespace Microsoft.Extensions.DependencyInjection
{
    /// <summary>
    /// Extension methods for dependency injection.
    /// </summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public static class SnapshotCollectorServiceCollectionExtensions
    {
        /// <summary>
        /// Add the Snapshot Collector to the DI container.
        /// </summary>
        /// <param name="services">The services collection.</param>
        /// <returns>The services collection with Snapshot Collector added.</returns>
        public static IServiceCollection AddSnapshotCollector(this IServiceCollection services)
            => AddSnapshotCollector(services, delegate { });

        /// <summary>
        /// Add the Snapshot Collector to the DI container.
        /// </summary>
        /// <param name="services">The services collection.</param>
        /// <param name="configure">Delegate that configures the <see cref="SnapshotCollectorConfiguration"/> options.</param>
        /// <returns>The services collection with Snapshot Collector added.</returns>
        public static IServiceCollection AddSnapshotCollector(this IServiceCollection services, Action<SnapshotCollectorConfiguration> configure)
        {
            services.AddOptions();
            services.AddSingleton<IConfigureOptions<SnapshotCollectorConfiguration>>(new ConfigureOptions<SnapshotCollectorConfiguration>(configure));
            services.AddSingleton<ITelemetryProcessorFactory, SnapshotCollectorTelemetryProcessorFactory>();
            return services;
        }
    }
}
```

and here's `SnapshotCollectorTelemetryProcessorFactory`:

```csharp
using Microsoft.ApplicationInsights.AspNetCore;
using Microsoft.ApplicationInsights.Extensibility;
using Microsoft.Extensions.Options;

namespace Microsoft.ApplicationInsights.SnapshotCollector
{
    /// <summary>
    /// A telemetry processor factory for <see cref="SnapshotCollectorTelemetryProcessor"/>
    /// instances.
    /// </summary>
    internal sealed class SnapshotCollectorTelemetryProcessorFactory : ITelemetryProcessorFactory
    {
        /// <summary>
        /// Options read from configuration.
        /// </summary>
        private readonly IOptions<SnapshotCollectorConfiguration> _options;

        /// <summary>
        /// Constructor called by dependency injection.
        /// </summary>
        /// <param name="options">Options from configuration.</param>
        public SnapshotCollectorTelemetryProcessorFactory(IOptions<SnapshotCollectorConfiguration> options)
            => _options = options;

        /// <summary>
        /// Create the telemetry processor.
        /// </summary>
        /// <param name="next">The next telemetry processor in the chain.</param>
        /// <returns>The new instance.</returns>
        public ITelemetryProcessor Create(ITelemetryProcessor next)
            => new SnapshotCollectorTelemetryProcessor(next, _options.Value);
    }
}
```

**Comment by OneCyrus** [comment]
ah ok thought this would be a netstandard lib.
thanks, i‘ll give this a try!
