### ISSUE TITLE
ReadTimeout and DNS resolution failure

### ISSUE THREAD

**Issue by dennis-tra** [microsoft/ApplicationInsights-Home#337]
Hey there,

I have already asked [here](https://github.com/Microsoft/ApplicationInsights-Ruby/issues/69) and I was forwarded to this repo :)

Just recently we started to experience the following error messages:
```
ERROR -- application_insights: Asynchronous sender work thread terminated abnormally: Net::ReadTimeout

or

ERROR -- application_insights: Asynchronous sender work thread terminated abnormally: Failed to open TCP connection to dc.services.visualstudio.com:443 (getaddrinfo: Temporary failure in name resolution)
```
in conjunction with the fluentd plugin [fluent-plugin-application-insights](https://github.com/Microsoft/fluent-plugin-application-insights). This happens several times a day. Any idea how we could debug that issue?

In the aforementioned issue the following was mentioned:
> There was a plan to have a common component written in .Net for logics like retry, sampling, so there is no need to replicate those logics for all language. I don't know how it is going right now, but it might be an option for you.

If someone has more information around this I would love to hear more about it :)

Thanks in advance,
Dennis

**Comment by cijothomas** [comment]
@dennis-tra Ruby SDK is community supported only. The issue you faced is likely when application insights backed timed out. If the Ruby SDK does not have retry, then it'll lead to data loss.
Unlike .NET or Java implementations, I don't think Ruby SDK has advanced retry mechanisms.

The common component mentioned in other repo is LocalForwarder, which is available as preview. But I don't think there is any Ruby support for it yet. This localforwarder has all the retry mechanisms, etc, but to make use of it in Ruby SDK, it needs to adapted to send data to locally installed Localforwarder which is not yet done. I cannot comment if this will ever be supported.
https://docs.microsoft.com/en-us/azure/azure-monitor/app/opencensus-local-forwarder

This is the place to give overall feedback about anything Application Insights, including supporting official Ruby SDK.
https://feedback.azure.com/forums/357324-application-insights

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
