### ISSUE TITLE
Application Insights End-to-end Transaction "Permalink"

### ISSUE THREAD

**Issue by AlskiOnTheWeb** [microsoft/ApplicationInsights-Home#347]
WRT issue #281 ...can we create a feature to offer a "permalink" URL based off of just the Operation ID? The suggested work around for #281 includes an Item ID. In our case, we don't have that item ID available in order to build the URLs referenced there...but we do have what equates to the operation ID. We're trying to build links from a client side application that will tie directly to the failed transactions.

**Comment by cbrianball** [comment]
@AlskiOnTheWeb I got around this by building a URL that included the operation ID to my application (a website), my application queries App Insights with the operation ID to get the item ID, then issues a redirect to App Insights.

**Comment by TimothyMothra** [comment]
mrbullwinkle
