### ISSUE TITLE
Traces not logged very early in ASP.NET app lifecycle?

### ISSUE THREAD

**Issue by tlmii** [Microsoft/ApplicationInsights-Home#35]
I've got a situation that I haven't been able to figure out.

I've got code in my override of Application.Init() - in global.asax.cs - that I want log what is happening. I am using the ApplicationInsightsTraceListener to do this.

I know that Application.Init() gets called multiple times (in my case at least, when published to an Azure Web App, this is 4 times) because the Application object is cached.

When it works normally, I get the trace information showing up in AppInsights (looking at it in the Azure Portal) 4 times.

However, sometimes, it only shows up three times. It appears that the first time is not being logged.

So I'm wondering, is it possible that I'm doing this too early in the ASP.NET application lifecycle and something with tracing, the tracelistener, app insights, etc isn't set up yet? Or could there be something else going on?

**Comment by SergeyKanzhelev** [comment]
It may be a simple data loss, not an initialization issue. How often do you see this data loss?

**Comment by AlexBulankou** [comment]
There was no follow up on this, so closing it here for now. If are still experiencing the issue, can you please reopen it here: https://github.com/Microsoft/ApplicationInsights-dotnet-logging with more details on whether you are seeing just this single first event missing or other data items missing as well. Thanks!
