### ISSUE TITLE
Can Application Insights do this like DynaTrace?

### ISSUE THREAD

**Issue by ketaanhshah** [microsoft/ApplicationInsights-Home#350]
Hello All,
I got these set of questions from a Performance Engineer who is trying to question Applications Insights in comparison to DynaTrace. I would really appreciate if someone can help me with these and how we can achieve it in Application Insights/Log Analytics:-
o	List all user actions (user screen button clicks) with response times, and errors
o	Ability to click on the above listed user actions/transactions and get a breakdown (% contribution) from high level methods/service calls/operations and its response time contribution
o	Ability to further break down each operation and get a breakdown of time spent at various sub-service calls
o	Ability to rollup the above per-transaction data to averages across all transactions for a period
o	All performance data is available without sampling
o	Each error is traceable to a caller and a called method/module

Appreciate help on this as I think Application Insights is powerful and can achieve things with custom queries etc but I was not able to find much myself on Microsoft Documentation so thought of checking with experts here.

**Comment by SergeyKanzhelev** [comment]
> - List all user actions (user screen button clicks) with response times, and errors

I assume it's for JavaScript on a web page? I think the best solution would be to wrap a button click into [trackDependency](https://docs.microsoft.com/azure/azure-monitor/app/api-custom-events-metrics#trackdependency) call. So a bit of custom code would be needed. @markwolff can have more ideas and suggestions.

> - Ability to click on the above listed user actions/transactions and get a breakdown (% contribution) from high level methods/service calls/operations and its response time contribution

[Performance view](https://docs.microsoft.com/azure/azure-monitor/app/web-monitor-performance#find-and-fix-performance-bottlenecks-with-performance-investigation-experience) is designed for this kind of analysis.

> - Ability to further break down each operation and get a breakdown of time spent at various sub-service calls

Same as above. Plus you may write a custom queries in analytics.

> - Ability to rollup the above per-transaction data to averages across all transactions for a period

Same as above. + @zakimaksyutov may have suggestions

> - All performance data is available without sampling

Check out the current situation. Application Insights is using an adaptive sampling (rate limiting sampling) and it only got kicked on for high load apps. In any case you can disable it completely. Read [here](https://docs.microsoft.com/azure/azure-monitor/app/sampling). Note, Application Insights uses pay as you go billing so charges for unsampled data may increase 

> - Each error is traceable to a caller and a called method/module

Method and module is a part of every exception event.

**Comment by ketaanhshah** [comment]
Thank you Sergey, I appreciate your quick response. @markwolff any additional comments/idea from you?

**Comment by markwolff** [comment]
User clicks must be manually instrumented currently. Unclear on what is meant by response times and errors -- network requests/responses and client errors are already collected. Is the click triggering an outgoing request? Or is it just a generic click as the user fills out a form?

**Comment by ketaanhshah** [comment]
Aah yes that's what was the question that if the instrumentation somehow can be made automated rather than manually asking the application teams to include the method calls.
The response times and errors were more with respect to an operation and basically what happens when the user is moving from one application to the other, basically for e.g. if a user is on a ecommerce website and he selects the item to purchase, then is forwarded to payment system (other app) and then checkout etc.. so basically for the user a seamless experience but in actual user is moved from one app to the other in the same user session, so that kind of breakdown

**Comment by markwolff** [comment]
This sort of breakdown does in exist on a pageview basis. E.g. we track for a particular user's session, which pages did they view and in which order. This funnel tracking is done automatically, but for SPA applications, you should use one of the community supported app insights SDKs for that particular framework.
https://github.com/microsoft/ApplicationInsights-JS/tree/master/vNext/extensions/applicationinsights-react-js
https://github.com/TrilonIO/angular-application-insights
https://github.com/latelierco/vue-application-insights

**Comment by ketaanhshah** [comment]
@markwolff Thank you so much sir, I am going to go thru the Angular community SDK u shared above and implement with sample. hopefully that should help us to get to where we want. I will keep all posted.
Thank you again @SergeyKanzhelev and @markwolff for being prompt in helping the community!

**Comment by SergeyKanzhelev** [comment]
@ketaanhshah I'd close the issue for now. Please re-open or create a new one when you have more questions.
