### ISSUE TITLE
Data usage charges

### ISSUE THREAD

**Issue by joepperkins** [microsoft/ApplicationInsights-Home#351]
When Application Insights are in different data centers than the source of the ingress are there also charges for egress from the source data center.

**Comment by cijothomas** [comment]
ApplicationInsights itself will not charge for egress, but there might be Azure VM/CS/WebApp charges.
@Dmitry-Matveev do you know more about this ?

**Comment by Dmitry-Matveev** [comment]
Azure does not differentiate calls to submit telemetry into Application Insights from any other network calls from the service. However, Azure may differentiate calls going through Azure Network (e.g. calls to Azure Storage or any other Azure services, including AI) vs. calls going outside of Azure Network (e.g. calls to the service hosted on-premises or in another cloud provider). If Azure does that differentiation, they might be billed differently, I'd recommend going through Azure networking charges documentation on this topic - AI docs won't cover this.

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
