### ISSUE TITLE
Question about reliability issues since Microsoft.ApplicationInsights.Web@2.2.0

### ISSUE THREAD

**Issue by rafanoronha** [microsoft/ApplicationInsights-Home#352]
Hey,

Would appreciate some guidance on relying on older versions of the sdk (web 2.2.0).
My customer has a broad Azure adoption and critical workloads served by virtual machines hosting legacy IIS/ASP.NET web apps.
These apps are logging debug information into sql server and we're considering moving to an approach where those are sent to AppInsights as trace events.

Is there any know issue on how reliable is the sdk duty of buffering/sending high volumes of data, eg, the sampling behavior? Specially versions up to 2.2.0.

**Comment by cijothomas** [comment]
@rafanoronha We always recommend to move to the latest version. We have fixed bugs in the area of channel, sampling etc since 2.2.0 time. You can look at changelogs to see the full list. (2.2.0 is quite old so the list of changes are long as well)

What's the reason for using this particular version?

**Comment by rafanoronha** [comment]
@cijothomas
Thanks for the heads up.
Those legacy apps were compiled with framework 4.0.
Just gave a second look a the pkg dependencies and figured SDK 2.4 would probably be best suited for us.

We're talking about leveraging a more robust logging infrastructure plus APM into applications missing this stuff.
So this is more about checking for critical/major reliability issues than more usual issues that certainly were handled since 2.4. Just to mitigate a "AppInsights knocked our apps down" scenario than anything else.

**Comment by cijothomas** [comment]
@rafanoronha you are mostly fine with 2.4, though you'll miss some bug fixes.

**Comment by rafanoronha** [comment]
Thanks @cijothomas
Keep up the work on AppInsights, we love the tool! :-)
