### ISSUE TITLE
AppInsight agent install changes machine's powershell execution policy

### ISSUE THREAD

**Issue by roman-76** [Microsoft/ApplicationInsights-Home#36]
InstallAgent.bat modifies powershell execution policy for the machine. I suggest to use powershell -ExecutionPolicy parameter when running installAgent.ps1
Instead:
`Powershell.exe -NoProfile -Command "& '%~dp0InstallAgent.ps1'" < NUL >> NUL 2>> NUL`
Do:
`Powershell.exe -NoProfile -ExecutionPolicy RemoteSigned -Command "& '%~dp0InstallAgent.ps1'" < NUL >> NUL 2>> NUL`

and remove block with
`Powershell.exe -NoProfile -Command "Set-ExecutionPolicy RemoteSigned" < NUL >> NUL 2>> NUL`

**Comment by SergeyKanzhelev** [comment]
Thanks for reporting. Would you mind to send PR for this?

**Comment by SergeyKanzhelev** [comment]
Thanks @roman-76 for this improvement in our script
