### ISSUE TITLE
Question about dependency tracking architecture

### ISSUE THREAD

**Issue by rafanoronha** [microsoft/ApplicationInsights-Home#364]
Hey,

Given a legacy IIS / ASP.NET web app compiled to Net40 scenario.
Have been working on leveraging app insights (SDK 2.4.0) to this system. Then realized dependency telemetry items are not being collected.

So, trying to figure the dependency tracking architecture out, came to the following conclusions:
From Net45 on, "event tracing for Windows" feed the SDK telemetry through System.Diagnostics.Tracing API.
Prior to Net45, SDK relies on app insights Profiler being avaiable.
Apparently the profiler exposes an API that enables proxying / decorating of any c# code, thus app insights use that to leverage sql and http dependency traces decorating the sql / http c# APIs.

Would appreciate the following guidance.
Are above conclusions right?

In order to make the Profiler avaiable to feed those items into my app's SDK, what need to be installed into the Azure VM hosting that app nowadays?
App insights Status Monitor?
Both app insights Status Monitor and app insights Profiler?

**Comment by Dmitry-Matveev** [comment]
@rafanoronha , you are correct with your conclusions:

- Prior to NET45, the only source to collect dependency information is to install profiler libraries that are delivered by Status Monitor. There is an ambiguity in the naming, but you won't need the so-called AI Profiler for this to work.
- Status Monitor v1 and Status Monitor v2 (Preview) should both do the job. However, SMv2 works with the latest SDK and, unless SDK 2.4 is preinstalled with the app, it won't be able to attach compatible SDK to NET40 app. Both SMv1 and [SMv2 can install and configure profiler piece](https://docs.microsoft.com/en-us/azure/azure-monitor/app/status-monitor-v2-api-enable-instrumentation-engine), though (called Instrumentation Engine), and configure it for IIS.
