### ISSUE TITLE
Is there a way to add the API key to Application Status Monitor v2 PowerShell Module

### ISSUE THREAD

**Issue by MarkIannucci** [microsoft/ApplicationInsights-Home#366]
We have some vendor provided compiled code which we are instrumenting via Application Status Monitor.  I noticed the [recent v2 release uses a PowerShell Module](https://docs.microsoft.com/en-us/azure/azure-monitor/app/status-monitor-v2-overview) to manage this which will be much easier for us to manage than the Web Platforms Installer that Microsoft has been using to deliver this functionality.  

Unfortunately, I haven't been able to figure out how to add the API key that you use to secure the [control channel](https://docs.microsoft.com/en-us/azure/azure-monitor/app/live-stream#secure-the-control-channel).  Is there a way to do that in the [Enable-ApplicationInsightsMonitoring cmdlet](https://docs.microsoft.com/en-us/azure/azure-monitor/app/status-monitor-v2-api-enable-monitoring)?

**Comment by cijothomas** [comment]
v2 doesn't allow any customizations, and livemetrics api key is something which users want to configure.
@MS-TimothyMothra what are our plans for allowing user customizations to ai.config?

**Comment by MS-TimothyMothra** [comment]
Hello @MarkIannucci,
Unfortunately, we don't support that at this time.

After we get v2 stable, we'll start work on exposing SDK configuration settings.
I appreciate you asking because this specific setting wasn't on our scope.

**Comment by MarkIannucci** [comment]
Thanks for the follow-up. I hope you're able to track this in your systems so we get notified when that work is done.  I have a placeholder in my code for the config, so I should be ready to light it up shortly after v2 allows it (•‿•)

**Comment by MS-TimothyMothra** [comment]
Hi @MarkIannucci,
I created a new issue (#375) to track this and other related issues.
Please feel free to comment on the new issue.
