### ISSUE TITLE
Application Insights and Log Analytics end to end

### ISSUE THREAD

**Issue by ketaanhshah** [microsoft/ApplicationInsights-Home#367]
Hi All,
With Application Insights and Log Analytics is it possible to track lets say an exception to the Server level? For e.g. We have IAAS hosted Virtual Machines which are running a custom application and that sends telemetry to Application Insights and Machine level logs are sent to the Log Analytics workspace (thru the agent). Lets say an exception happens in the application is it possible to trace it back to the machine level (if we have more than one machine serving that application request). Basically an end to end tracking from application side back to the machine on which it happned (could just be the config or something was wrong on that specific server, but how can we track or identify it?

Any recommendation on this?

Thank you

**Comment by Dmitry-Matveev** [comment]
@ketaanhshah , telemetry items delivered to Application Insights, such as Exception Telemetry, should have machine name on each item in Cloud_RoleInstance field.

Analytics UI support c[ross AI-LogAnalytics queries](https://docs.microsoft.com/en-us/azure/azure-monitor/log-query/cross-workspace-query), so you can take machine name from Exception and query Log Analytics for logs from this machine. Even better, you should be able [to join](https://docs.microsoft.com/en-us/azure/azure-monitor/log-query/joins) cross-AI/LogAnalytics as well like:

```
exceptions | where timestamp > ago(1h) | where …
| join worskpace('yourWorkspaceName').yourTableName on $left.cloud_RoleInstance == $right.ComputerName
| where ...
```

**Comment by ketaanhshah** [comment]
@Dmitry-Matveev Thank you for your detailed response! wow I didnt knw that cloud_RoleInstance was really the machine name but I know now :). Also do we have to set the cloud_RoleInstanceName property anywhere? For instance for some of the custom application we are setting the cloud_RoleName but not the cloud_RoleInstance. If we dont set this property will it pick up the machine name if it is an IAAS hosted service?

**Comment by Dmitry-Matveev** [comment]
@ketaanhshah, in short, yes.

Cloud_RoleInstance has slightly different meaning across different environments. For instance, it will have a value of cloud service instance for Azure Cloud Services but it will have name of the machine for IAAS because there is no other "instance" definition applicable for simple VM.

As you mentioned, one can always set this value manually if necessary, or simply propagate machine name in some other property (e.g. property bag) on the telemetry item.

**Comment by ketaanhshah** [comment]
@Dmitry-Matveev Thank you so much! this helps a lot. I wish your comments above are put in the documentation as they are concise, simple to understand.
