### ISSUE TITLE
metadata operation canceled exception

### ISSUE THREAD

**Issue by OneCyrus** [microsoft/ApplicationInsights-Home#374]
we have a lot of the following exceptions because our web isn't running on a azure VM and so AppInsight can't connect to the metadata service. is there a way to disable this metadata fetching?

![image](https://user-images.githubusercontent.com/7747800/61469872-46c90d00-a980-11e9-99e9-b51e84a29bb5.png)

**Comment by Dmitry-Matveev** [comment]
Moved to correct repo.
