### ISSUE TITLE
Tag Telemetry Data for Load Testing coming into AppInsights as Perf Data

### ISSUE THREAD

**Issue by ketaanhshah** [microsoft/ApplicationInsights-Home#378]
Hi All,
We run load tests time to time and what we want is some way to identify that data so that in future we can use it. We understand that Telemetry data stays for 90 days in App Insights and then needs to be moved to Storage. I wanted to know if there was a way to Tag the request, exceptions, etc happening during the load test as "PERFDATA#1", "PERFDATA#2" so that it can be easily queried in future to compare Load Testing results? in our case we have 15+ API Management services, 3 web-apps and some external .Net applications all integrated and currently reporting data into AI and they do have unique cloud_Rolenames. Any help here on how we can tag ONLY during PERF TEST?

**Comment by MS-TimothyMothra** [comment]
You can add a TelemetryInitializer to set any custom property
https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-filtering-sampling
