### ISSUE TITLE
how to add custom telemetry in statusmonitor v2

### ISSUE THREAD

**Issue by Kmdkca** [microsoft/ApplicationInsights-Home#379]
Hi
I'm trying out the new status monitor V2 for monitoring some on-prem apppools.
Much easier:-)
But how do I add custom telelmetryInitializer/modules to monitor the apppools without changing the running code? 
In the original status monitor, I added the assembly to bin folder and modified the applicationinsights.config for each apppool.

**Comment by MS-TimothyMothra** [comment]
Hi @Kmdkca,
I'm glad you're liking the newer V2. :)
I'm sorry to say that our initial version of Status Monitor v2 won't support customizations.

I've added your request to our backlog (#375) and I'm going to close this issue as a duplicate. 
Please add your comment to the other thread. We're monitoring upvotes to plan our next efforts.
