### ISSUE TITLE
Azure Storage SDK "chunking" affects AI context tracking

### ISSUE THREAD

**Issue by isaacabraham** [Microsoft/ApplicationInsights-Home#38]
If you e.g. upload a non-trivial blob in Azure (I think > 4mb), the Azure SDK chunks up the data into multiple requests of 4mb each.

In AI, the first "chunk" correctly shows as a dependency within the context of the request, but the remainder have no operation id (or parent operation id) so they appear as orphaned entries within AI. They should all have the correct operation id.

**Comment by SergeyKanzhelev** [comment]
We will track it in corresponding repository. Thanks a lot for reporting!
