### ISSUE TITLE
Server performance counters

### ISSUE THREAD

**Issue by jagathprasanga** [microsoft/ApplicationInsights-Home#389]
I have hosted Asp.Net Core 2.2 web application on CentOS and connected with Application Insights. All performance counters are working well except Server performance counters. But performance counters are showing for development Windows PC only.
Please help me on this regard.  
![image](https://user-images.githubusercontent.com/10453671/63778774-17a0a680-c903-11e9-8f28-e824fbc40c2c.png)

**Comment by cijothomas** [comment]
Performance Counters are only supported in Windows.
https://docs.microsoft.com/en-us/azure/azure-monitor/app/performance-counters#performance-counters-in-aspnet-core-applications

The latest beta sdk https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore/2.8.0-beta2 supports counter from all platform, but it'll be limited to  process cpu/ process memory.
