### ISSUE TITLE
Will application insights support opentracing?

### ISSUE THREAD

**Issue by Bo-Yee-Woods** [microsoft/ApplicationInsights-Home#391]

**Comment by Dmitry-Matveev** [comment]
@reyang, can you please take this question?

**Comment by reyang** [comment]
@Bo-Yee-Woods 

Application Insights is part of [Azure Monitor](https://docs.microsoft.com/en-us/azure/azure-monitor/overview) product.
[OpenTracing](https://opentracing.io) is a vendor neutral API for distributed tracing, developed by LightStep. It is being superseded by [OpenTelemetry](https://opentelemetry.io) under CNCF.
We do have plan to provide native support in [OpenTelemetry](https://opentelemetry.io) to pipe data to Azure Monitor / Application Insights.
There is no plan to support OpenTracing API from Azure Monitor / Application Insights given OpenTelemetry is the direction to go.

**Comment by Bo-Yee-Woods** [comment]
OK, thank you!
