### ISSUE TITLE
A lot of NuGet search requests for Microsoft.ApplicationInsights.SnapshotCollector

### ISSUE THREAD

**Issue by joelverhagen** [microsoft/ApplicationInsights-Home#397]
I am on the nuget.org team and we are in the process of switching our search implementations. I am looking at the HTTP request logs on our old search service and I am noticing thousands of requests per day for the following URL:

```
https://api-v2v3search-1.nuget.org/query?q=packageid:Microsoft.ApplicationInsights.SnapshotCollector
```

The reason I am asking here is because the referrer on the requests look like this:

```
https://appinsights.hosting.portal.azure.net/appinsights/content/{version}/iframe/node_modules/curated.app/index.{hex}.html?instrumentationKey={key}&endpointAddress=https%3A%2F%2F{subdomain}.aimon.applicationinsights.io%2Fv2%2Ftrack&clientOptimizations=undefined&l=en.en-us&trustedAuthority=https%3A%2F%2Fportal.azure.com&shellVersion=undefined
```

I go to this URL and there is an error that this request is expecting to be in the parent frame `portal.azure.com`.

This leads me to believe that some Application Insights component in the Azure Portal is making requests to our search service. The volume is not an issue for us (although is an outlier in our query patterns). The problem is that we are planning on deprecating this URL soon.

As mentioned in the NuGet HTTP protocol documentation, the search service URL should be discovered from the service index, not hard-coded. The service index is here:
https://api.nuget.org/v3/index.json

[API Overview](https://docs.microsoft.com/en-us/nuget/api/overview)
[Service Index](https://docs.microsoft.com/en-us/nuget/api/service-index)
[Search resource](https://docs.microsoft.com/en-us/nuget/api/search-query-service-resource)

In the short-term, the new search URLs are:
- https://azuresearch-usnc.nuget.org/query
- https://azuresearch-ussc.nuget.org/query

If this is the wrong place, could you help me get in contact with the right people? I am a Microsoft employee, alias "jver".

**Comment by Dmitry-Matveev** [comment]
@pharring , can you please take a look?

**Comment by pharring** [comment]
My guess is that this is for our upgrade check. The AIMon code checks for the latest version of the nuget package, compares it with the version from heartbeat telemetry and shows an upgrade banner if there's a mismatch.
@jemodyMS @jewinkle

**Comment by JacobBovee** [comment]
Hey @joelverhagen I have a PR open for this issue however I was hoping you could give me some insight as to when CORS support will be live as it currently causes errors when developing for our app. Thank you.

**Comment by joelverhagen** [comment]
Yes, we caught this change in behavior between the new and old service when inspecting IIS logs. The change should be deployed tomorrow. It is currently in our PPE environment.

**Comment by joelverhagen** [comment]
@JacobBovee - this has been deployed to https://azuresearch-usnc.nuget.org/. It will be deployed to https://azuresearch-ussc.nuget.org/ tomorrow. CORS/AJAX should work just fine for you now.

**Comment by pharring** [comment]
I believe this has been resolved now.
