### ISSUE TITLE
HTTP 409 from CloudBlobContainer.CreateIfNotExists or CloudTable.CreateIfNotExists is logged as failed  

### ISSUE THREAD

**Issue by grzegorzbrelski** [microsoft/ApplicationInsights-Home#404]
So, as in title.

Natural behavior of .CreateIfNotExists (at least how I understand it) looks like follow: 

- Make a call to create the container or table (HTTP PUT Request).

- If an error was returned (HTTP 409) because the container or table already exists then do nothing. The error is handled.

- If the container or table did not exist then create would have succeeded.

Application Insights log 409 as failed, when it should be warning, cause this is no exception that table or container exist.

Current behavior mislead users of service, cause it looks like request failed.

Thanks in advance !

**Comment by TimothyMothra** [comment]
This can be filtered out of your telemetry using a custom TelemetryInitializer or TelemetryProcessor
