### ISSUE TITLE
Azure Monitoring Agent and Dependancy Details

### ISSUE THREAD

**Issue by ketaanhshah** [microsoft/ApplicationInsights-Home#415]
Hi All,
We have a scenario where a .Net App is hosted on IIS on vm and that app connects with SQL Server. We are trying to get end to end transaction details including the SQL statements fired etc and what we got to know from one of the experts at Microsoft is the Azure Monitoring Agent is what's used to send logs to Log Analytics, but it's also what gets dependancy details for App Insights.
I have not got any documentation which specifies that and can someone please confirm that if this is correct?

This is what I read https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-dependencies

IIS   Server (Azure VM, on-prem, and so on.) | Use   the Status Monitor PowerShell Module to install the Instrumentation   Engine and restart IIS.
-- | --

Can someone help here?

**Comment by Dmitry-Matveev** [comment]
Similar question has been posted on [StackOverflow recently](https://stackoverflow.com/questions/58624849/azure-monitoring-agent-and-dependancy-details?noredirect=1#comment103593857_58624849). I will re-use the comment from that question:

"To collect SQL statements you would need Instrumentation Engine libraries at your service (you won't need them for the .NET Core SQL statement collection, they should be available by default with the recent AI SDK versions). The way you deliver instrumentation engine to the service differs and all presently supported options are outlined in the document you linked, such as using PowerShell Status Monitor v2 module for VMs or extension for Web Apps. Log Analytics agent used to drop Instrumentation Engine libraries as well, but I do not think it still does."

**Comment by ketaanhshah** [comment]
Thank you @Dmitry-Matveev this is very helpful.
