### ISSUE TITLE
Please provide a Dart SDK to use with Flutter

### ISSUE THREAD

**Issue by jonsamwell** [microsoft/ApplicationInsights-Home#416]
Please provide a Dart SDK to use with Flutter.

Alternatively, could you point me in the directions of some API information so I can start to communicate with app-insights from Flutter via HTTP

**Comment by Dmitry-Matveev** [comment]
One can submit telemetry directly to AI Endpoint following the Endpoint Specs / Protocol [outlined here](https://github.com/microsoft/ApplicationInsights-Home/tree/master/EndpointSpecs).

Dart SDK is not planned, so going direclty against endpoint is a good workaround.

**Comment by jonsamwell** [comment]
Many thanks for the reply
