### ISSUE TITLE
Potential memory leak from application insights

### ISSUE THREAD

**Issue by graham-saunders** [microsoft/ApplicationInsights-Home#420]
I received a notification from Smart Detection telling me there is a potential memory leak in APP_WIN32_PROC.

I believe this is related to application insights, as APP_WIN32_PROC is a part of the telemetry model.

The application insights name is Virtuous.Jobs.Interminable

How can I dig into this further? The smart detection and app insights doesn't seem to offer much a solution.

Let me know if I can provide any more info!

**Comment by Dmitry-Matveev** [comment]
Application Insights itself does not execute memory profiling and won't be able the deep dive diagnostic of the memory issue. In this example Application Insights has evaluated several available indicators such as memory-related metrics and concluded that there is a possibility of the memory leak. As a result pro-active alert from smart detection has been generated.

You can plot memory metrics in Application Insights Metric Explorer to start with the investigation. However, to actually investigate the source of the leak, you'd need to employ some memory profiling tool on that application.
