### ISSUE TITLE
Missing/Dropped RequestTelemetry when Success flag is false with no ResponseCode

### ISSUE THREAD

**Issue by danpacgig** [microsoft/ApplicationInsights-Home#426]
As the title suggests when the success flag is set to false, nothing goes to app insights cloud.

repro : 
logging is `private readonly TelemetryClient logging;`

This messages will get lost
```
using (var operation = logging.StartOperation<RequestTelemetry>($"my test"))
{
   operation.Telemetry.Success = false;
}
```

the below works

```
using (var operation = logging.StartOperation<RequestTelemetry>($"my test"))
{
   operation.Telemetry.ResponseCode = "whatever
   operation.Telemetry.Success = false;
}
```

this automatically changes response code to 200
```
using (var operation = logging.StartOperation<RequestTelemetry>($"my test"))
{
   operation.Telemetry.Success = true;
}
```

**Comment by Dmitry-Matveev** [comment]
`ResponseCode` is a required field on AI Endpoint for Request Telemetry item. If this field is missing, the telemetry is getting dropped and AI endpoint should reply back with 40x type of error.

Default for Success is true and AI SDK automatically sets 200 as a response code. When AI SDK detects failure it automatically changes both fields. However, if Success's value is changed manually, AI SDK would not know which code to set alongside it and would expect customer to provide response code as well.
