### ISSUE TITLE
Can the "wait" be part of the Flush?

### ISSUE THREAD

**Issue by mikeblakeuk** [microsoft/ApplicationInsights-Home#428]
a) How long should we wait for the flush?
https://github.com/microsoft/ApplicationInsights-Home/blob/2dbdd7c58ceca76beff99bbeaef9327071995669/Samples/WorkerServiceSDK/ConsoleAppWithApplicationInsights/ConsoleAppWithApplicationInsights/Program.cs#L55
b) Why can the we have a FlushBlocking() method instead? https://github.com/Microsoft/ApplicationInsights-dotnet/issues/407

**Comment by cijothomas** [comment]
https://docs.microsoft.com/en-us/azure/azure-monitor/app/telemetry-channels#which-channel-should-i-use
The exact time is not predictable. The Flush() is being tracked as an enhancement. I dont have an ETA for that yet.

**Comment by mikeblakeuk** [comment]
Task.Delay(500000) feels too long. Should it be around 5 seconds?

**Comment by cijothomas** [comment]
Right. 5-10 secs would do in most cases. (the example acciddently put additional zeros)
