### ISSUE TITLE
Microsoft.ApplicationInsights.WorkerService dependency System.Runtime.CompilerServices.Unsafe load fail on .NET 4.7.2 Windows Service

### ISSUE THREAD

**Issue by HMoen** [microsoft/ApplicationInsights-Home#429]
Hello.

**Issue:** (CLR v4.0.30319)
Using nuget package [Microsoft.ApplicationInsights.WorkerService](https://www.nuget.org/packages/Microsoft.ApplicationInsights.WorkerService) version 2.8.2 in a .NET 4.7.2 windows service throws the exception below when calling the **TelemetryClient.StartOperation** method per the example used in this [article](https://docs.microsoft.com/en-us/azure/azure-monitor/app/worker-service#net-corenet-framework-console-application). Using the traditional inidividual MS AI Nugets for .NET 4.6.1 also throws the same exception. When running the windows service as a console app in VS, it does not throw this exception. The **System.Runtime.CompilerServices.Unsafe** dll is included in the application folder and its file version is **4.6.26919.2**.

**Exception:** 
> The type initializer for 'PerTypeValues`1' threw an exception.
> System.BadImageFormatException: Could not load file or assembly System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a or one of its dependencies. 
> Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)

**Relevant Code:**
```
try
{
    using (telemetryClient.StartOperation<RequestTelemetry>("operation")) //throws exception here
    {
        await this.httpClient.GetAsync("https://bing.com").ConfigureAwait(false);
        telemetryClient.TrackEvent("Bing call event completed");
    }
} 
catch (Exception e)
{
    Debug.WriteLine(e);
    this.Stop();
}
```

**App.Config:** (auto-generate bindings is checked)
```
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2" />
  </startup>
  <appSettings>
    <add key="Azure.ApplicationInsights.InstrumentationKey" value="47057928-ade5-4640-852e-151f0e4ec69b" />
  </appSettings>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Extensions.DependencyInjection.Abstractions" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.2.0.0" newVersion="2.2.0.0" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Memory" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.1.1" newVersion="4.0.1.1" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.4.1" newVersion="4.0.4.1" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Sample Project:**
https://github.com/HMoen/WindowsService-AI-Dependency-Failure
You can run this project as a console app from VS or install it as a windows service and add the Application Insights Instrumentation Key during installation.

Other TelemetryClient methods such as the following seem to work fine:
- TrackEvent
- TrackTrace
- TrackMetric

**Question:**
1. Is this package not suitable for .NET 4.7.2 windows service projects or only console apps?
2. If it is suitable for WS projects, what else can I try to fix this issue?

Thank you in advance to all.

**Comment by cijothomas** [comment]
Thanks for reporting and sharing the issue. We'll investigate this and get back.

**Comment by cijothomas** [comment]
@Dmitry-Matveev Any chance you know more about this? The app runs fine except when run as windows service.

The type initializer for 'PerTypeValues`1' threw an exception.
System.BadImageFormatException: Could not load file or assembly System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a or one of its dependencies.
Reference assemblies should not be loaded for execution. They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)

**Comment by HMoen** [comment]
Thanks for looking into this @cijothomas and @Dmitry-Matveev. 

In the meantime, is there a work around for windows services? Thanks.

**Comment by Dmitry-Matveev** [comment]
@HMoen , I would suggest trying to add System.Runtime.CompilerServices.Unsafe 4.5.0+ package explicitly into the project as a workaround, it seemed to help others on GitHub with the similar issues. 

Locally, VS resolves such references successfully from its caches or MSBuild extension folders, but when deployed as a service, certain indirect references may become unresolved out of VS context, especially with strict redirects in the config. Pinning it to a certain version may do the trick.

**Comment by HMoen** [comment]
@Dmitry-Matveev, I tried your suggestion with no success. I tried adding System.Runtime.CompilerServices.Unsafe 4.5.0-4.6.0. When 4.6.0 is added, app.config gets the following added automatically upon install:
```
<dependentAssembly>
  <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-4.0.5.0" newVersion="4.0.5.0" />
</dependentAssembly>
```
If I manually correct the version to the following, it still throws the excption that it can't find the specified version:
```
<dependentAssembly>
  <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-4.0.5.0" newVersion="4.6.0.0" />
</dependentAssembly>
```

I updated the sample project to reflect the explicit addition of the Nuget:
https://github.com/HMoen/WindowsService-AI-Dependency-Failure

Is there anything else I could do?

**Comment by lmolkova** [comment]
@HMoen please do not correct the version. Binding redirects require Assembly version (4.0.5.0) and not nuget version (4.6.0).

Does the problem reproduce when you have 

```xml
<dependentAssembly>
  <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-4.0.5.0" newVersion="4.0.5.0" />
</dependentAssembly>
```

in the app.config?

**Comment by HMoen** [comment]
@lmolkova, yes, the exception also occurs without correcting the version.

**Comment by lmolkova** [comment]
Are you still seeing an exception about "4.0.4.1" version? Can you search for any mentions of this version in your project? I see something in your repo (https://github.com/HMoen/WindowsService-AI-Dependency-Failure/blob/2864bcba7bc1cdcc89d495fb243d22b963075282/WindowsServiceAIFailureSetup/WindowsServiceAIFailureSetup.vdproj)

If updating it won't help, please enable [fuslog](https://docs.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer) - it will show detailed information on directories for dll and problems with binding/loading

**Comment by HMoen** [comment]
Yes, I'm still seeing the exception about "4.0.4.1" version when Nuget 4.60 is explicitly added. I will enable fuslog and get back to you shortly.

**Comment by lmolkova** [comment]
Thanks! can you make sure this https://github.com/HMoen/WindowsService-AI-Dependency-Failure/blob/2864bcba7bc1cdcc89d495fb243d22b963075282/WindowsServiceAIFailureSetup/WindowsServiceAIFailureSetup.vdproj is not what requiring 4.0.4.1 version? Something in your project requires 4.0.4.1

**Comment by HMoen** [comment]
The sample project has no dependencies besides Microsoft.ApplicationInsights.WorkerService version 2.8.2. If I attempt to downgrade System.Runtime.CompilerServices.Unsafefrom 4.6.0 to 4.50, I get the following NU 1605 warning:

> Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1605	Detected package downgrade: System.Runtime.CompilerServices.Unsafe from 4.5.2 to 4.5.0. Reference the package directly from the project to select a different version. 

> WindowsServiceAIFailure -> Microsoft.ApplicationInsights.WorkerService 2.8.2 -> Microsoft.ApplicationInsights.DependencyCollector 2.11.2 -> System.Diagnostics.DiagnosticSource 4.6.0 -> System.Memory 4.5.3 -> System.Runtime.CompilerServices.Unsafe (>= 4.5.2) 

It seems System.Memory 4.5.3 is requiring that version.

**Comment by HMoen** [comment]
When running the project, FUSLOG generates the attached report. 
[fuslog-output.txt](https://github.com/microsoft/ApplicationInsights-Home/files/3872319/fuslog-output.txt)

**Comment by lmolkova** [comment]
System.Memory depends on System.Numerics.Vectors. so maybe System.Memory version is a problem here.

Also what I see in fuslog 
> Comparing the assembly name resulted in mismatch of Processor Architecture: Ref MSIL, Def Legacy.

Can you check that you compile your project against proper processor architecture?

I was trying to repro the problem on my machine. 

I cannot load your vdproj, so I just started windowsServiceAIFailure csproj. It works fine on my maching. Which one do you start? 
If vdproj, could you please comment on my previous mentions of it and why it has reference to System.Runtime.CompilerServices.Unsafe  4.0.4.1?
Note that App.config in your repo is also empty - it does not include any binding redirects.

**Comment by HMoen** [comment]
My machine is Windows 10 Pro version 1903 and am compiling using VS 2019 16.3.10 with platform target "Any CPU" with "Prefer 32-bit" option checked.

Running windowsServiceAIFailure csproj in VS 2019 won't throw any exception. It's when it is installed as a windows service that it throws the exception. Can you install the project as a service without using the setup project?

**Comment by HMoen** [comment]
I ran the project as a console application outside of VS and it runs perfectly. It seems that when the project is installed as a service and started from Services.msc it no longer can find the dependencies.

Does a windows service look for references in a different location instead of the application folder?

**Comment by lmolkova** [comment]
Your vdproject project brings old version of System.Runtime.CompilerServices.Unsafe (4.5.1). You need to configure it to bring 4.6.0 and make sure it brings right System.Memory. I believe this is the root cause of this issue.

**Comment by HMoen** [comment]
@lmolkova, 4.6.0 (4.0.5.0) is being installed in the application folder (attached) and as you can see from the snippet of vdproject below:
![dll-installed](https://user-images.githubusercontent.com/2124254/69367479-6477ed00-0c66-11ea-909e-9e751a32c5f9.jpg)

```
{
            "AssemblyRegister" = "3:1"
            "AssemblyIsInGAC" = "11:FALSE"
            "AssemblyAsmDisplayName" = "8:System.Runtime.CompilerServices.Unsafe, Version=4.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
                "ScatterAssemblies"
                {
                    "_5DC60841F8B356815BA0ED27C9BC1D4F"
                    {
                    "Name" = "8:System.Runtime.CompilerServices.Unsafe.dll"
                    "Attributes" = "3:512"
                    }
                }
            "SourcePath" = "8:System.Runtime.CompilerServices.Unsafe.dll"
            "TargetName" = "8:"
            "Tag" = "8:"
            "Folder" = "8:_75860C05E5774FC989E5F14E89A05F67"
            "Condition" = "8:"
            "Transitive" = "11:FALSE"
            "Vital" = "11:TRUE"
            "ReadOnly" = "11:FALSE"
            "Hidden" = "11:FALSE"
            "System" = "11:FALSE"
            "Permanent" = "11:FALSE"
            "SharedLegacy" = "11:FALSE"
            "PackageAs" = "3:1"
            "Register" = "3:1"
            "Exclude" = "11:FALSE"
            "IsDependency" = "11:TRUE"
            "IsolateTo" = "8:"
            }
```
The following automatically generated binding redirect in App.config ([WindowsServiceAIFailure.exe.config.txt](https://github.com/microsoft/ApplicationInsights-Home/files/3876257/WindowsServiceAIFailure.exe.config.txt)) should have the project use the installed 4.6.0:
```
<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.5.0" newVersion="4.0.5.0" />
      </dependentAssembly>
    </assemblyBinding>
```

It's at runtime the project seems to still look for 4.0.4.1 instead of the installed 4.0.5.0 which the redirect binding references.

I will look into System.Memory now.

**Comment by HMoen** [comment]
@lmolkova, running the .exe as a console app from the VS project bin folder it runs perfectly. Running the .exe as a console app from the installed folder, it crashes. I compared the DLLs in the bin folder against the DLLs in the installed folder and noticed the following two DLLs have different file sizes even though they are the same version as you can see from the attached image.

- System.Buffers (28kb vs 22kb)
- System.Numerics.Vectors (114kb vs 29kb)

What could cause these file sizes and its contents to change even though they are the same version? It seems vdproject is selecting another version of these file from the GAC maybe? Any thoughts @Dmitry-Matveev or @cijothomas ?

Manually copying all DLLs from bin folder to installed folder fixes the issue, thus the culprit indeed is the vdproject copying over the wrong assemblies. Which team or github thread should I refer for this?

![dll-variance](https://user-images.githubusercontent.com/2124254/69372987-c89fae80-0c70-11ea-991e-61d5354246e9.jpg)

**Comment by HMoen** [comment]
FIX: add the 4 following assemblies manually from project bin folder in addition to "Project Output" in installer project:
1. System.Buffers
2. System.Memory
3. System.Numeric.Vectors
4. System.Runtime.CompilerServices.Unsafe

Of the 4 DLLs added by the installer project, only System.Numeric.Vectors is being referenced from the nuget net46 folder instead of netstandard2.0 folder like other 3. After looking at https://github.com/dotnet/standard/issues/250, it might be related.

Closing since this rabbit hole is too deep and uninteresting. Thanks for all the help @lmolkova, @Dmitry-Matveev, and @cijothomas.

![dll-manual-add](https://user-images.githubusercontent.com/2124254/69441904-89796800-0d19-11ea-9aec-8e0a2af40496.jpg)
![dll-system_numeric_vectors-issue](https://user-images.githubusercontent.com/2124254/69441914-8d0cef00-0d19-11ea-83b1-26611b3c497f.jpg)

**Comment by victorlin** [comment]
@HMoen This is interesting - I am having the same issue, but with an Azure Cloud Services Worker Role running .NET Framework 4.6.2. Posting here because it seems to be the only thread on the internet discussing my exact problems.

Everything runs fine as console app, but a runtime error shows when running as a Worker Role instance:

> System.BadImageFormatException: 'Could not load file or assembly 'System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)'

Using fuslogvw.exe to view the assembly binding logs, the underlying problem seems to be the same:

```
LOG: Assembly Name is: System.Numerics.Vectors, Version=4.1.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
WRN: Comparing the assembly name resulted in mismatch of Processor Architecture: Ref MSIL, Def Legacy.
ERR: The assembly reference did not match the assembly definition found.
```

The same 2 DLLs had same versions but different file sizes when comparing the project bin and Worker Role instance folders. File size disparities were the same as yours.

Unfortunately, copying the DLLs over doesn't work for me. Continuing the investigation...

**Comment by HMoen** [comment]
@victorlin Sorry to hear... It was a pain to get it to work on my end, but it's still working fine, however. The latest NUGET requires less of the files too to manually add to the output folder, but can't confirm which ones. Good luck and please post your solution here once you find it for others. Thanks.

**Comment by victorlin** [comment]
I got around the System.ValueTuple exception by:

1. Deleting a `<bindingRedirect>` for System.ValueTuple (per [this post](https://stackoverflow.com/a/53512525/4410590))
2. Copying these files over AFTER starting the Cloud Service (that's when it copies over the worker role files):
    - System.Buffers.dll
    - System.Numerics.Vectors.dll
    - System.Runtime.CompilerServices.Unsafe.dll
    - System.Runtime.dll

Now I am running into another exception that seems to be unrelated. However, this new problem (and previous problems) also appears only when run as a Worker Role. Running as console app is always fine. I have been finding little "hacks" like this one to bypass various exceptions, and my guess is that they all stem from some big underlying problem with the way .NET dependencies are handled in different environments.
