### ISSUE TITLE
ApplicationInsightsProfiler StopProfiler failed after WebApp restart

### ISSUE THREAD

**Issue by OzBob** [microsoft/ApplicationInsights-Home#435]
@pharring @xiaomi7732 @juliusl 
Restarted my webapp 20191127 and StopProfiler errors have appeared every morning in my Applicationinsights Failures log.

Failed method	Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpResponseParsers.ProcessExpectedStatusCodeNoException	
Problem Id	System.Net.WebException at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpResponseParsers.ProcessExpectedStatusCodeNoException	
Assembly	Microsoft.WindowsAzure.Storage, Version=8.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35	
...
at Microsoft.ServiceProfiler.Collectors.DetailedTraceCollector+d__38.MoveNext (ApplicationInsightsProfiler, Version=2.6.1909.2701, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
...

AgentVersion | 2.6.1909.2701
Machine_EnvironmentType | ANTARES

The last time this occurred (First mentioned in #377)  a restart reverted the Agent back to a previous version.

What is the recommended solution today?

**Comment by pharring** [comment]
Hi, @OzBob this might be a service-side error. Please contact us by email at serviceprofilerhelp@microsoft.com and let us know your Application Insights instrumentation key so we can check telemetry on our side.

**Comment by pharring** [comment]
I think this was resolved over email.
