### ISSUE TITLE
Diagnostics Logging for Application Insights Service in Azure

### ISSUE THREAD

**Issue by ketaanhshah** [microsoft/ApplicationInsights-Home#441]
Hi All,
We use Azure Application Insights and Generate Alerts and also use webhooks.
We are looking for Logs of Application Insights itself for the Alert generated (This is not the application's log but the diagnostics logs about Application Insights Alert that was generated) as we want to debug details on what data was sent in the Alert's webhook and what was the url (kind of Verbose log of Application Insights).
Does anyone know where we can find that log? Will it be in AzureDiagnostics in Log Analytics any KQL for it?

Thank you

**Comment by yanivlavi** [comment]
Can you explain the use case please? 
We don't expose the alerting engine log currently. Other than in the alert management history.

**Comment by ketaanhshah** [comment]
@yanivlavi we are sending the Json payload to webhook thru one of our App Insights Alerts and their was a failure their. So we wanted to look at the logs like what was the Json pay load sent, what was the webhook URL etc used during that alert firing (which some devz may have changed). So to find out that Alert's log for what all was sent exactly at that execution we were looking for that logs.

**Comment by yanivlavi** [comment]
You can get the alert payload which is in the same format as the webhook as well as the URL used from alert rules. Maybe a support case will help you resolve the issue as well, if you get stuck.

**Comment by ketaanhshah** [comment]
thank you @yanivlavi but like the workflow (Logic apps) logs get logged to Log Analytics workspace why not have an option to log some intern App Insights logs related to tenant to log analytics workspace. What we want is the actual payload at that time generated just to see if it had exceptions and also which url and how ti parsed it. I agree Premier ticket will help but wish this gets added as other services are logged in log analytics.

**Comment by yanivlavi** [comment]
We are exploring adding logs to alerts and exposing it to customers, but nothing solid yet. I agree this could be helpful. I also suggest you post us a UserVoice to track your request.

**Comment by ketaanhshah** [comment]
ty @yanivlavi surely will raise the request thru UserVoice.
