### ISSUE TITLE
Overview blade - Server Response time metric is 1000x higher than expected

### ISSUE THREAD

**Issue by PashaPash** [microsoft/ApplicationInsights-Home#445]
I have an app with some medium load, mix of .NET Core Micro services and old .NET Framework code. We have a lot of inter-services calls, so avg request duration is less than 100ms:

 
![image](https://user-images.githubusercontent.com/1866711/71412621-944c5300-265f-11ea-9184-61368c099219.png)
![image](https://user-images.githubusercontent.com/1866711/71412638-a4643280-265f-11ea-9ae5-1778d400da12.png)

However, Server Response Time chart on overview blade shows some crazy values like **1.6 minutes** average with 13 minutes response time peaks:
![image](https://user-images.githubusercontent.com/1866711/71412701-ec835500-265f-11ea-827f-dcd3ded2e8d1.png)

Here is a response from support on how that Server Response time is calculated:

> Duration in overviewblade is summarized by timespan and grain. The avg value depends on how many grains in that timespan range. The overall duration in performance grid is summarized by operations. The avg value depends on avgs of operations.

I just don't get it. Does that mean "Works as expected"? 

The resulting "1.6 minutes average server response time" is totally unrelated to the real application performance.  
That is 1000 times higher than avg value from Performance blade and 1500 times higher than `requests | summarize avg(duration)` output.

What is the point of that "summarization"? Is there any way to fix or disable it?

**Comment by zakimaksyutov** [comment]
This indeed doesn't make much sense. It sounded that you opened official support ticket for this case. If yes, can you please send it to me so I would look it up? zakima __a___t__ microsoft (.com).

**Comment by PashaPash** [comment]
@zakimaksyutov got an update from support:

"summarized by operations" part seems to be related only for Operations Blade vs Log Analytics metric mismatch (94.4 ms vs 62.197ms). My Log Analytics query ignores `itemCount` for requests. Here is a correct one: 

```
requests
| where timestamp > ago(24h)
| summarize SimpleSummarization=avg(duration), SummarizeConsideringSampling=sum(itemCount * duration)/sum(itemCount)
```

For Server Response Time chart (the one with 1.6 min values) - support told me that it is not based on `requests` data, and that is uses some pre-aggregated values from SDK side. It seems like SDK side preagreggation includes all requests, including requests filtered out from telemetry. 

We have a SignalR service with custom telemetry processor to filter out long SignalR connections. However, those connections are still included in preagreggation for metrics on SDK side. Asked for the confirmation from support 6 days ago, still waiting for reply. 

SignalR seems to be a widely used part of the platform, not sure why AppInsights metrics does not take it into account.

**Comment by PashaPash** [comment]
Got a response from support. Metric aggregation is performed on the SDK side, by standard `AutocollectedMetricsExtractor` telemetry processor. Any custom telemetry processors that filters our response telemetry types should be registered before that standard metrics extractor.

For ASP.NET Framework, custom processor should be listed first in `<TelemetryProcessors>` config:

```
<TelemetryProcessors>
    <Add Type="WebApplication1.SignalRTelemetryFilter, WebApplication1" /> <-------------------------
    <Add Type="Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryProcessor, Microsoft.AI.PerfCounterCollector"/>
    <Add Type="Microsoft.ApplicationInsights.Extensibility.AutocollectedMetricsExtractor, Microsoft.ApplicationInsights"/>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.AdaptiveSamplingTelemetryProcessor, Microsoft.AI.ServerTelemetryChannel">
        <MaxTelemetryItemsPerSecond>5</MaxTelemetryItemsPerSecond>
        <ExcludedTypes>Event</ExcludedTypes>
    </Add>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.AdaptiveSamplingTelemetryProcessor, Microsoft.AI.ServerTelemetryChannel">
        <MaxTelemetryItemsPerSecond>5</MaxTelemetryItemsPerSecond>
        <IncludedTypes>Event</IncludedTypes>
    </Add>
</TelemetryProcessors>
```

For ASP.NET Core apps, it should be registered **before** `AddApplicationInsightsTelemetry` call:

    public void ConfigureServices(IServiceCollection services)
    {
        // ...
        services.AddApplicationInsightsTelemetryProcessor<SignalRTelemetryFilter>();
        services.AddApplicationInsightsTelemetry();
    }

`SignalRTelemetryFilter` code:

    public class SignalRTelemetryFilter : ITelemetryProcessor
    {
        private ITelemetryProcessor Next { get; set; }

        public SignalRTelemetryFilter(ITelemetryProcessor next)
        {
            this.Next = next;
        }

        public void Process(ITelemetry item)
        {
            if (item is RequestTelemetry request &&
                request.Url.AbsolutePath.IndexOf(HubActions.HubPath, StringComparison.InvariantCultureIgnoreCase) >= 0)
            {
                return;
            }

            this.Next.Process(item);
        }
    }
