### ISSUE TITLE
Snapshot uploader not creating minidump

### ISSUE THREAD

**Issue by qbryant** [microsoft/ApplicationInsights-Home#448]
I see the SnapshotUploader process start successfully for my ASP.NET application, but no minidump file gets created.  There's nothing in the log file that indicates it's even tried to create a minidump, like I would expect to see from [here](https://docs.microsoft.com/en-us/azure/azure-monitor/app/snapshot-debugger-troubleshoot#check-the-uploader-logs).  It looks like another process is supposed to be spawned, which actually creates the minidump file.  This doesn't appear to start.  What triggers it?

**Comment by Dmitry-Matveev** [comment]
@pharring should be able to help here.

**Comment by pharring** [comment]
Your application is the other process. Here's a description of how it works:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/snapshot-debugger#how-snapshots-work

**Comment by pharring** [comment]
@qbryant do you have any follow-up questions, or can this be closed?

**Comment by qbryant** [comment]
Apologies, I didn't look at trying to get this to work again yet.  But I don't remember reading that description, and I think it's likely the problem is on my end.  Maybe I just didn't meet the threshold for sending a snapshot.  Anyway, this can be closed, thanks for your help.
