### ISSUE TITLE
When App Insights turned is on in my App Service Plan - App does not load anymore

### ISSUE THREAD

**Issue by mgolois** [microsoft/ApplicationInsights-Home#459]
It's a .net core 3.1 app. it does not have appInsights dlls. Just wants to turn on app insights on the app service plan, but unfortunately. I get a 500 when site tries to load. Im not sure where it's pully that version of appInsight.aspnetcore. Here is the error I get:

```
FileNotFoundException: Could not load file or assembly 'Microsoft.ApplicationInsights.AspNetCore, Version=2.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
Unknown location

ReflectionTypeLoadException: Unable to load one or more of the requested types.Could not load file or assembly 'Microsoft.ApplicationInsights.AspNetCore, Version=2.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)

Loader Exceptions:
Could not load file or assembly 'Microsoft.ApplicationInsights.AspNetCore, Version=2.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
```

**Comment by TimothyMothra** [comment]
@Mikhail-msft please review.

**Comment by mgolois** [comment]
@Mikhail-msft , I think this is caused by our code.
We have a code that does something like:

`var dict = AppDomain.CurrentDomain.GetAssemblies().SelectMany(c=> c.GetTypes().Where(x=> !x.IsAbstract)).ToDictionary(x=> x.Name, x=> x.Type)`

here is the error and trace:


ReflectionTypeLoadException: Unable to load one or more of the requested types. 
Could not load file or assembly
'Microsoft.ApplicationInsights.AspNetCore, Version=2.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
.The system cannot find the file specified.

System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
System.Reflection.RuntimeModule.GetTypes()
System.Reflection.Assembly.GetTypes()
System.Linq.Enumerable+SelectManySingleSelectorIterator<TSource, TResult>.MoveNext()
System.Linq.Enumerable.ToDictionary<TSource, TKey, TElement>(...)

**Comment by TimothyMothra** [comment]
Oh, this may not specifically be an App Service Extension issue.

I don't know how the NetCore attach works, but the DotNet attach uses the GAC to load some assemblies at runtime. 
I'm surprised your app couldn't find the file though.

Just out of curiosity; why are you creating a dictionary of loaded assemblies? Is this an audit or reporting concern?
As a workaround, I think you could exclude where name includes "applicationinsights", but that may defeat your purpose here.
If this is a critical business need you can manually onboard to the SDK. 
Mikhail might have some other suggestions.

**Comment by Mikhail-msft** [comment]
.netcore3.1 one-click turn on support is being rolled out. Your issue appears to be different, though - your app is referencing the ApplicationInsights SDK and the version is being loaded is 2.1, which is quite old one. For reference currently shipped version with the codeless one-click extension is `Microsoft.ApplicationInsights.AspNetCore, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35`

You have couple options there: either uninstall SDK, and rely on the codeless monitoring (which will be fully rolled out to all regions by end of this week) or update the SDK in your code to use the latest version.

**Comment by mgolois** [comment]
@Mikhail-msft , the app/project itself has no reference to the Application Insights SDK. We have only turned on appInsights in the app service plan. So we are using the codeless monitoring option.

When I check the version of the application insight extension installed via kudu by going to https://xxx.scm.azurewebsites.net/ApplicationInsights it's says: 
 
> Pre-Installed Site Extension, version 2.8.33.139, is running.

After further investigation, I see that the errors are coming from the following assemblies

> DiagnosticServices.SnapshotCollector.HostingStartup
> Microsoft.ApplicationInsights
> Microsoft.ApplicationInsights.SnapshotCollector

For some reason the current AppDomain is unable to load or find those dlls.
We have some workarounds as suggested by @TimothyMothra and some colleagues. I'll test that and see

**Comment by mgolois** [comment]
@Mikhail-msft  not sure what's different with .net core 3.1 version, because the .net core 3.0 of the app does not throw any exception.
any thoughts?

**Comment by Mikhail-msft** [comment]
@mgolois , the deployment of 3.1 support is now fully done. Please let us know if the issue still persists.
For the difference reason: the DiagnosticService require application insights dlls to be present and since the 3.1 codeless wasn't supported yet, those dlls were missing from your runtime. Now the issue should be solved.

**Comment by mgolois** [comment]
@Mikhail-msft great to hear! Thank you!!
