### ISSUE TITLE
Error creating Action Group for selected resource group

### ISSUE THREAD

**Issue by mjohanss** [microsoft/ApplicationInsights-Home#464]
Trying to create an Action Group and selecting a different resource-group than the default "Default-ActivityLogAlerts (to be created)". When submitting the request I receive an error stating that I do not have rights to create resource group "Default-ActivityLogAlerts" even though I have selected a different resource group in the UI. It seems that it tries to create the action group within "Default-ActivityLogAlerts" even though I have specified a different one.

**Comment by ofirmanor** [comment]
Thanks for reporting it @mjohanss !
This is a UI regression, the deployment of the fix is already in progress.
Meanwhile, since it only affects the poral, you could use the API/powershell/CLI instead
