### ISSUE TITLE
Link to download ApplicationInsightsAgent.msi is broken

### ISSUE THREAD

**Issue by trinathm** [microsoft/ApplicationInsights-Home#473]
Unable to download ApplicationInsightsAgent.msi from this path http://go.microsoft.com/fwlink/?LinkID=522371.

This forward link is resolving to https://appinsightsstatusmonitor.blob.core.windows.net/version91/ApplicationInsightsAgent.msi 

At this URL, Installaer is not found, probably it has been moved or removed.

**Comment by TimothyMothra** [comment]
@trinathm I believe this is fixed now.
I'm going to close this issue, but please reopen or create a new issue if you need further assistance.
