### ISSUE TITLE
Dependency issues in NuGet packages

### ISSUE THREAD

**Issue by Zenuka** [Microsoft/ApplicationInsights-Home#48]
I'm trying to update the main Microsoft.ApplicationInsights package to 2.0.1 but the dependency on for example Microsoft.ApplicationInsights.DependencyCollector is set to = 2.0.0 instead of >= 2.0.0. See the following error:
`Unable to resolve dependencies. 'Microsoft.ApplicationInsights 2.0.1' is not compatible with 'Microsoft.ApplicationInsights.DependencyCollector 2.0.0 constraint: Microsoft.ApplicationInsights (= 2.0.0)', 'Microsoft.ApplicationInsights.PerfCounterCollector 2.0.0 constraint: Microsoft.ApplicationInsights (= 2.0.0)', 'Microsoft.ApplicationInsights.TraceListener 2.0.0 constraint: Microsoft.ApplicationInsights (>= 2.0.0)', 'Microsoft.ApplicationInsights.Web 2.0.0 constraint: Microsoft.ApplicationInsights (= 2.0.0)', 'Microsoft.ApplicationInsights.WindowsServer 2.0.0 constraint: Microsoft.ApplicationInsights (= 2.0.0)', 'Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel 2.0.0 constraint: Microsoft.ApplicationInsights (= 2.0.0)', 'Serilog.Sinks.ApplicationInsights 2.0.24 constraint: Microsoft.ApplicationInsights (>= 1.2.3)'.`

**Comment by AlexBulankou** [comment]
Please disregard 2.0.1 package update for web/service applications, it was intended for devices. Apologies for confusion, we are planning to release next stable soon which will address the problem.
