### ISSUE TITLE
appInsights with jquery-pjax

### ISSUE THREAD

**Issue by raphaelm22** [Microsoft/ApplicationInsights-Home#52]
What would be the best way to use appInsights with [jquery-pjax](https://github.com/defunkt/jquery-pjax)?

Someone tell if the approach below would have any side effects?

`$(document).on('pjax:complete', function() {
appInsights.trackPageView();
});`

**Comment by SergeyKanzhelev** [comment]
Can you please ask in JS repo: https://github.com/Microsoft/ApplicationInsights-JS/
