### ISSUE TITLE
JAVA - Caused by: java.lang.NoClassDefFoundError: org/apache/http/impl/conn/PoolingClientConnectionManager

### ISSUE THREAD

**Issue by oak-tree** [Microsoft/ApplicationInsights-Home#55]
Hey 

I'm using Java,Tomcat, Spring and log4js. I'm trying to use applicationinsights with those tools. 
I followed this links https://azure.microsoft.com/en-us/documentation/articles/app-insights-java-get-started/

But i get 
Caused by: java.lang.NoClassDefFoundError: org/apache/http/impl/conn/PoolingClientConnectionManager

Any ideas?
Thanks
Alon

**Comment by oak-tree** [comment]
Ok it seems that `applicationInsights` has dependency on https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient/4.5.2
maybe its worth to update the documents for that?

**Comment by gupele** [comment]
Hi @oak-tree 
Thanks for sharing the information.

I am not sure I fully understand, can you please share more details?
What version are you using?
Are you using the SDK or also the Agent?
Are you using the Apache's HttpClient?

Any other information will be appreciated

Thanks

**Comment by oak-tree** [comment]
I did not have  `Apache's HttpClient`. Thanks.

**Comment by SergeyKanzhelev** [comment]
Moved discussion to the Java repo: https://github.com/Microsoft/ApplicationInsights-Java/issues/307  Closing the issue here.

@oak-tree, thanks for reporting!
