### ISSUE TITLE
Write the Performance Metrics information to a file using Application Insights

### ISSUE THREAD

**Issue by AnithaL** [Microsoft/ApplicationInsights-Home#58]
Provide ability to programmatically access the performance metrics and write the metrics information to a text file.I am planning to use Application Insights API only in my application without Azure.Please provide the ability to access the metrics information for custom processing.

**Comment by SergeyKanzhelev** [comment]
Is this what you need: https://dev.applicationinsights.io/ ? Alternatively you can use export feature: https://azure.microsoft.com/en-us/documentation/articles/app-insights-export-telemetry/

Here is how you send metrics to Application Insights:
https://azure.microsoft.com/en-us/documentation/articles/app-insights-api-custom-events-metrics/#track-metric

**Comment by AnithaL** [comment]
I was already looked at the send metrics to Application Insights( https://azure.microsoft.com/en-us/documentation/articles/app-insights-api-custom-events-metrics/#track-metric)
 and using this feature and along with this i need to retrieve the below performance metrics programmatically.

Business Case:
Capture a set of performance metrics at regular (configurable) intervals that accurately provide details service processes.
Example:
    + Threads count
    + UserProcessTime as % - (UPT2-UPT1)/(T2-T1)
    + PrivilegedProcessorTime as %
    + StartTime
    + PagedMemorySize64
    + PeakPagedMemorySize64
    + VirtualMemorySize64
    + WorkingSet64
    + PeakWorkingSet64
    + Environment.ProcessorCount
    + PID
    + Environment.MachineName
