### ISSUE TITLE
Silverlight version?

### ISSUE THREAD

**Issue by birbilis** [Microsoft/ApplicationInsights-Home#6]
why not also have a version for Silverlight apps? 
(I'd love to use it with ClipFlair Studio - http://ClipFlair.net)

**Comment by JakubOleksy** [comment]
Thanks for the feedback. At this time, we don't have any plans to add Silverlight support. We do support Windows Phone and Store applications written in Silverlight.

**Comment by JakubOleksy** [comment]
The best way to get the request prioritized is to do so through our user voice forum:
http://visualstudio.uservoice.com/forums/121579-visual-studio/category/77108-application-insights?query=silverlight

I did a quick search for Silverlight app support and didn't already see an item, you might want to create a new one.
