### ISSUE TITLE
Hierarchical tenants support: enable CSP scenario 

### ISSUE THREAD

**Issue by TheXenocide** [microsoft/ApplicationInsights-Home#64]
I'm not sure which repository this is most correct for, since I feel it's more of an API-level request, but it would be nice if we could specify 2 iKeys so that our customers can have direct access to their own data, but we could also aggregate the data from all of our customers into a single AI resource. I figure this is a long shot, but couldn't hurt to ask. I imagine it as a means of providing a second key with the existing API calls, rather than making two API calls for every piece of telemetry. I'll be testing with continuous export soon, but I think it would be much better to get all of the out-of-box AI dashboards, filters, alerts, etc. and it would be nice to be able to have our IT Support and their IT staff on the customer-only resource, while our engineers could receive alerts from the aggregate instance.

**Comment by SergeyKanzhelev** [comment]
Do you care more about the data reporting or data querying?

cc: @olegsych, @DaleKoetke, @pdrayton 

From data reporting perspective - you need to decide whether you own instrumentation key or customer owns it. There is no shared ownership

From querying perspective - you can give customers and API key to access data [programmatically](https://dev.applicationinsights.io/) or using PowerBI. 

Also you may want to upvote this item on [uservoice](
https://visualstudio.uservoice.com/forums/357324-application-insights/suggestions/15165558-support-for-cross-ikey-queries).

**Comment by TheXenocide** [comment]
The uservoice item seems relevant to me, but I'm more concerned about both the customer and our internal teams being able to leverage the built-in dashboards, filters, and notifications provided in the azure portal within the scope of their interest: the customer seeing dashboards of only their data and our team seeing an aggregate of all customers. I understand we can setup continuous export as well as query by API, but most of our customers won't use APIs or fashion custom queries (some have robust IT shops, but many do not), and we are already seeing benefits of multi-version and multi-environment analysis in aggregate which would be nice to allow our non-developers and developers alike to access; I see some room for us to fashion custom queries and reports, but the experience provided by the AI dashboards in the azure portal are very useful as is and it would be nice if our team could use them in the scope of all deployed environments rather than us having to reinvent the wheel and recreate all the same reports and its also very useful to be able to drill into dependency/trace related data in a visual way. I get that this isn't how it works currently, but I'm suggesting a way to send the data to 2 iKeys simultaneously so that all customers have the option of providing their own resource while we aggregate data from all customers into a single one. If we aggregate all customers into a single resource we can't provide customers an api key to query other customers data, and if we keep every customer in separate resources we have to browse data from every customer separately or make our own queries/reports to mimic the existing functionality.

**Comment by SergeyKanzhelev** [comment]
Have you considered to give permissions to certain apps to your customers? You can make them "readers" for certain resource groups.

You can certainly send data to two keys. It's shouldn't be complicated to implement on SDK side.

I wonder - how similar are those apps? Is it basically the same app that is being run by different customers? Or just tenants of a single application hosted by you?

**Comment by TheXenocide** [comment]
The app is nearly identical, but extensible so there will be customizations that change performance characteristics (but the extension points are uniform, so it will be useful to understand how different customizations impact the common operations). The main issue we would have giving them permission to the aggregate data is the possibility that there is semi-private information customers wouldn't mind us accessing, but wouldn't want their competitors who also use our software to have access to. How would I go about experimenting with sending the same data to two keys? There's so much contextual association and the real sending happens in the background, is it as simple as using two instances of TelemetryClient with different configurations? Maybe an initializer at the end of the order or some other extension point might be an ideal place to replicate all telemetry universally?

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
