### ISSUE TITLE
App Insights should provide a PowerShell Module

### ISSUE THREAD

**Issue by anblanco** [Microsoft/ApplicationInsights-Home#67]
As a developer, I would like to use Application Insights from PowerShell, so that I can combine my applications telemetry with any infrastructure telemetry. I also would like to start instrumenting my scripts with Application Insights, so that I can get more insights into how people are using the code I share.

I think there is a lot of value in using App Insights from PowerShell scripts, but there are two areas that could be improved for a more natural PowerShell experience

1) Creating a new telemetry client
````powershell
#Today
Add-Type -Path "$Path\lib\net45\Microsoft.ApplicationInsights.dll" 
$ai = New-Object -TypeName Microsoft.ApplicationInsights.TelemetryClient
$ai.InstrumentationKey = "iKey"
````
````powershell
#Ideal
$ai = New-TelemetryClient -InstrumentationKey "iKey"
````
2) Using Hashtables is more natural in PowerShell, but not supported in the native SDK.
````powershell
#Today
$ai.TrackEvent('event', @{customProperty='PowerShell!'})

Cannot find an overload for "TrackEvent" and the argument count: "2".
At line:1 char:1
+ $ai.TrackEvent('event', @{customProperty='PowerShell!'})
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest
````
````powershell
#Ideal
$ai.TrackEvent('event', @{customProperty='PowerShell!'})
````

I think that App Insights should provide a PowerShell Module that allows developers / IT pros to more easily collaborate for application telemetry.

**Comment by SergeyKanzhelev** [comment]
This is a great proposal. As I mentioned in PR - the best place for this SDK is [SDK labs](https://github.com/Microsoft/ApplicationInsights-sdk-labs). Or you can ship if from your name and we will be happy to link it from our documentation

**Comment by anblanco** [comment]
@SergeyKanzhelev I've opened a new issue and PR in the App Insights SDK project.

https://github.com/Microsoft/ApplicationInsights-SDK-Labs/issues/78
