### ISSUE TITLE
Typo in AvailabilityData.bond

### ISSUE THREAD

**Issue by dnduffy** [Microsoft/ApplicationInsights-Home#75]
Minor typo in AvailabilityData.bond; the description annotation for the "name" property should end in "...represent.".

**Comment by dnduffy** [comment]
https://mseng.visualstudio.com/AppInsights/ChuckNorris/_git/One-Breeze/pullrequest/180190?path=%2FPublicSchemas%2FCommonSchema%2Fv2.1%2FTelemetry.bond&_a=overview

**Comment by SergeyKanzhelev** [comment]
You'd need to run this tool https://github.com/Microsoft/ApplicationInsights-Home/blob/master/EndpointSpecs/Tools/generateSchema.ps1 to update the schema in this repo
