### ISSUE TITLE
Why is duration a string instead of an int?

### ISSUE THREAD

**Issue by dnduffy** [Microsoft/ApplicationInsights-Home#81]
In AvailabilityData.bond, PageViewData.bond, RemoteDependencyData.bond, and RequestData.bond the "duration" property is defined as a string and a unit test in the node-js repository uses it with a value like "00:00:00.010".
This may be a nice display format but it makes doing calculations on the data very inefficient.  Computing averages etc. would require converting the string to some integer or time format for each record stored in Kusto.

**Comment by SergeyKanzhelev** [comment]
Reading it again I think it is not an issue as Kusto cast duration to datetime format. This [query](https://analytics.applicationinsights.io/Demo?q=H4sIAAAAAAAAA0tJLUjNS0nNS85MLVaoUSguzc1NLMqsSlVILEvXSCktSizJzM%2FTBADJU6JmJgAAAA%3D%3D&timespan=P1D) works as expected: `dependencies | summarize avg(duration)`
