### ISSUE TITLE
using correlation with end-to-end system app maps

### ISSUE THREAD

**Issue by andrasg** [Microsoft/ApplicationInsights-Home#82]
We have a multi tiered application (Angular client, API frontend, API backend, SQL, other http dependencies) currently setup to report into the very same appinsights resource. The reason for this was to enable correlationid based search: show everything we know about a specific call, from top to bottom.
In order to get the application map show things correctly we would need to split the API layers into their own AI resource. In this case though we would loose the correlationid based search and would need to launch queries against multiple AI resources.
Is there a way to get both benefits (appmap, one place to search)?

**Comment by andrasg** [comment]
Looks like this is the relevant uservoice request:

https://visualstudio.uservoice.com/forums/357324-application-insights/suggestions/15165558-support-for-cross-ikey-queries

**Comment by SergeyKanzhelev** [comment]
@andrasg, yes this is a related user voice request and we plan to enable this capability. It is already working for components correlation on the map. See [here](https://github.com/Microsoft/ApplicationInsights-Home/blob/master/app-insights-app-map-preview.md) and we plan to make it easier to track transactions across components.

**Comment by SergeyKanzhelev** [comment]
I'll close the issue for now. Please feel free to re-open if you have more questions. Make sure to vote at user voice so we will notify you when it's complete. (You can also create a new one specifically for transactions correlation as it may be delivered faster than generic query capability)
