### ISSUE TITLE
Cannot use Application Insights SDK in Partial Trust

### ISSUE THREAD

**Issue by dberryalliance** [Microsoft/ApplicationInsights-Home#87]
So, I was trying to embed Application Insights into another Microsoft product that allows for event-driven "plug-ins", and coming up with the error:

`System.Security.SecurityException: Request for the permission of type 'System.Security.Permissions.EnvironmentPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.`

With the stack trace being:

`System.Security.SecurityException
 at System.Security.CodeAccessSecurityEngine.Check(Object demand, StackCrawlMark&amp; stackMark, Boolean isPermSet)
 at System.Security.CodeAccessPermission.Demand()
 at System.Environment.GetEnvironmentVariables()
 at Microsoft.ApplicationInsights.Extensibility.Implementation.Platform.PlatformImplementation..ctor()
 at Microsoft.ApplicationInsights.Extensibility.Implementation.Platform.PlatformSingleton.get_Current()
 at Microsoft.ApplicationInsights.TelemetryClient.Initialize(ITelemetry telemetry)
 at Microsoft.ApplicationInsights.TelemetryClient.Track(ITelemetry telemetry)
 at Microsoft.ApplicationInsights.TelemetryClient.TrackTrace(TraceTelemetry telemetry)
 at Microsoft.ApplicationInsights.TelemetryClient.TrackTrace(String message)`

Unfortunately there's no way for me to elevate the assembly into Full Trust, or to configure trust by the Microsoft product, as it's a cloud-based product.  Therefore, I'll have to wrap Application Insights in a form of RESTful relay service to get what I need.

What I don't understand, exactly, is why the SDK internalizes all of the `TelemetryContext` members that provide data like host name, or SDK version.  Why am I not allowed to supply this information via a configuration, or ITelemetryInitializer implementation?

**Comment by SergeyKanzhelev** [comment]
Thanks for reporting. You can write your own telemetry initializer and supply those values. Like [this](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/75373e57dcf8d646c54ee188461c373f2cc98939/Src/WindowsServer/WindowsServer.Shared/AzureRoleEnvironmentTelemetryInitializer.cs#L44): 

``` Csharp
telemetry.Context.Cloud.RoleInstance = "computerName";
telemetry.Context.GetInternalContext().NodeName = "computerName"; //--> this is not needed if you set Cloud.RoleInstance 
telemetry.Context.GetInternalContext().SdkVersion = "mySdkVersion";
```

**Comment by SergeyKanzhelev** [comment]
I'll close this work item as I created a separate bug in the proper repo. Feel free to re-open if you need more info,

**Comment by dberryalliance** [comment]
Thank you for the insight.  I'll try again to implement this with the information you provided.

**Comment by dberryalliance** [comment]
@SergeyKanzhelev Correction to your example:
`            if (string.IsNullOrEmpty(telemetry.Context.Internal.NodeName) && !string.IsNullOrEmpty(telemetry.Context.Cloud.RoleInstance))
            {
                telemetry.Context.Internal.NodeName = PlatformSingleton.Current.GetMachineName();
            }
            if (string.IsNullOrEmpty(telemetry.Context.Cloud.RoleInstance))
            {
                telemetry.Context.Cloud.RoleInstance = PlatformSingleton.Current.GetMachineName();
            }`

Based on that logic, I have to provide both `NodeName` and `RoleInstance` values to avert a call into the System for the machine name.

**Comment by dberryalliance** [comment]
@SergeyKanzhelev The constructor of the `TransmissionProcessor` calls into the PlatformSingleton, again trying to raise out of partial trust.  I'll log this in the other issue, as well.  There doesn't appear to be a way around that one, so I'm once again stuck.
