### ISSUE TITLE
Alerts for when a custom event is not received for a certain period of time

### ISSUE THREAD

**Issue by nibras85** [Microsoft/ApplicationInsights-Home#91]
This is more of a feature request than an issue. We have an application that tracks custom events (along with metrics). I have an alert setup for when a metric crosses a certain threshold. I'd also like to get alerted if that event isn't fired for a certain period of time. This isn't currently possible. See (https://docs.microsoft.com/en-us/azure/application-insights/app-insights-alerts#how-alerts-work)

**Comment by SergeyKanzhelev** [comment]
Vote here at [user voice](https://visualstudio.uservoice.com/forums/357324-application-insights/suggestions/14428134-add-alerts-based-on-results-of-analytics-queries). Consider [this](http://apmtips.com/blog/2017/01/17/alerting-over-analytics-queries/) as temporary solution
