### ISSUE TITLE
WebApi Request tracking

### ISSUE THREAD

**Issue by steinmr** [Microsoft/ApplicationInsights-Home#93]
Should this work? It works sometimes, and sometimes not. Sometimes it works only when an exception occurs.
Could you point me to the library/code that does this, so that I can debug the reasons between it.

I found code for request tracing in the WebApi.Tracing library, but it works also without it, so the code must be "somewhere" in the other AI-libraries.

**Comment by SergeyKanzhelev** [comment]
@steinmr, thanks for reporting. I believe it may be this issue: https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/175 

@cijothomas have you got a repro?

**Comment by steinmr** [comment]
It might. I tried removing TransferRequestHandler, but it made no visible difference. 
The problem is that if I do a File_New Project, it works. But it suddenly stops working, and sometimes starts working again.
Since it is all "magic" I have no way of debugging the issue, so some insight into the process of tracking requests for WebApi would be great. (Like, are there any filters I can check to see if are there)

**Comment by SergeyKanzhelev** [comment]
Can you pleas better explain what's going on. You create a new application from the default template, run it in VS and after some time telemetry stops flowing?

**Comment by steinmr** [comment]
Hi, sorry for the delay.
I have now reproduced the problem in a super-simple application (attached).
[AINotWorking.zip](https://github.com/Microsoft/ApplicationInsights-Home/files/841553/AINotWorking.zip)
The main point here (I think) is that I'm using OWIN.

To reproduce this, compile the attached application and run it in Debug in Visual Studio.
In Visual studio, open the "Application Insights Search".
There you will see a "Application Start" event.
 - Hitting /api/test/410 will give a 410 back, and this request is _usually_ tracked in AI. Using f.ex. Postman makes it a bit more reliable.
- Hitting /api/test/500 will give a 500 back and this request is tracked in AI.
- Hitting /api/test/200 will give a 200 back and this request is NOT tracked in AI (which is what I want)

thank you for your continued help.

**Comment by SergeyKanzhelev** [comment]
@steinmr thanks for the repro app. I just confirmed that this is the same issue as this one: https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/175 so the same workaround applies (just comment out `<Add>System.Web.Handlers.TransferRequestHandler</Add>`).

It reproes on my machine so I can troubleshoot and fix it now

**Comment by steinmr** [comment]
Thanks, commenting out the element fixed the issue. I tried it before, but it did not work then, but it might have been a different issue causing it not to work.
What happens with TransferRequestHandler commented out? I will keep it commented out for now, until the fixed 2.2 version comes out.

**Comment by SergeyKanzhelev** [comment]
@steinmr it is mostly commented for WCF applications where you will receive two events for every request. If you do not use WCF it should not be a problem to keep it this way

**Comment by SergeyKanzhelev** [comment]
This issue was fixed out of the box in 2.5
