### ISSUE TITLE
Performance - Examples - Inconsistent values and empty When line

### ISSUE THREAD

**Issue by FrancoisM** [Microsoft/ApplicationInsights-Home#94]
Hi,

First let me say that Application Insights is incredibly amazing!

I attached 3 files to show issues:
- duration values are inconsistent
- the window doesn't get wider when more width is required
- the When line is mostly empty: where is the time spent then?

![azureperformance](https://cloud.githubusercontent.com/assets/3176568/23120436/9b78b3a6-f75c-11e6-9cae-a9d438d2a210.png)
![azureperformance2](https://cloud.githubusercontent.com/assets/3176568/23120437/9b7b237a-f75c-11e6-9f2f-f003883a7568.png)
![azureperformance3](https://cloud.githubusercontent.com/assets/3176568/23120958/c6a9b578-f75e-11e6-89e1-2201fd711563.png)

**Comment by SergeyKanzhelev** [comment]
CC: @qubitron, @northtyphoon, @pharring

@FrancoisM thanks for your feedback! People I mentioned as CC will be able to help you with these issues.

**Comment by juliusl** [comment]
Hello Francois, thanks for trying out the Profiler. I'm on the team and I'm hear to offer some explanations. 

1. For the first screenshot, your result actually makes sense. Metric is a measurement of time spent doing something and wall clock time/request duration is the measurement in real time. By looking at the When column it's obvious this request had a bit of blocked time before resuming. For the 2nd/3rd pictures that result is unexpected. If you could download that .etl file and send me it in an email at juliusl@microsoft.com, our engineers would be happy to take a deeper look.

2. Currently working on this bug, for now if you zoom out it should give you more width. (Which I think you figured out judging by the screenshots.)

3. The when line is composed of CPU measurements we get from the .etl trace file. An empty when line means that no to very low CPU resources were being used, likely nothing was happening. From looking at the third picture it seems that here was not much going on then a spike of work, and then not much going on again. 

Thanks for reaching out, and if in the future you encounter any more issues feel free to contact serviceprofilerhelp@microsoft.com and somebody should reply within a day.

**Comment by FrancoisM** [comment]
Tks Julius.

1°) I sent you the etl file by email.
2°) ok
3°) That time doing nothing is exactly what I'm trying to understand and avoid. Here it was after a code deployment so I guess it's related. But more generally speaking sometime there spikes in request duration (>5sec) and all I see in these graphs is white. And I'm like what's going on lol.
