### ISSUE TITLE
Remote Dependencies Graph - Inconsistencies and questions

### ISSUE THREAD

**Issue by FrancoisM** [Microsoft/ApplicationInsights-Home#95]
Find attached a screenshot showing remote dependencies for a Request.
A few issues/questions:
- Why it the first row green block starting after the second row?
- How do you detect dependencies for a given request? As none of my sql query overlap (they are done one after another) I don't expect green blocks to overlap either.
- Is there a way to find these sql queries with Query Performance insights?
- Is there a way to capture some of our code durations to integrate them into that timeline graph (using trace for ex)?

![azureperformance5](https://cloud.githubusercontent.com/assets/3176568/23127047/c2fcaef6-f779-11e6-8c72-536e20ee60e1.png)

**Comment by FrancoisM** [comment]
With regards to capturing custom duration into the timeline I found out I could use the method TrackDepedency :-)

**Comment by SergeyKanzhelev** [comment]
@kartang is actively looking into this screen improvements. @karting, can you please help @FrancoisM here?

@FrancoisM - do you have any other feedback on what improvements would be helpful on this screen?

**Comment by FrancoisM** [comment]
No more comments so far but I'll get back to you if any.

Any ideas re my questions?

**Comment by kartang** [comment]
@FrancoisM 
Why it the first row green block starting after the second row?

- that doesn't seem right to me. Can you please share more details with respect to both the dependencies? Details like the dependency event time, and the duration of the first two items on the grid should be helpful. 

How do you detect dependencies for a given request? As none of my sql query overlap (they are done one after another) I don't expect green blocks to overlap either.

- Currently, we use operation id to find all the dependencies associated with a particular request => `dependency.operationId == request.operationId.` We use event time and duration to identify the overlaps. Please let us know if you find that the event time does not associate correctly with the chart. _We are changing that to match the dependency.parentId with the requestId, which will be in prod later this week._

Is there a way to find these sql queries with Query Performance insights?

- Can you please help us understand more on what were you referring to by "**Query Performance insights**"?

Is there a way to capture some of our code durations to integrate them into that timeline graph (using trace for ex)?

- Currently we only support dependencies on the timeline chart. We can always track a dependency with the respective code duration, and make sure that the dependency has the same operation id as the request, and parent id matching with the associated request id. This way, we will have the code related timelines added to the chart as well. Please let us know if this helps.

**Comment by FrancoisM** [comment]
@kartang 

1) Row ordering
Well all my dependencies are sql queries. And I don't know which one, I just look at my code and the order I call them to try and identify them. I wish there were some way to link some sql dependencies with sql insights on azure.

2) Overlaps
As my dependencies are ony sql query and as I do them one after another (they next one use the previous one result) I don't expect overlaps. Unless you're not showing the correct dependencies, hence my question. But as the dependency only says "database" there not much I can make out of it.

3) Query Performance Insights
As dependency only says "database" I need  a way to know which query was executed so that I can go to the "Query Performance Insights" page of my Azure SQL database on the portal and find the query. If it's not your team working on SQL insights you should talk to them :-)

4) I tried TradeDependency in my code. I have a private util method that I call for each action:

```
public static T TrackDependecy<T>(Func<T> action, string actionName, [CallerMemberName] string callerMemberName = "")
        {
            var startTime = DateTime.UtcNow;
            var timer = Stopwatch.StartNew();
            var success = true;
            try
            {
                return action();
            }
            catch (Exception)
            {
                success = false;
                throw;
            }
            finally
            {
                timer.Stop();
                var telemetry = new Microsoft.ApplicationInsights.TelemetryClient();
                telemetry.TrackDependency($"[{callerMemberName}][{actionName}]", actionName, startTime, timer.Elapsed, success);
            }
        }
```

Here is an example of how I call it:

```
var listOfPicsUserLikes = await TrackDependecyAsync(() => context.Likes
                .Where(y => y.UserId == userId)
                .Select(y => y.PicId).ToListAsync(), "listOfPicsUserLikes").ConfigureAwait(false);
```

The problem is while all my action do occur, some of my dependencies do not appear on the graph.
For example, I have a request that makes 5 sql queries. All these 5 queries are called through my private util method. In the graph I see 5 database dependencies but only 2 of my custom dependencies.

**Comment by FrancoisM** [comment]
Today, I have an instance where all rows overlap:

![azureperformance6](https://cloud.githubusercontent.com/assets/3176568/23216806/8e5bb18e-f917-11e6-94b9-8995ed4efbaa.png)

**Comment by FrancoisM** [comment]
I think I know why rows overlap. It's because we rely on `DateTime.UtcNow` to be accurate to the millisecond but it is not. See that [article](https://blogs.msdn.microsoft.com/ericlippert/2010/04/08/precision-and-accuracy-of-datetime/).

**Comment by FrancoisM** [comment]
I rewrote my TrackDependency to avoir DateTime.UtcNow. You should do the same.

```
public class DependencyTracker
        {
            private readonly DateTime _starTime;
            private readonly Stopwatch _timer;
            public DateTime CurrenTime => _starTime + _timer.Elapsed;

            public DependencyTracker()
            {
                _starTime = DateTime.UtcNow;
                _timer = new Stopwatch();
                _timer.Start();
            }

            public T TrackDependency<T>(Func<T> action, string actionName, [CallerMemberName] string callerMemberName = "")
            {
                var startTime = CurrenTime;
                var timer = Stopwatch.StartNew();
                var success = true;
                try
                {
                    return action();
                }
                catch (Exception)
                {
                    success = false;
                    throw;
                }
                finally
                {
                    timer.Stop();
                    var telemetry = new Microsoft.ApplicationInsights.TelemetryClient();
                    var elapsed = timer.Elapsed;
                    telemetry.TrackDependency($"[{startTime: hh:mm:ss:fff}][{callerMemberName}][{actionName}][{elapsed.Milliseconds} ms]", actionName, startTime, elapsed, success);
                }
            }

            public async Task<T> TrackDependecyAsync<T>(Func<Task<T>> actionAsync, string actionName, [CallerMemberName] string callerMemberName = "")
            {
                var startTime = CurrenTime;
                var timer = Stopwatch.StartNew();
                var success = true;
                try
                {
                    return await actionAsync();
                }
                catch (Exception)
                {
                    success = false;
                    throw;
                }
                finally
                {
                    timer.Stop();
                    var telemetry = new Microsoft.ApplicationInsights.TelemetryClient();
                    var elapsed = timer.Elapsed;
                    telemetry.TrackDependency($"[{startTime: hh:mm:ss:fff}][{callerMemberName}][{actionName}][{elapsed.Milliseconds} ms]", actionName, startTime, elapsed, success);
                }
            }
        }
```

And here is how I use it:

```
[HttpPost]
        [AllowAnonymous]
        [Route(ApiHelper.ApiPath.Login)]
        public HttpResponseMessage Login(LoginRequest loginRequest)
        {
            var t = new DependencyTracker();
            var context = t.TrackDependency(() => new SocialAppServiceDevContext() , "NewContext");
            var user = t.TrackDependency(() => context.Users.SingleOrDefault(x => x.Email == loginRequest.Id || x.Name == loginRequest.Id), "GetUser");
            if (user == null) return t.TrackDependency(() => Request.CreateResponse(HttpStatusCode.BadRequest, ApiError.WrongCredentials), "WrongCredentialsUser");
            var sid = t.TrackDependency(() => context.IdMappers.SingleOrDefault(x => x.Provider == "custom" && x.UserId == user.Id)?.Sid, "GettingSid");
            var account = t.TrackDependency(() => context.Accounts.SingleOrDefault(a => a.Id == sid), "GettingAccount");
            if (account == null) return t.TrackDependency(() => Request.CreateResponse(HttpStatusCode.BadRequest, ApiError.WrongCredentials), "WrongCredentialsAccount");
            var incoming = t.TrackDependency(() => Hash(loginRequest.Password, account.Salt), "Hash");
            var isLoginOk = t.TrackDependency(() => SlowEquals(incoming, account.SaltedAndHashedPassword), "SlowEquals");
            if (isLoginOk && account.TempPasswordExpiry != null)
            {
                if (DateTimeOffset.Now.CompareTo(account.TempPasswordExpiry.Value) > 0)
                    return t.TrackDependency(() => Request.CreateResponse(HttpStatusCode.BadRequest, ApiError.WrongCredentials), "WrongCredentialsPassword");
                return t.TrackDependency(() => Request.CreateResponse(HttpStatusCode.BadRequest, ApiError.TemporaryPassword), "WrongCredentialsExpiredTempPassword");
            }
            return isLoginOk
                ? t.TrackDependency(() => SendToken(user.Id, sid), "SendToken")
                : t.TrackDependency(() => Request.CreateResponse(HttpStatusCode.Unauthorized, ApiError.WrongCredentials), "WrongCredentialsPassword");           
        }
```

Now that looks like that on the graph:

![azureperformance7](https://cloud.githubusercontent.com/assets/3176568/23222326/c3dd4312-f927-11e6-84fe-39d6eff15fc5.png)

**Comment by FrancoisM** [comment]
Is there a color code for the dependencies or is it always green? It'd be great if I could specify a color with TrackDependency.

**Comment by FrancoisM** [comment]
And as you notice it's not Dependency that I track but my code execution. I use TrackDependency because I find the timeline graph so cool!

**Comment by SergeyKanzhelev** [comment]
@cijothomas is the issue @FrancoisM discovered the same as you fixed in `Start` `Stop` of operations timing? Can you please confirm it is fixed in latest betas

**Comment by cijothomas** [comment]
Yes we fixed the accuracy issue arising due to usage of DateTime.UtcNow instead of high precision Timer.
https://github.com/Microsoft/ApplicationInsights-dotnet/issues/358

This should be in Version 2.2 Stable on base sdk. (the fix was in base sdk, not in dependency module)
https://github.com/Microsoft/ApplicationInsights-dotnet/releases/tag/v2.2.0

**Comment by FrancoisM** [comment]
It's not only the accuracy of the calculation of the duration but the start time as well which is not precise hence dependencies occurrences relative to each other are incorrect.

**Comment by SergeyKanzhelev** [comment]
Remaining problem higlighted here is this https://github.com/Microsoft/ApplicationInsights-Home/issues/189 Closing
