### ISSUE TITLE
Deployed mobile app on a new region - Insights did not collect data

### ISSUE THREAD

**Issue by FrancoisM** [Microsoft/ApplicationInsights-Home#97]
I have a mobile app with insights sdk.
It is deployed and collecting data.
I deployed it to another region but it doesn't collect data.

I think there are two ways to collect data:
- the web extension that needs to be activated on the portal (not easy to find the start button): I had not done it. Can it be activated from templates or cli?
- the sdk in the app code: well it is there so why don't I see data?

**Comment by SergeyKanzhelev** [comment]
What do you mean when saying the "mobile insights SDK"? Our recommendation for mobile customers to switch to HockeyApp SDK.

**Comment by FrancoisM** [comment]
I meant application insights sdk (or library or package or whatever it is called lol).
I expected my newly deployed app to collect data as the first one did. But I had to find the Start button on the portal before it does.
I'm not talking about mobile app client here just about backend app (just a rest api really but it's called Azure Mobile App...)

**Comment by SergeyKanzhelev** [comment]
Oh, I see. Sorry for confusion. Now I'm confused by "Start button" on portal. Is it something specific for mobile apps?

**Comment by FrancoisM** [comment]
No. As I didn't see data, I tried several icons on the portal for the Application Insights Resource until I arrived on a page with a big "Start" button to activate the data collection.

**Comment by SergeyKanzhelev** [comment]
@iusafaro - can you please help here? I have limited experience with the Mobile Apps and do not know if there are Start button and what it does.

**Comment by iusafaro** [comment]
Can you please clarify once more:
1) Have you added SDK from Visual Studio?
2) Have you seen any data before enabling Start button?
3) What's the current state of those two instances and can you see the data?

Yes, Start button is not very intuitive - it can be reached from the banner on Overview blade when you don't have any data or by the clicking on un-configured node in Application Map. The recommended way of extension installation is from Application Insights resource menu item (Monitoring section) from Azure Mobile App blade - it does the same as Start button.

**Comment by FrancoisM** [comment]
1. Yes
2. No for the second instance. I don't know for the first one as I added the SDK and enable with Start button about the same time when I created the application insights resource.
3. I can see data for both instance

The initial question is about seeing the SDK and the portable Start button as two different complementary features whereas it seems it's only one feature.

**Comment by iusafaro** [comment]
SDK and Extension are two alternative ways of enabling Application Insights. SDK from VS is preferrable and recommended solution as it provides more configurable options, but Extension is the only way if you don't have an access to the source code and/or unable to redeploy the application. There's also one additional scenario when you may want to have them both - remote dependencies are collected by both approaches, but only Extension allows you to see SQL command texts for SQL external calls.

Only SDK should be enough to start seeing the data. Can you please confirm that you don't see the data before Extension installed?

**Comment by FrancoisM** [comment]
I confirm I had deployed with sdk in my code on last night (as this was the same code of my existing first instance which was successfully collecting data).

This morning no data (while I know for sure beta testers connected in Brazil).

What is possible is that I created the application insight resource on the portal this morning. I don't really remember to be honest. Maybe there is a timestamp createdat somewhere to verify.

**Comment by iusafaro** [comment]
If it was the same code then application sent data to the old AI resource that first instance is connected to. Have you updated the instrumentation key in AI.config before the deployment?

**Comment by FrancoisM** [comment]
I don't have such config file. Instrument key is an app setting in the portal (can't check right now as I'm on my phone). That's maybe the reason! The second instance didn't have an instrumentation key in its app settings until I clicked the Start Button?

**Comment by iusafaro** [comment]
Yes, that seems to be the reason. So if you don't need extended SQL collection functionality (as I've mentioned above) please ensure that you correctly added all nuget packages from Visual Studio and your ApplicationInsights.config contains the right key for all future instances.

**Comment by iusafaro** [comment]
I'm going to close the thread as it seems that we understood the root cause of confusion and I hope we resolved it. Please feel free to re-open it in case of any additional questions.
