### ISSUE TITLE
Duplicated values in name and data field

### ISSUE THREAD

**Issue by saxenark** [microsoft/ApplicationInsights-Home#98]
Hi,

We are using 2.2.0 version of App Insights library in our ASP.NET project. I am assigning different values to the 'data' and 'name' properties of DependencyTelemetry. However, in appinsights, when I view the dependencies, I see that both the name and the data field have one and same value. What could be the possible reason for this?

Thanks

**Comment by saxenark** [comment]
Interesting thing is that this shows up correctly in the App Insights 'Filter' blade, but somehow analytics does not show it correctly. It shows the same value for name and data fields

**Comment by fpintos** [comment]
See also https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/643

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
