### ISSUE TITLE
Trigger the profiler

### ISSUE THREAD

**Issue by FrancoisM** [Microsoft/ApplicationInsights-Home#99]
Hi,

Your profiler tool is great. I have huge performance issues with my Azure Mobile App Backend. I can't find any answers nowhere and your profiler is the only bit of insights I get.
My problem is that it's hard to test the impact of any changes as I can't control when it's run. It's based on sampling and even these I don't know when they happen.

So my question is: Is there a way to trigger the profiler ourselves?
Tks.

**Comment by FrancoisM** [comment]
I just discovered you have a service profiler extension. Why do you hide these gems?
Maybe this what I'm looking for. Don't know yet as it says "no agents running" while the service profiler extensions status is all green checks.

**Comment by SergeyKanzhelev** [comment]
CC @qubitron 

We are not hiding. It's in preview...

**Comment by northtyphoon** [comment]
@FrancoisM You currently can not trigger the profiler yourself. 

How did you install the service profiler extension? Did you use https://www.azureserviceprofiler.com/?

**Comment by FrancoisM** [comment]
Yes I installed it from there.
I checked and still no "agent running".

**Comment by northtyphoon** [comment]
Service Profiler agent is running as a continuous web job in Web App. You can open the Web App resource in https://portal.azure.com and check "ServiceProfiler" status in WebJobs blade. If it's not running, you can click "Logs" button to find out more information. 
If you have further question, you can send the log to serviceprofilerhelp@microsoft.com. We can help you from there.

**Comment by SergeyKanzhelev** [comment]
Please reopen if you still having problems and didn't get needed help over e-mail
